### ISSUE TITLE
orbitControl() should stop zooming if I click outside the canvas

### ISSUE THREAD

**Issue by yuxi-liu-wired** [processing/p5.js#6627] opened 2023-12-13 02:35 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

Chrome 119.0.6045.200

### Operating System

Windows 11

### Steps to reproduce this

Open the following document. Try zooming in and out of the right canvas. Then there is no way to disable scroll-zooming no matter where I press the mouse button.

```javascript
// Shared variables
let vx = 0;
let vy = 0;
let fourVelocity = minkowskiNormalize([vx, vy, 1]);

let circleDiameter = 2;
let dotDiameter = 0.1;
let circleColor = hexToRgb("#ffffff");

let lightConeHeight = 1;
let lightConeColor = hexToRgb("#7887ab");
console.log(lightConeColor);
let spaceCircleColor = hexToRgb("#7887ab");
let spaceCircleDotColor = [255, 0, 0];
const leftSketchBackgroundColor = [0, 0, 0];

const spaceCircleDotTrail = [];
const spaceCircleDotTrailLength = 100;
const spaceCircleDotTrailFading = 0.99;
const scaleFactor = 100;
const canvasSize = 500;

// The vector defining the orientation of the space circle.
let ex = [1, 0, 0];

// Left Sketch: Unit circle with draggable dot
let leftSketch = function (p) {
  let checkboxTrail;
  let dot = { x: 0, y: 0 };
  let dragging = false;

  p.setup = function () {
    p.createCanvas(canvasSize, canvasSize);
    p.noStroke();

    // checkboxTrail = p.createCheckbox("Show trail");
    // checkboxTrail.position(0, 100);
  
  };

  p.draw = function () {
    p.background(0);
    p.translate(p.width / 2, p.height / 2);
    p.scale(scaleFactor);

    p.push()
    let gamma = velocityToLorentzFactor([vx, vy]);
    let theta = Math.atan2(vy, vx);
    p.rotate(theta);
    p.fill(lightConeColor);
    p.ellipse(0, 0, circleDiameter * gamma, circleDiameter);
    p.pop();

    // The projection of space circle to 2D
    p.push();
    // Update the trail array with the new position
    spaceCircleDotTrail.unshift({x: ex[0], y: ex[1]});
    if (spaceCircleDotTrail.length > spaceCircleDotTrailLength) { spaceCircleDotTrail.pop(); }
    // Draw the trail
    let alpha = 1;
    let size = dotDiameter;
    for (let i = 0; i < spaceCircleDotTrail.length; i++) {
      alpha *= spaceCircleDotTrailFading;
      size *= spaceCircleDotTrailFading;
      p.strokeWeight(size);
      p.stroke(spaceCircleDotColor[0] * alpha + leftSketchBackgroundColor[0] * (1 - alpha),
               spaceCircleDotColor[1] * alpha + leftSketchBackgroundColor[1] * (1 - alpha),
               spaceCircleDotColor[2] * alpha + leftSketchBackgroundColor[2] * (1 - alpha));
      if (i < spaceCircleDotTrail.length - 1) {
        p.line(spaceCircleDotTrail[i].x, spaceCircleDotTrail[i].y, 
               spaceCircleDotTrail[i + 1].x, spaceCircleDotTrail[i + 1].y);
      }
    }
    // Draw the current position
    p.fill(spaceCircleDotColor);
    p.ellipse(ex[0], ex[1], dotDiameter, dotDiameter);
    p.pop();

    p.fill(circleColor);
    p.ellipse(0, 0, circleDiameter, circleDiameter);
    p.fill(0, 0, 0);
    p.ellipse(dot.x, dot.y, dotDiameter, dotDiameter);

    if (dragging) {
      let [mouseXTransformed, mouseYTransformed] = getMouseXY(p);
      dot.x = mouseXTransformed;
      dot.y = mouseYTransformed;

      let d = p.dist(0, 0, dot.x, dot.y);
      let epsilon = 0.2; // avoid extremely high velocities
      let bound = (circleDiameter/2) * (1 - epsilon);
      if (d > bound) {
        let angle = p.atan2(dot.y, dot.x);
        dot.x = bound * p.cos(angle);
        dot.y = bound * p.sin(angle);
      }
      vx = dot.x;
      vy = dot.y;
      fourVelocity = minkowskiNormalize([vx, vy, 1]);
      ex = minkowskiProjection(ex, fourVelocity);
    }
  };

  p.mousePressed = function () {
    let [mouseXTransformed, mouseYTransformed] = getMouseXY(p);
    if (p.dist(mouseXTransformed, mouseYTransformed, dot.x, dot.y) < dotDiameter/2) {
      dragging = true;
    }
  };

  p.mouseReleased = function () {
    dragging = false;
  };

  function getMouseXY(p) {
    let mouseXTransformed = (p.mouseX - p.width / 2) / scaleFactor;
    let mouseYTransformed = (p.mouseY - p.height / 2) / scaleFactor;
    return [mouseXTransformed, mouseYTransformed];
  }
};

new p5(leftSketch, 'velocity-canvas');

// Right Sketch: spacetime diagram
let rightSketch = function (p) {
  p.setup = function () {
    p.createCanvas(canvasSize, canvasSize, p.WEBGL);
    p.camera(0, -canvasSize*1.2, 0, 0, 0, 0, 0, 0, 1);
  };
  let detailX = 50;
  let detailY = 50;
  let timelikeHyperboloid = new p5.Geometry(detailX, detailY, function() {
    for (let i = 0; i <= detailX; i++) {
      let theta = p.map(i, 0, detailX, 0, p.TWO_PI);
      for (let j = 0; j <= detailY; j++) {
        let r = p.map(j, 0, detailY, 0, 5);
        let x = Math.sinh(r) * Math.cos(theta);
        let y = Math.sinh(r) * Math.sin(theta);
        let z = Math.cosh(r);
        this.vertices.push(new p5.Vector(x, y, z));
      }
    }
    this.computeFaces();
    this.computeNormals();
  });

  p.draw = function () {
    fourVelocity = minkowskiNormalize([vx, vy, 1]);

    p.orbitControl(1, 1, 1, { freeRotation: true });
    p.scale(scaleFactor)
    p.rotateX(p.PI);
    p.background(0);

    // System-wide plotting.
    // xyz axes with different colors
    p.push();
    p.stroke(255, 0, 0);
    p.line(-1, 0, 0, 1, 0, 0);
    p.stroke(0, 255, 0);
    p.line(0, -1, 0, 0, 1, 0);
    p.stroke(0, 0, 255);
    p.line(0, 0, -1, 0, 0, 1);
    p.pop();
    
    // Plot that should not be affected by the Lorentz transform.
    // The 3-velocity vector.
    p.push();
    p.stroke('red');
    p.strokeWeight(10);
    p.point(vx, vy, 1);
    p.pop();

    // the two hyperboloids
    // p.model(timelikeHyperboloid);

    // The reference point on the space circle.
    p.push();
    p.stroke(spaceCircleDotColor);
    p.strokeWeight(20);
    p.point(ex[0], ex[1], ex[2]);
    p.pop();

    // Plot that should be affected by the Lorentz transform.
    let transform = velocityToLorentzTransform([vx, vy]);
    let transformMatrix = [transform.get([0, 0]), transform.get([0, 1]), transform.get([0, 2]), 0,
                           transform.get([1, 0]), transform.get([1, 1]), transform.get([1, 2]), 0,
                           transform.get([2, 0]), transform.get([2, 1]), transform.get([2, 2]), 0,
                           0, 0, 0, 1];
    p.applyMatrix(...transformMatrix);

    // Draw the vector fourVelocity
    p.push();
    p.stroke(255);
    p.strokeWeight(2);
    p.line(0, 0, 0, 0, 0, 1);
    p.pop();

    // The space circle
    p.push();
    p.beginShape();
    p.noFill();
    p.stroke(circleColor);
    p.strokeWeight(4);
    for (let theta = 0; theta < p.TWO_PI; theta += 0.01) {
      p.vertex(Math.cos(theta), Math.sin(theta), 0);
    }
    p.endShape(p.CLOSE);  
    p.pop();

    // Draw a cone with apex at fourVelocity, pointing towards -z
    p.push();
    p.translate(0, 0, 1);
    p.translate(0, 0, - lightConeHeight/2)
    p.rotateX(p.PI * 0.5);
    p.fill(lightConeColor)
    p.cone(lightConeHeight, lightConeHeight, 24, 1, false);
    p.pop();

    // Draw a cone with apex at -fourVelocity, pointing towards +z
    p.push();
    p.translate(0, 0, -1);
    p.translate(0, 0, + lightConeHeight/2)
    p.rotateX(p.PI * 1.5);
    p.fill(lightConeColor)
    p.cone(lightConeHeight, lightConeHeight, 24, 1, false);
    p.pop();
  };
};
new p5(rightSketch, 'spacetime-canvas');

function hexToRgb(hex) {
  let result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)] : null;
}

function minkowskiProduct(u, v) {
  return u[0] * v[0] + u[1] * v[1] - u[2] * v[2];
}

function minkowskiNormSquared(u) { return minkowskiProduct(u, u); }

function minkowskiNormalize(u) {
  let norm = Math.sqrt(Math.abs(minkowskiNormSquared(u)));
  return [u[0] / norm, u[1] / norm, u[2] / norm];
}

// Requires minkowskiNormSquared(u) = -1, and minkowskiProduct(e, u) = 0
// that is, u is a time-like unit vector that is Minkowski-orthogonal to e.
// In this special case, minkowskiProjection is greatly simplified.
function minkowskiProjection(e, u_prime) {
  // e' = e + <e, u'> u'
  let eu = minkowskiProduct(e, u_prime);
  eu = [e[0] + eu * u_prime[0], e[1] + eu * u_prime[1], e[2] + eu * u_prime[2]];
  return minkowskiNormalize(eu);
}

function normalizeVector(vec) {
  let angle = Math.atan2(vec[1], vec[0]);
  return [Math.cos(angle), Math.sin(angle)];
}

function velocityToRapidity(v) {
  let speed = Math.sqrt(v[0] * v[0] + v[1] * v[1]);
  return Math.atanh(speed);
}
function velocityToRapidityVector(v) {
  let direction = normalizeVector(v);
  let rapidity = Math.atanh(v);
  return [direction[0] * rapidity, direction[1] * rapidity];s
}

function velocityToLorentzFactor(v) {
  let rapidity = velocityToRapidity(v);
  return Math.cosh(rapidity);
}

function velocityToLorentzTransform(v) {
  let rapidity = velocityToRapidity(v);
  let n = normalizeVector(v);
  let cosh = Math.cosh(rapidity);
  let sinh = Math.sinh(rapidity);

  let I = math.identity(3);
  let Kx = math.matrix([[0, 0, 1], 
                        [0, 0, 0], 
                        [1, 0, 0]]);
  let Ky = math.matrix([[0, 0, 0], 
                        [0, 0, 1], 
                        [0, 1, 0]]);
  let K = math.add(math.multiply(n[0], Kx), math.multiply(n[1], Ky));
  let Ksquared = math.multiply(K, K);
  // I + Math.sinh(rapidity) * K + (Math.cosh(rapidity) - 1) * K^2;
  return math.add(math.add(I, 
                                math.multiply(sinh, K)), 
                  math.multiply(cosh - 1, Ksquared));
}
```

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Interactive Graphics with p5.js</title>
    <!-- <link rel="stylesheet" href="style.css" /> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.0/p5.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mathjs@12.2.0/lib/browser/math.min.js"></script>
</head>

<body>
    <div id="velocity-canvas"></div>
    <p>_</p>
    <div id="spacetime-canvas"></div>

</body>
<script src="3d_wigner_sketch.js"></script>

</html>
```

**Comment by yuxi-liu-wired** [comment] 2023-12-13 02:39
I found the solution, but it really should appear somewhere in the tutorial. Better, have a dedicated syntactic sugar for this.

```javascript
    let mouseInCanvas = 
      this.mouseX < this.width &&
      this.mouseX > 0 &&
      this.mouseY < this.height &&
      this.mouseY > 0;
    
    if (mouseInCanvas) {p.orbitControl(1, 1, 1, { freeRotation: true });}
```

**Comment by inaridarkfox4231** [comment] 2023-12-13 07:30
I think the irrelavant code is too long and it's very difficult to understand what the problem is. If you don't clarify the problem, it will be difficult to deal with it.

**Comment by inaridarkfox4231** [comment] 2023-12-13 07:37
If you simply want to prohibit scaling, I think you can set the third argument to 0.
I don't really understand what the problem is, so it would be really helpful if you could explain it in a shorter code.

**Comment by deveshidwivedi** [comment] 2023-12-13 10:29
Hi! @yuxi-liu-wired 
I think in the code you've provided, the p.orbitControl(1, 1, 1, { freeRotation: true }); was placed directly in the draw function without any conditional checks. So, every frame, regardless of the mouse position, the orbitControl was being activated, allowing zooming behavior even if the mouse was outside the canvas.

Other than the solution you've provided, another solution could be that we introduce a variable orbitControlActive to track whether orbitControl should be active or not and modify the draw function to include a conditional check  before applying p.orbitControl.

**Comment by inaridarkfox4231** [comment] 2023-12-13 10:50
If you want scaling to occur only when the cursor is inside the canvas, I think I can help.

**Comment by inaridarkfox4231** [comment] 2023-12-13 11:07
I understand the cause. This is my mistake. I forgot to change the variable named zoomFlag to executeZoom at one place. Here it is.

![Screenshot_20231213-195959~2](https://github.com/processing/p5.js/assets/39549290/f3c99bde-cdf0-49ba-beea-a6bf82e5784a)

I'll correct this as soon as possible.

**Comment by inaridarkfox4231** [comment] 2023-12-13 15:18
In #6169, I made a specification change that fixed a not-so-smart process in which stopping orbitControl operation when cursor moved out of the canvas after operating within the canvas.
At that time, the specifications were supposed to be set so that the scale change using the mouse wheel would stop smoothly when going outside the canvas, but there was a mistake.

[here](https://github.com/processing/p5.js/blob/main/src/webgl/interaction.js#L224)
```js
      // start zoom when the mouse is wheeled within the canvas.
      if (pointersInCanvas) this._renderer.executeZoom = true;
    } else {
      // quit zoom when you stop wheeling.
      this._renderer.zoomFlag = false; // ---BUG IS HERE---
    }
```
I thought I had renamed all the places that said "zoomFlag" to "executeZoom", but I forgot to change one place. This resulted in a bug where you could scale with the mouse wheel even outside the canvas.

This is my fault for overlooking the mistake, and my reviewer, dave pagurek. sorry. I'll fix it as soon as possible. Thank you for reporting the bug.

I have prepared a demo to check whether this behavior is OK.

https://github.com/processing/p5.js/assets/39549290/07f8027f-7bd8-4321-b2b3-ee14e19a4f5a

After performing scaling within the canvas, if the cursor leaves the canvas, the scaling will no longer be performed.
Not only source code is too long, but also there is no link to the demo sketch, so I don't know if this is the correct way to fix it.
However, there is an obvious bug, so I will fix it anyway.

**Comment by inaridarkfox4231** [comment] 2023-12-13 15:51
I don't think it's just me, but I think most people wouldn't know what the problem was even if only the source code was posted. I would appreciate it if you could try to clarify the problem a little more.

**Comment by inaridarkfox4231** [comment] 2023-12-13 17:35
I checked the contents of the sketch.

https://github.com/processing/p5.js/assets/39549290/71b40249-cdd3-479a-870a-3f73ce9dfdf0

After zooming using the mouse wheel inside the canvas, scaling is performed even if you use mousewheel outside the canvas. As I said above, this is a bug caused by my mistake. 
If this pull request is approved, scaling will no longer be performed when using the mouse wheel outside the canvas.

There is no need to implement the spec as mentioned in the title of this issue.

**Comment by inaridarkfox4231** [comment] 2023-12-14 01:31
I think it's easy to understand when it's this simple.

[double sketches](https://openprocessing.org/sketch/2124795)

```js
const canvasSize = 300;

let leftSketch = function (p) {
  p.setup = function () {
    p.createCanvas(canvasSize, canvasSize, p.WEBGL);
    p.noStroke();
  };
  p.draw = function () {
    p.background(128);
		p.orbitControl(1, 1, 1, { freeRotation: true });
		p.lights();
		p.fill("orange");
		p.torus(80, 24, 48);
  };
};
new p5(leftSketch, 'canvas0');

let rightSketch = function (p) {
  p.setup = function () {
    p.createCanvas(canvasSize, canvasSize, p.WEBGL);
		p.noStroke();
  };
  p.draw = function () {
    p.background(128);
		p.orbitControl(1, 1, 1, { freeRotation: true });
		p.lights();
		p.fill("blue");
		p.box(100);
  };
};
new p5(rightSketch, 'canvas1');
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <script src="https://cdn.jsdelivr.net/npm/p5@1.9.0/lib/p5.js"></script>
  <script src="mySketch.js"></script>
  <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>   
  <div id="canvas0"></div>
  <div id="canvas1"></div>
</body>
</html>
```

https://github.com/processing/p5.js/assets/39549290/52a45912-ea80-4054-b049-44505ea689c9

This bug will be resolved once the pull request is merged.

**Comment by inaridarkfox4231** [comment] 2023-12-14 01:59
And...
Thank you very much for using the freeRotation feature. This was really hard to implement. As someone who implemented the specification, I couldn't be happier to see this feature used by users. thank you very much!

**Closed** 2023-12-16 20:03 UTC
Labels: Bug, Area:DOM, Area:WebGL

**Comment by davepagurek** [comment] 2023-12-16 20:05
Thanks for your work on the free rotation mode @inaridarkfox4231! At some point we might want to make that the default behaviour (maybe in a 2.0 release?)
