### ISSUE TITLE
p5.js' web editor gives the "createElement()" error when simply running the default template.

### ISSUE THREAD

**Issue by Ongshu777** [processing/p5.js#4405] opened 2020-03-23 17:51 UTC
#4405 
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)
Web editor.

- p5.js version: The one in the web editor
- Web browser and version: Chrome 80.0.3987.149
- Operating System: Windows 10
- Steps to reproduce this: For me, just running the default code in the web editor.

The error: p5 had problems creating the global function "createElement", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.

**Comment by stalgiag** [comment] 2020-03-23 18:26
Hi @Ongshu777 ! 

Can you give a bit more information? By default code do you mean:
```js
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
}
```
?

Also, can you give the version numbers for your browser and operating system? You can see your chrome version by going to `chrome://version` in your browser URL bar. You can check your Windows version with the "System Information" application. Thanks!

**Comment by Ongshu777** [comment] 2020-03-23 18:50
@stalgiag Yes, the very code. No changes to the code when entering https://editor.p5js.org/#. And the version is edited in.

**Comment by fenilgandhi** [comment] 2020-03-24 13:27
hey @Ongshu777, could not reproduce this. Are you sure, you are not missing out on something ?


![Screenshot from 2020-03-24 18-52-14](https://user-images.githubusercontent.com/9128903/77430089-a4abcf80-6e00-11ea-96ff-828d0d9f6728.png)

**Comment by Ongshu777** [comment] 2020-03-24 14:07
@fenilgandhi  I don't know why you couldn't but:
  
  
![image](https://user-images.githubusercontent.com/51079288/77434247-7a461c00-6dd8-11ea-87ab-56df0e2ed89b.png)

![image](https://user-images.githubusercontent.com/51079288/77434377-acf01480-6dd8-11ea-8d9b-b2a370f35734.png)

![image](https://user-images.githubusercontent.com/51079288/77434410-b8dbd680-6dd8-11ea-9ad7-4ba75141596e.png)

**Comment by akshay-99** [comment] 2020-03-24 15:40
@Ongshu777 Hmm that's really weird. Can you try this in incognito mode with all extensions and addons disabled? There might be something else that is interfering here with p5. Also can you show browser console output? This can be seen by pressing  **ctrl+shift+i** and then clicking on the tab that says "console".

**Comment by DivyamAhuja** [comment] 2020-03-24 16:43
Yes @Ongshu777 can you send screenshot of developer tools console. that might help determine where `createElement()` method is getting defined.....maybe it's same as what @akshay-99 said some add-on interfering with code in editor.

![Screenshot from 2020-03-24 22-10-58](https://user-images.githubusercontent.com/39771050/77452785-5c9aa600-6e1c-11ea-8d10-1ed7ec758153.png)

**Comment by Ongshu777** [comment] 2020-03-24 19:43
@DivyamAhuja As requested:
Browser Console Image:

![image](https://user-images.githubusercontent.com/51079288/77469661-577f2c00-6e07-11ea-8bab-a567ba8d7e2f.png)

I tried on Incognito mode, and the error didn't appear. But the strange thing is, I don't have any browser extensions or add-ons in this browser (as seen in all the screenshots). So why is that happening?

**Comment by fenilgandhi** [comment] 2020-03-25 04:09
Hey @Ongshu777, let's try one thing. Since you are on the editor, login, and save the sketch. then can you share that link with us, so we can have a look and check if it's the sketch or just something with your browser.

**Comment by Ongshu777** [comment] 2020-03-25 06:53
@fenilgandhi Here's [the link](https://editor.p5js.org/ongshu777/present/vTSfp9nvn)

**Comment by Ongshu777** [comment] 2020-03-25 06:55
@fenilgandhi Here's [the link](https://editor.p5js.org/ongshu777/sketches/vTSfp9nvn)

**Comment by fenilgandhi** [comment] 2020-03-25 07:03
Ok i tried and it works fine, so i think it's only something related to your browser. You can try one of the following things and see what works.
- Empty Cache and hard Reload
- Clean your cookies and cache of website
- Try with a different browser maybe ?

**Comment by limzykenneth** [comment] 2020-03-25 14:55
@Ongshu777  For some reason the `createElement` variable has already been set on the `window` object. Can you try typing `createElement` into the browser console, hit enter, and let us know what it returns?

**Comment by Ongshu777** [comment] 2020-03-25 19:01
@limzykenneth I get:
![image](https://user-images.githubusercontent.com/51079288/77571680-a55a6980-6ec5-11ea-8a84-09265b09f8b1.png)

**Comment by DivyamAhuja** [comment] 2020-03-25 20:02
@Ongshu777 You are getting this cause you are logging it after the p5 script is loaded try running `console.log()` from inside the script before function setup

**Comment by limzykenneth** [comment] 2020-03-25 21:14
@Ongshu777 I should have asked this earlier but does whatever sketch you write run at all for you? If it does run as expected without any problems, I would say you can just ignore this message, it's not an error just a message and in this case may be a false positive.

**Comment by Ongshu777** [comment] 2020-03-26 21:14
*Before Setup* gives me: 
![image](https://user-images.githubusercontent.com/51079288/77697422-bf1fad80-6fa6-11ea-9b8f-4f986ce05ecc.png)

**Comment by jcelerier** [comment] 2020-12-09 13:43
Hello,
since this monday I'm hitting the exact same error, as soon I am logging in, tried on both Windows and Linux with Chrome and Firefox.
Also getting weird noises sometimes.

**Comment by limzykenneth** [comment] 2020-12-09 20:52
@jcelerier Can you share a link to an example sketch that shows the problem?

**Comment by jcelerier** [comment] 2020-12-09 21:36
@limzykenneth I have the issue with every sketch - just opening https://editor.p5js.org/ gives me the error.
I'll have the "weird sound" on more complex sketches - will try to find some -, but it will be there or not randomly if I refresh the page.


![that](https://user-images.githubusercontent.com/2772730/101691342-dc31d900-3a6e-11eb-8443-ea06bd97750e.png)

**Comment by akshay-99** [comment] 2020-12-09 22:12
So I just looked it up. Apparently, it might be something with the web editor's accessibility features, as discussed in [this issue](https://github.com/processing/p5.js-web-editor/issues/1208). I was able to replicate this by turning on any of the checkboxes under "Accessible text-based canvas" in accessibility settings. 

The accessibility settings would explain the sound too if you have "Lint warning sound" turned on.

**Comment by jcelerier** [comment] 2020-12-10 09:33
Okay, had a checkbox checked there indeed (weird, first time I go to that menu), and indeed disabling it I don't see the warning for now.

**Comment by Ongshu777** [comment] 2020-12-20 20:26
@akshay-99  Thank you for the workaround.

It appears that if the `Settings -> Accessibility -> Accessible text-based canvas -> Sound` is checked, the error will appear.

While this can get around the issue, I still think that the issue is not fully resolved. For example, a person who would want the setting turned on would still receive this error.

**Comment by akshay-99** [comment] 2020-12-21 06:54
It's mostly a thing with p5.accessibilty, which is automatically imported by the editor when accessibility settings are on. `createElement` is defined as a global function there on [line 724](https://github.com/processing/p5.accessibility/blob/v0.2.0/dist/p5.accessibility.js#L724). It is this definition that clashes when the main library's core initialization process tries to create its own `createElement`. Hence the message. 

On the editor, also notice that this message only appears with p5.js 0.10.0 or later, which was the version in which p5.dom was merged into the main library. p5.accessibility's most recent release was in 2018, before this change, and hence it wasn't an issue at the time.

**Comment by Ongshu777** [comment] 2020-12-21 07:35
@akshay-99 

That is a lot of insight to the problem. This would suggest that the function on line 724 should be renamed or (if possible) removed.

**Comment by limzykenneth** [comment] 2020-12-21 16:12
I would suggest redirecting this issue to the p5.accessibility repo if possible. Thanks.

**Closed** 2020-12-21 17:11 UTC
Labels: bug
