### ISSUE TITLE
image() + createGraphics() not working properly on HDPI retina displays

### ISSUE THREAD

**Issue by mikima** [processing/p5.js#2838] opened 2018-05-02 15:10 UTC
#### Nature of issue?

- [x] Found a bug
- [x] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: 
- Operating System: MacOSX 10.13.4
- Steps to reproduce this: [simple example here
](https://alpha.editor.p5js.org/mikima/sketches/HkEagLDaG)

Using a MacbookPro with Retina Display.

If I draw directly on the canvas, there are no problems.

However, if i create a new object using `createGraphics()`, draw in it and then place it in the canvas using `image()` the image is pixelated. See the attached image: on the left drawing directly on the canvas, on the right using `createGraphics()`.

Is there any way to fix the problem?

![example](https://user-images.githubusercontent.com/907536/39531427-69f37d76-4e2b-11e8-9da3-fa6e21ff5ed1.png)

**Comment by Spongman** [comment] 2018-05-02 15:51
Try calling `pixelDensity(1)` after `createCanvas`.

**Comment by mikima** [comment] 2018-05-04 07:11
Ow. So, there is no solution?

**Comment by Spongman** [comment] 2018-05-04 15:06
One thing you can try is retrieve the configured pixel density, enlarge your graphics by that amount and scale the drawing operations accordingly.

**Comment by kjhollen** [comment] 2018-05-22 00:48
with #2746 merged, in the next release you should be able to do:

`pg.pixelDensity(pixelDensity());`

to make the graphics density to the canvas density.

**Comment by molleindustria** [comment] 2018-07-02 16:28
Is this issue still ongoing?
With a similar system configuration (retina etc) I see a discrepancy in the ways graphic and canvas images are drawn on screen. The example below draws a circle with the same parameters on canvas and on an graphics (p5.Renderer)

```

function setup() {
  
  createCanvas(200, 100);
  var g = createGraphics(100, 100);
  
  ellipseMode(CORNER);
  g.ellipseMode(CORNER);
  
  //density is the same
  print(pixelDensity() + " "+ g.pixelDensity() +" "+displayDensity());
  
  //changing the graphics density to 1 makes it the same size but blurry
  //g.pixelDensity(1);
  
  background(200);
  ellipse(25,25,50,50);
  
  g.ellipse(25,25,50,50);
  image(g,50,0,100,100);
}
```
This is the result. All the densities are the same = 2; 
<img width="196" alt="screen shot 2018-07-02 at 12 08 17 pm" src="https://user-images.githubusercontent.com/12369651/42174884-b95bc86e-7df1-11e8-9e7c-b8388aca3868.png">

Changing the graphics density to 1 I get consistent sizes but the pgraphics is blurred:
<img width="193" alt="screen shot 2018-07-02 at 12 08 47 pm" src="https://user-images.githubusercontent.com/12369651/42174919-d8a2fa12-7df1-11e8-8827-e8736fbd251c.png">

The workaround on my machine is to create the graphics at double size and then draw it half size but would it work the same on other displays?

```
var g;
var SCALE = 2;

function setup() {
  
  createCanvas(200, 100);
  g = createGraphics(100*SCALE, 100*SCALE);
  
  ellipseMode(CORNER);
  g.ellipseMode(CORNER);
  
  background(200);
  ellipse(25,25,50,50);
  
  g.ellipse(25,25,50,50);
  
  image(g,50,0,100,100);
  
}
```

**Comment by kjhollen** [comment] 2018-07-05 20:21
hey @molleindustria, I think the partial fix has been merged but not released yet. When the next release comes out, you should be able to update your sketch to do:

```
g.pixelDensity(pixelDensity());
```

to get the two to match. I was looking at the remaining step a couple weeks ago (to make the two match automatically when the graphics object is created) but it looked like that was already being done in the p5.Graphics constructor. I haven't yet tracked down why it doesn't take hold.

**Comment by kjhollen** [comment] 2018-07-05 22:37
actually, I couldn't reproduce this in master: I think it is fixed! here's a gist with a bleeding edge build of p5.min.js: https://gist.github.com/kjhollen/2f916c1724fcc9e653218d8b81760b1a

I want to say that last time I had tested this, I was moving between an external monitor and the retina screen on my laptop, and that maybe there were still some unexpected behaviors there—but today I'm using just the retina laptop and all seems well. let me know if you have time to test the gist & it works on your end. thanks!

**Comment by lmccart** [comment] 2019-04-09 02:18
indeed, this has been fixed 🎉

**Closed by lmccart** 2019-04-09 02:18 UTC
Labels: help wanted
