### ISSUE TITLE
Limit WebGL textures to gl.MAX_TEXTURE_SIZE

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js#6546] opened 2023-11-09 16:32 UTC
### Increasing Access

There's a hardware limit on the size of textures that can be used in WebGL. (On my Mac it's 16,384; on other systems apparently it is commonly 4096.) If one goes over that, a cryptic WebGL context loss error will be thrown without much indication of the cause. We can internally limit texture sizes to that and provide a friendly error if one asks for something larger to avoid users having to go deep into internal` WebGL errors.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [X] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

Some implementation details:

- `gl.getParameter` is rather slow, so we should do this once and store it rather than calling it every time
- We need to limit width and height to that max size **divided by the pixel density** to make sure the actual pixel size in either dimension doesn't go over it
- I believe this needs to be handled in `p5.Texture` (which I think should handle p5.Framebuffer creation) and maybe also when creating p5.Graphics and the main canvas

**Comment by theGodOfMind** [comment] 2023-11-10 10:29
Hi there! 👋

I'm interested in working on this issue and implementing the enhancement to handle WebGL context loss errors and limit texture sizes in p5.js. I've taken a look at the proposed solution and would like to contribute to its implementation.

I plan to follow these general steps:

1. Handle WebGL context loss error more gracefully.
2. Optimize `gl.getParameter` to improve performance.
3. Limit width and height of textures to the maximum supported size divided by pixel density.
4. Integrate these changes into `p5.Texture` and `p5.Graphics`.

I'll also make sure to update the documentation accordingly. If there are any specific guidelines or considerations I should be aware of, please let me know.

Looking forward to your feedback and guidance on getting started with this contribution! 🚀

**Comment by davepagurek** [comment] 2023-11-10 13:10
Hi, thanks for your interest! I think we don't need to look into all those steps. (1) would maybe be nice but is a bit too general of a goal for right now; (2) is not something we can actually optimize since it's a browser API, but instead just work around it by not calling it often. But (3) and (4) are directly relevant to this issue!

**Comment by sudhanshuv1** [comment] 2023-11-12 15:18
Hey 👋.

I understood this issue but somehow couldn't reproduce the WebGL context loss error in the p5.js online editor. Could you please explain the steps we need to take to reproduce this error? Although having taken a look at the code in `p5.Texture` and `p5.Graphics`, I have come up with the following possible solution:

- Calling `gl.getParameter(gl.MAX_TEXTURE_SIZE)` once in `p5.Texture` and `p5.Graphics` to get the hardware limit value.
- Including an `if` statement in the constructor of `p5.Texture` and `p5.Graphics` to check whether the width and height exceed the hardware limit.
- Throw a user friendly error if it exceeds the hardware limit ( though I don't think a simple `console.log` statement would achieve this and don't know of any other way to display this error to the user).

I am not sure about my last point, but if this solution is actually feasible, I would be happy to contribute if you assign this issue to me.

Thanks! :)

**Comment by davepagurek** [comment] 2023-11-13 13:10
The specific context loss error will depend on the browser and the system. I noticed a context loss on Chrome in an  Amazon Web Services worker, but on my own Mac, I don't get an error, just a warning in the console:

<img width="1112" alt="image" src="https://github.com/processing/p5.js/assets/5315059/5e0a108d-5e2c-4422-b605-9cd5f5564289">

https://editor.p5js.org/davepagurek/sketches/td93FlQYo


In terms of how to handle it, I think maybe we can log a friendly error, but maybe the thing to do is to shrink the size of the graphic or framebuffer? If that's not feasible, then maybe throwing a real error instead of a friendly error will make the problem more obvious so that it's at least clearer what's going on.

**Closed** 2024-03-19 20:11 UTC
Labels: Enhancement, Area:WebGL, Friendly Errors
