### ISSUE TITLE
font load issue

### ISSUE THREAD

**Issue by Zaptronic** [processing/p5.js#1231] opened 2016-02-03 14:54 UTC
I'm using the p5.min.js file from the site and I'm getting this error on iOS.
Font could not be loaded: 
(anonymous function)p5.min.js:6:20927
(anonymous function)p5.min.js:1:22767
onloadp5.min.js:1:21128

Any help or solutions?

**Comment by lmccart** [comment] 2016-02-03 15:25
could you please post your test code, and maybe a screenshot of your file directory?

**Comment by Zaptronic** [comment] 2016-02-03 16:10
You can find my code here: https://github.com/Zaptronic/tomdeweerbeer
I have to add I'm using p5 in a phonegap build app. Not getting the error in safari on iOS. The sketch works without loading a font.

**Comment by lmccart** [comment] 2016-02-03 16:23
thanks.. this is a lot to dig through. is it possible to post a bit of code that is a pared down minimal example of what's not working? otherwise, if it's a general debugging question, the forum is the best place for that: https://forum.processing.org/two/categories/p5-js

**Comment by Zaptronic** [comment] 2016-02-03 16:43
yes. It fails here: 
function preload() {
      standardFont = loadFont("fonts/Cof.ttf");
} 
in sketch.js and the error refers to: 
(anonymous function)p5.min.js:6:20927
(anonymous function)p5.min.js:1:22767 
onloadp5.min.js:1:21128

**Comment by lmccart** [comment] 2016-02-03 16:49
hm, i'm having trouble reproducing.. this is the setup i have. which version of p5.js are you using?

<img width="1132" alt="screen shot 2016-02-03 at 11 48 42 am" src="https://cloud.githubusercontent.com/assets/191056/12789505/22b8e6b6-ca6c-11e5-9b2a-97e14ee8803c.png">

**Comment by Zaptronic** [comment] 2016-02-03 18:20
I'm using version 0.4.21
My setup is a bit more complicated than your example. I made a app using phonegap (build.phonegap.com). I could make a sample app for you but I have to add you iPhone to the device provisioning if you have one. Please send me a private message (if you prefer twitter @SubsurfNL) if you like to have it. You can remotely debug it.

**Comment by toolness** [comment] 2016-02-11 12:40
It's possible that this is due to [opentype.js checking for a HTTP 200 status](https://github.com/nodebox/opentype.js/blob/master/src/opentype.js#L53-L55).

Because PhoneGap is ultimately accessing the local filesystem rather than a remote webserver, the [HTTP response of the ajax request may be 0 instead of 200](http://stackoverflow.com/a/11233086/2422398).

If this is correct, then the bugfix actually lies in the opentype.js project, not in p5, but I'm just speculating.

@Zaptronic can you provide a traceback from an un-minified version of p5.js so we can look at the exact line of code that's being called to throw the error?

**Comment by lmccart** [comment] 2016-10-12 18:20
for organizational purposes, I'm closing this one. @Zaptronic please feel free to reopen if you can post a trackback as requested above.

**Closed by lmccart** 2016-10-12 18:20 UTC
