### ISSUE TITLE
SVG image positioning and scaling

### ISSUE THREAD

**Issue by geoffalday** [processing/p5.js#1179] opened 2015-12-17 20:25 UTC
When loading an SVG image, the positioning and scaling doesn't render as expected. Note the two images used in this example were saved from the same file with the same dimensions.

```
var alien_png;
var alien_svg;

function preload() {
  alien_png = loadImage("data/alien.png");
  alien_svg = loadImage("data/alien.svg");
}

function setup() {
  createCanvas(400, 400);
  fill(0);
  
}

function draw() {
  background(255);
  
  image(alien_png, 10, 10);
  image(alien_svg, 10, 10);
}
```

This is what is rendered with that code:
![svg_bug_1](https://cloud.githubusercontent.com/assets/713227/11880987/a7782b78-a4c9-11e5-9afd-e9455e3e13ec.png)

If I remove the `viewBox` attribute from the SVG...
![alien_svg](https://cloud.githubusercontent.com/assets/713227/11880999/bdf21bd4-a4c9-11e5-86a4-b686ed6bc24d.png)

![alien_svg_viewbox_removed](https://cloud.githubusercontent.com/assets/713227/11881005/c59886de-a4c9-11e5-93ce-06b9234ee4d6.png)

... it renders as expected (at least how I would expect it to):
![svg_bug_2](https://cloud.githubusercontent.com/assets/713227/11881043/f7274456-a4c9-11e5-806c-1786df7ba585.png)

Thanks!

**Comment by DarkPrince304** [comment] 2015-12-22 14:23
@lmccart : What do you think could be the problem here?

**Comment by lmccart** [comment] 2015-12-23 01:32
I would guess it has to do with a conflict between the pixel density and the viewbox property. Is it a feasible workaround to just set `pixelDensity(1)` to disable scaling for retina, or review the viewbox property from the svg file?

**Comment by DarkPrince304** [comment] 2015-12-30 17:31
@lmccart: Sure would like to give it a try, though, I'm interested in knowing what could be the cause of conflict between the viewbox property and Pixel Density. Also what about conditions when the user needs to use the viewbox property? If we go the way of removing the viewbox property?

**Comment by lmccart** [comment] 2016-01-01 03:37
hey @DarkPrince304, it'd be great if you'd like to take a look at this. unfortunately, i don't know too much about svgs and so i don't have a clear idea about what the best fix for this, without digging in further.

my vague guess is that the viewbox property is forcing some scaling or image sizing so it shows up at a specific size. this may be clashing with the fact the canvas is sometimes actually larger than the size set by `createCanvas()` to accommodate high density displays. that is, if you set the canvas to 400x400, but the pixel density of the screen is 2, then the canvas will actually be created at 800x800, and then scaled with css style properties to show up at 400x400.

maybe when the p5.Image is loaded, we need to check if it has the viewbox property, and if so either (a) remove it or (b) set some flag or reset the width and height properties so it is properly scaled.

these are just some quick thoughts, feel free to dig in more and experiment. the `pixelDensity(1)` function may be useful for testing to see if that is related to the issue at all.

maybe @zenozeng who was working with some p5 SVG stuff this summer may have more ideas as well?

**Comment by DarkPrince304** [comment] 2016-01-04 22:34
@lmccart : I agree with everything you said, but when I tested this it seemed to work fine even without removing the viewbox property. I'm using 0.4.20 version. Did you get a chance to test it for yourself aswell?

**Comment by lmccart** [comment] 2016-01-04 23:09
interesting. I have not tried, I'll give it a look a little later.
are you using a retina screen? maybe it could be something that only shows up with displays that have pixel density greater than 1 (which wouldn't happen on non-retina display).

**Comment by DarkPrince304** [comment] 2016-01-08 20:47
Didn't use retina screen since I don't have such a device. Would like to hear about this from you.

**Comment by lmccart** [comment] 2016-01-22 21:08
@geoffalday could you include the svg file you are working with? i'm having trouble reproducing this. thanks.

**Comment by geoffalday** [comment] 2016-01-25 15:51
@lmccart Sure! Here is a zip of the project: http://cl.ly/473q0c0w1g0A

**Comment by lmccart** [comment] 2016-01-25 18:23
Thanks. I just tested in chrome, firefox, and safari and it all looks good. This seems to be a p5 editor specific issue, so I am going to post it over there.
https://github.com/processing/p5.js-editor/issues/204

**Closed by lmccart** 2016-01-25 18:23 UTC
