### ISSUE TITLE
Discrepancies with shader-based THRESHOLD, ERODE, and DILATE Filters at higher pixel densities

### ISSUE THREAD

**Issue by SableRaf** [processing/p5.js#6398] opened 2023-09-06 14:52 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.7.x Beta: https://raw.githubusercontent.com/wong-justin/p5.js/shader-filters-build/lib/p5.js

### Web browser and version

Chrome Version 116.0.5845.140 (Official Build) (arm64)

### Operating System

MacOS Ventura 13.4 (22F66)

### Steps to reproduce this

_Note: this is a follow up to the conversation on https://github.com/processing/p5.js/pull/6324_

Big thanks to @wong-justin, @aferriss, and @aceslowman for getting the shader-based filters up and running in p5.js

I've spotted some quirks in the outputs of `filter(THRESHOLD)`, `filter(ERODE)`, and `filter(DILATE)` when we increase the pixel density. At `pixelDensity(1)`, things look similar to the CPU-based filter, but once we increase the density, some discrepancies start to appear in the output.

For more clarity, I've put together a demo sketch [here](https://editor.p5js.org/SableRaf/sketches/Rvd-Hznpt). You can also see the differences in this generated images:

### `pixelDensity(1)`
![image](https://github.com/processing/p5.js/assets/290261/0385ad4e-071c-4893-a7e4-408208a7f091)

### `pixelDensity(2)`
![image](https://github.com/processing/p5.js/assets/290261/1182d398-2cb8-4f25-bdee-b951e55dcc72)

**Comment by wong-justin** [comment] 2023-09-07 11:23
I believe these three filters will be fixed if they use the same luma calculation as the CPU version. I'll make a PR shortly

**Comment by wong-justin** [comment] 2023-09-08 13:58
So these filters match up now, except for a few artifacts in `THRESHOLD` that depend on browser and pixel density. I'm not sure about the cause or solution.
 
|  | Chrome (v116.0) | (Firefox v117.0) |
|--------|--------|--------|
| `pixelDensity(1)` | ![threshold_on_chromium](https://github.com/processing/p5.js/assets/28441593/34f11127-8d33-444e-b61c-7d5c1600ebaf) | ![threshold_on_firefox](https://github.com/processing/p5.js/assets/28441593/6aa428bd-9b60-4f04-96a2-ff4f97538e3b) |
| `pixelDensity(2)` | ![threshold_chrome_pd2](https://github.com/processing/p5.js/assets/28441593/812c9dae-4746-44b1-9c39-d6107ab8ceb4) | ![threshold_firefox_pd2](https://github.com/processing/p5.js/assets/28441593/284c1b7a-0522-49b9-be16-4ce37dd0d17f) |

I know there was a weird line in the cpu filter about `floor()`ing the threshold, which I think I replicated in the shader. But I guess they're still not quite the same. For reference, cpu filter and shader filter sources:

https://github.com/processing/p5.js/blob/9d71220fc6286bb084fe00a1219159a1599da70b/src/image/filters.js#L201-L222

https://github.com/wong-justin/p5.js/blob/85e11074602f0abecd0c10dee27c1af9caa7e70a/src/webgl/shaders/filters/threshold.frag#L4-L23

```glsl
precision highp float;

varying vec2 vTexCoord;

uniform sampler2D tex0;
uniform float filterParameter;

float luma(vec3 color) {
  // weighted grayscale with luminance values
  return dot(color, vec3(0.2126, 0.7152, 0.0722));
}

void main() {
  vec4 color = texture2D(tex0, vTexCoord);
  float gray = luma(color.rgb);
  // floor() used to match src/image/filters.js
  float threshold = floor(filterParameter * 255.0) / 255.0;
  float blackOrWhite = step(threshold, gray);
  gl_FragColor = vec4(vec3(blackOrWhite), color.a);
}
```

**Comment by davepagurek** [comment] 2023-09-08 14:35
For a potential source of discrepancy at different pixel densities, it looks like the graphic used to do the filter doesn't specify a density: https://github.com/processing/p5.js/blob/9d71220fc6286bb084fe00a1219159a1599da70b/src/image/pixels.js#L578-L584

So if e.g. you're on a 1x display but you have manually set the canvas at `pixelDensity(2)`, I think that means the graphic would be outputting less pixels than expected? Or at least maybe end up with different antialiasing? Do you see the differences go away when you make the filter graphic match the density of the main canvas?

Once at a higher density, for ERODE/DILATE, you may also need to factor the pixel density in here in order to read adjacent pixels properly: (maybe `1/(width*density)`?) https://github.com/processing/p5.js/blob/9d71220fc6286bb084fe00a1219159a1599da70b/src/webgl/p5.RendererGL.js#L1077

**Comment by wong-justin** [comment] 2023-09-11 12:35
I'm a bit fuzzy about `pInst` and the scope of all the hidden variables in a sketch, but I thought `pixelDensity()` sets a global that applies to all renderers when they're created. The differences remained, and the canvas sizes and densities were the same. Example sketch: https://editor.p5js.org/jwong/sketches/HkDei0TqX

**Comment by davepagurek** [comment] 2023-09-11 20:11
Ah yep you're right! I'm not sure what else might be the cause off the top of my head, but at least the difference now is very small, so I think it's fine to not worry about the remaining differences any more (unless someone else has other new leads.)

**Comment by SableRaf** [comment] 2023-09-12 12:15
I agree with Dave it's close enough. Looks good to me! Nice work @wong-justin 🙌

**Closed** 2023-10-07 05:35 UTC
Labels: Bug, Area:WebGL
