### ISSUE TITLE
blendMode(NORMAL) reset

### ISSUE THREAD

**Issue by gregorfa** [processing/p5.js#3579] opened 2019-03-07 21:24 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by gregorfa** [comment] 2019-03-07 21:26
blendMode(NORMAL) doesn’t seem to work here. If you use another mode (DARKEST for example) it will change, but revert to normal does not seem to work. What am I missing?



function setup() {
createCanvas(400, 400);
}

function draw() {
background(220);

blendMode(LIGHTEST);
strokeWeight(30);
stroke(80, 150, 255);
line(25, 25, 75, 75);
//this does not seem to have any effect
blendMode(NORMAL);

stroke(255, 50, 50);
line(75, 25, 25, 75);
noLoop(0);

}

**Comment by stalgiag** [comment] 2019-03-07 23:15
I haven't looked in to the `blendMode` section before but it seems like the [`NORMAL` constant](https://github.com/processing/p5.js/blob/master/src/core/constants.js#L499) is going to evaluate to 'normal' when [being passed to `globalCompositeOperation`](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L168) when it should [probably be 'source-over'.](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation)

**Comment by stalgiag** [comment] 2019-03-08 23:26
Hi @gregorfa actually I just got a chance to test this bug and I wasn't able to reproduce it in Chrome and Windows 10.

Here is a screenshot of your example code with `blendMode(NORMAL)` commented out:
![Screenshot (22)](https://user-images.githubusercontent.com/10382506/54061567-4476cb00-41b6-11e9-9ebe-0458dd4d9509.png)

and with `blendMode(NORMAL)`
![Screenshot (23)](https://user-images.githubusercontent.com/10382506/54061574-4e003300-41b6-11e9-88ff-94f490db2562.png)

I am going to close this issue for organization purposes. If you are still able to reproduce feel free to comment here with more details about your editor (operating system or online editor)/version and I will reopen.

**Comment by gregorfa** [comment] 2019-03-11 22:42
Thank you!  I also got expected results with Chrome.   On the same Windows 10 system I got the problem result running Firefox 65.0.2.  Internet Explorer was also OK.  So the current p5JS Web Editor, Windows 10 Firefox 65.0.2.  Will be interested to see if anyone can get the same result.

Thanks again.

**Comment by stalgiag** [comment] 2019-03-12 02:27
Thanks for the update gregorfa! I am able to reproduce in Firefox.

This seems to be related to #1756 which was fixed a couple of years ago. Looking at Bugzilla there seems to be ongoing parity issues between Firefox and other browsers when it comes to `globalCompositeOperation`. I think my first guess probably still holds, and the problem is that FF doesn't handle 'normal' well here.

**Comment by Ajayneethikannan** [comment] 2019-03-13 20:02
Hello !
Is there any difference between 'source-over' and 'normal'  for globalCompositeOperation ? 
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation) says 'source-over' is the default setting , so maybe we can set value of NORMAL as 'source-over' to resolve this.

**Comment by stalgiag** [comment] 2019-03-25 16:21
@Ajayneethikannan we already have `BLEND` as the default state which evaluates to `'source-over'`. I think the todo might be just to remove `NORMAL` from [the list of possible arguments ](https://github.com/processing/p5.js/blob/0.7.3/src/core/rendering.js#L274)to `blendMode`. `NORMAL` will work in Chrome but we have no reason to assume that there will be parity across those browsers on this. For emphasis we could even add bold styling to the section describing `BLEND` that [says it is the default mode.](https://github.com/processing/p5.js/blob/0.7.3/src/core/rendering.js#L242)

**Closed** 2019-03-26 18:34 UTC
Labels: area:core
