### ISSUE TITLE
issue with capture (video) drawing on chrome

### ISSUE THREAD

**Issue by ofZach** [processing/p5.js#5925] opened 2023-01-03 12:35 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

p5js editor

### Web browser and version

chrome / safari

### Operating System

osx

### Steps to reproduce this

in testing "mirroring" a video, I noticed slightly strange / different behavior with regards to chrome and safari on this code 

https://editor.p5js.org/zachary.lieberman/sketches/6z5VLKeHn

the expect behavior would be to see a mirrored video regardless of which approach was taken to draw it, but on chrome, it's alternating between mirrored and non mirrored which seems wrong to me. 

osx safari 15.5
osx chrome 108.0

**Comment by limzykenneth** [comment] 2023-01-04 15:17
I've tested Chrome, Firefox, and Safari on both macOS and Linux and all tests shows the alternating behaviour for me. Which is to say for any of the browsers `image(cam, cam.width, 0, -cam.width, cam.height);` is not mirroring the image. I'm not sure if this signature is supposed to be able to mirror an image or not though.

**Comment by ofZach** [comment] 2023-01-04 15:30
I would expect it to mirror, but also I'm generally finding image(...) generally doesn't flip if you do a negative width (which seems like a bug to me...  tbh) 

https://editor.p5js.org/zachary.lieberman/sketches/VdItnuGIS

the weird thing is does flip for me on that one version of safari.

**Comment by limzykenneth** [comment] 2023-01-08 12:02
I would say negative width not flipping is intended behaviour, or at least if we were to change it it would be a breaking change. This is also the behaviour of the underlying HTML canvas: https://editor.p5js.org/limzykenneth/sketches/59AQcNfgO

**Comment by somendrakr** [comment] 2023-03-10 17:09
Hello @davepagurek , @limzykenneth and @ofZach I was trying to solve this issue and found out that it is not the image(..) function that flips. Its due to scale(..) function. In the code
https://editor.p5js.org/zachary.lieberman/sketches/6z5VLKeHn
scale(-1,1) is used that flips the view about y-axis(mirror image) due to which video appears mirrored. so whenever if function executes it flips the video image around y due to negative scaling thus it keeps shifting between mirrored and non-mirrored view. 
If we omit the scale function or change its value to scale(1,1) both views will appear same.
I hope this solves the issue.

**Comment by limzykenneth** [comment] 2023-03-10 18:55
@somendrakr That's not quite what the issue is about. The call to `image()` in the provided sketch gave a negative width value in the expectation that it will be flipped in the same way as `scale(-1, 1)` is called. The issue has nothing to do with `scale(-1, 1)` as that is just for demonstration and comparison. In other words, we fully expect `scale()` to flip but not entirely expecting `image()` to not flip

As mentioned in my reply above as well this is more or less intended behaviour because of underlying HTML canvas's behaviour.

**Comment by thecodermaniac** [comment] 2023-03-20 09:04
is the issue resolved ? i wanted to work on the issue

**Comment by thecodermaniac** [comment] 2023-03-20 10:20
let cam;

function setup() {
  createCanvas(windowWidth, windowHeight);

  //create a video capture object
  cam = createCapture(VIDEO);

  //the createCapture() function creates an HTML video tag
  //as well as pulls up image to be used in p5 canvas
  //hide() function hides the HTML video element
  cam.hide();
}

function draw() {
  background(220);

  translate(cam.width, 0);
  scale(-1, 1);
  image(cam, 0, 0);
  
}

the above code does not result in altering of the mirrored video

**Comment by limzykenneth** [comment] 2023-03-20 11:13
Closing this issue for now as the current behaviour matches native canvas behaviour.

**Closed by limzykenneth** 2023-03-20 11:13 UTC
Labels: Bug, Area:Image
