### ISSUE TITLE
Examples involving keyboard events, only one works

### ISSUE THREAD

**Issue by hellonearthis** [processing/p5.js#3450] opened 2019-01-13 02:49 UTC
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Events

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

Was adding to the event keyboard examples and noticed  that only the 1st example actually functions and the following examples don't function.   see https://p5js.org/reference/#/p5/keyPressed

- Web browser and version: Chrome 71.0.3578.98 (Official Build) (64-bit)
- Operating System: Windows 10
- Steps to reproduce this:
Add a 2nd code example to keyboard.js see https://p5js.org/reference/#/p5/keyPressed

**Comment by hkirat** [comment] 2019-01-15 17:45
Hi @hellonearthis 
I would like to work on this issue.

**Comment by sc231997** [comment] 2019-01-28 04:18
@hellonearthis I would like to work on this.

**Comment by sc231997** [comment] 2019-01-28 09:54
@hellonearthis 
I want to try to fix this. 
Where can I find the code where keyPressed() is implemented?

**Comment by hellonearthis** [comment] 2019-01-28 10:34
I have no idea where the code is,  i guess the issue is around having to things tapping into the keyboard event.  But on the demos, i can stop both demos and then try to start the 2nd demo with no luck.

Having only one example is the current fix but it's no solution.

**Comment by limzykenneth** [comment] 2019-01-28 12:32
`keyPressed()` is defined in [here](https://github.com/processing/p5.js/blob/master/src/events/keyboard.js#L176). I would suggest determining whether the problem is limited to the reference page or is it a general bug in the library first before attempting to fix anything.

**Comment by sc231997** [comment] 2019-01-28 13:06
> `keyPressed()` is defined in [here](https://github.com/processing/p5.js/blob/master/src/events/keyboard.js#L176). I would suggest determining whether the problem is limited to the reference page or is it a general bug in the library first before attempting to fix anything.

In `keyIsDown()` reference page also we have two examples and there the function is working as expected. So maybe there is an issue with the library. 

@limzykenneth can you have the look and tell what may be the issue. 

I am new here so not much idea with code base still learning. :)

**Comment by Spongman** [comment] 2019-01-28 16:18
It might be helpful to find which git commit (if any) introduced the bug. `git bisect` Can be used for this.

**Comment by sanketsingh24** [comment] 2019-03-05 20:12
@Ajayneethikannan is this same as #3193, I haven't been following the discussion for some time.

**Comment by Ajayneethikannan** [comment] 2019-03-05 20:32
@sanketsingh24 Yes it is !  . I will make a pull request as soon as my doubts regarding the issue have been cleared. 
Thank you for mentioning it !

**Comment by Ajayneethikannan** [comment] 2019-03-05 20:54
@outofambit with reference to your comment #3569  , I think that the bug is mostly due to the global downkey variable as in #3193 . For confirmation ,we can the event listeners registered for keydown event on the chrome developer tools , and there are three event listeners corresponding to three sketches. If we remove any two event listeners , we can see the keyPressed function working in the remaining one sketch without any errors . 
Also a similar function which depends on the downkeys variable , as in keyPressed() is isKeyDown(), 
so in those sketches too , we can see the second sketch failing, https://p5js.org/reference/#/p5/keyIsDown
would love to hear your thoughts on these issues ,
Thank you !

**Comment by outofambit** [comment] 2019-03-07 00:39
@Ajayneethikannan ohhh yes, that all makes sense! thanks for digging into this! 💟 

I'm going to close this issue in favor of continuing the discussion/work in #3193 since it accurately describes the underlying issue causing the symptoms documented in this issue description. Thanks all!

**Closed by outofambit** 2019-03-07 00:39 UTC
Labels: area:examples, area:io
