### ISSUE TITLE
Images and alpha masks

### ISSUE THREAD

**Issue by soegaard** [processing/p5.js#5343] opened 2021-07-01 18:25 UTC
The example collection for Processing (the Java version) has an example using an alpha mask.
Above the source code one can see the P5 version of the same example.

This screenshot shows the P5 result at the left and the Processing result at the right.
Notice that the transparent areas are reversed in the P5 result.

The mask image contains a circle with blurred edges. The original idea of the Processing
example is to make the user see a circular area of a larger photo. In the P5 version the
effect is instead to block the view of what's inside the circle.

![image](https://user-images.githubusercontent.com/461765/124172037-a0616e00-daa9-11eb-8950-5b675c000468.png)

#### Most appropriate sub-area of p5.js?

- [x ] Core/Environment/Rendering

#### Details about the bug:

https://processing.org/examples/alphamask.html

Latest version of Chrome is used on macOS Big Sur.

**Comment by limzykenneth** [comment] 2021-07-07 13:13
Not sure why this is the case as it should have been fixed as far back as #531. Although I don't see this changing currently as it would be a pretty significant breaking change, maybe the documentation can be updated to reflect this.

**Comment by soegaard** [comment] 2021-07-07 18:43
Maybe The p5.Sj version used in the Processing docs were from before the fix of #531, and Shiffman compensated by changing the image - and then the P5 version was updated? If so the bug is not in P5.Sj but rather the Processing docs.

**Comment by limzykenneth** [comment] 2021-07-08 11:37
@soegaard I had a closer look and what you just mentioned is kinda right. The implementation for p5.js or Processing, example, documentation, or otherwise, are both right, there is no bug. The confusion comes mainly from the mask used, p5.js' alpha mask example and Processing's alpha mask example actually uses two different mask image.

The p5.js mask image uses an image where the circle are transparent (low alpha) which from the documentation "using its alpha channel as an alpha channel for this image" which matches the intended behaviour. For Processing the mask image used is one where the whole image are opaque (full alpha) but the circle is white while the rest is black and from Processing's documentation "This mask image should only contain grayscale data, but only the blue color channel is used" which also matches expectation (the blue channel value is used as the alpha value of the masked image).

It can be confusing when we compare p5.js and its counterparts in Processing but differences like this do exist and usually are intended while parity with Processing is not a goal for p5.js. I'm going to close this issue for now as I don't see any fix would be necessary in this case.

**Closed by limzykenneth** 2021-07-08 11:37 UTC
Labels: bug

**Comment by soegaard** [comment] 2021-07-08 11:51
Thanks for looking into this. 

If I understand correctly, this means the images used for the the p5js code in the Processing (Java version) documentation needs to invert the alphamask in order for the behaviour of the applet and the Processing code below to match.

Note: I see the applets in the Processing (Java version) as previews of what the Processing does (not what P5Js does).

I'll file an issue in the Processing docs instead.
