### ISSUE TITLE
Switching between front and rear camera on a smartphone using P5.js

### ISSUE THREAD

**Issue by GeeveGeorge** [processing/p5.js#4140] opened 2019-11-07 09:13 UTC
@shiffman @outofambit 
Hi Guys,
I have written the program below for switching between front and rear camera on a phone when clicking on the switchBtn. On cliking the button, it doesn't switch as intended. Hope you could have a look at my code and if possible suggest a fix. Thank you! :)

```
var capture;
let switchFlag = false;
let switchBtn;

var options = {
     video: {
        
         facingMode: {
          exact: "user"
        }
     }
   };

function setup() {
  createCanvas(390, 240);
  
  capture = createCapture(options);
  
  switchBtn = createButton('Switch Camera');
  switchBtn.position(19, 19);
  switchBtn.mousePressed(switchCamera);
  
  

}

function switchCamera()
{
  switchFlag = !switchFlag;
  if(switchFlag==true)
  {
   capture.remove();
   options = {
     video: {
        
         facingMode: {
          exact: "environment"
        }
     }
   };

  }
  else
  {
   capture.remove();
   options = {
     video: {
        
         facingMode: {
          exact: "user"
        }
     }
   };
    
  }
  capture = createCapture(options);
  
}
```

**Comment by limzykenneth** [comment] 2019-11-07 12:21
Hi @GeeveGeorge, we usually keep github issues for bug reports and feature requests only. If you have questions about your own code, please post them to the [forum](https://discourse.processing.org/) where you can get help there. Thanks!

**Comment by GeeveGeorge** [comment] 2019-11-07 15:57
Thanks for the reply! I've made a post there. But, I feel like switching between front and rear camera seems to not be working using p5.js . I read other similar topics on the issues page https://github.com/processing/p5.js/issues/1496 , here too the issue seems not to be resolved. Hope someone could update regarding if there has been any changes such that we could switch between the rear and back cameras.

**Comment by limzykenneth** [comment] 2019-11-08 12:44
For me your code above work just fine on Safari iOS 13.2, it is switching as intended between the two cameras on my iPhone SE. If you think there is still a bug, please let us know more about your particular setup, namely the p5.js version, the iOS version and the phone being used.

**Comment by GeeveGeorge** [comment] 2019-11-08 12:50
Hey Kenneth,

Thanks for the reply. Glad to know it's working on your iPhone. I'm on an Android device (Redmi Note 5 Pro) running, Android Oreo  : 8.1.0. I wrote the above code on the p5.js web editor .

**Comment by limzykenneth** [comment] 2019-11-08 12:53
I'll reopen this and see if anyone else can reproduce.

**Comment by GeeveGeorge** [comment] 2019-11-08 12:56
Thank you! :) Hope someone could reproduce it on Chrome and on Androidm

**Comment by GeeveGeorge** [comment] 2019-11-08 13:12
![IMG_20191108_184132](https://user-images.githubusercontent.com/9594201/68479065-706fb200-0257-11ea-87a9-b6c10ba74ec7.jpg)

On clicking switch , the p5.js log reports : error .

**Comment by stalgiag** [comment] 2019-11-11 20:43
I am able to reproduce with Android 8 and latest Chrome.

I am unable to get a stack trace with my current setup but it appears that with Chrome on Android the old capture stream has to be stopped manually before switching. I am saying this based on the error and [on this thread.](https://github.com/philnash/mediadevices-camera-selection/issues/1)

Here is an image of the error:
![Screenshot_20191111-123717_Chrome](https://user-images.githubusercontent.com/10382506/68619726-dc812e80-0480-11ea-8e79-cf31a40754ba.jpg)

**Comment by stalgiag** [comment] 2019-11-11 20:52
Here is the original code with a workaround added:
```js
var capture;
let switchFlag = false;
let switchBtn;

var options = {
     video: {
        
         facingMode: {
          exact: "user"
        }
     }
   };

function setup() {
  createCanvas(390, 240);
  
  capture = createCapture(options);
  
  switchBtn = createButton('Switch Camera');
  switchBtn.position(19, 19);
  switchBtn.mousePressed(switchCamera);
}

function switchCamera()
{
  switchFlag = !switchFlag;
  stopCapture();
  if(switchFlag==true)
  {
   capture.remove();
   options = {
     video: {
         facingMode: {
          exact: "environment"
        }
     }
   };

  }
  else
  {
   capture.remove();
   options = {
     video: {
         facingMode: {
          exact: "user"
        }
     }
   };
  }
  capture = createCapture(options);
}

function stopCapture() {
  let stream = capture.elt.srcObject;
  let tracks = stream.getTracks();

  tracks.forEach(function(track) {
    track.stop();
  });

  capture.elt.srcObject = null;
}
```

**Comment by GeeveGeorge** [comment] 2019-11-11 21:00
Hey @stalgiag , thanks for the reply!
I tried running your code on the web editor.
I am getting an error. I am attaching an image of it below.
![Screenshot_2019-11-12-02-28-26-166_com android chrome](https://user-images.githubusercontent.com/9594201/68620860-628a8d00-04f4-11ea-9332-10c92387f4d1.png)

**Comment by GeeveGeorge** [comment] 2019-11-11 21:02
Hey @stalgiag ,
Just tried running the code. It works perfectly!
Thanks for the reply :)

**Comment by stalgiag** [comment] 2019-11-11 21:12
Great @GeeveGeorge ! 

Not sure what should be done on the library side. Perhaps `p5.MediaElement.stop()` should stop the stream of a capture and get rid of the `srcObject`? Currently `stop()` does the equivalent of:
```js
capture.pause();
capture.time(0);
```
What do you think @limzykenneth ?

**Comment by GeeveGeorge** [comment] 2019-11-11 21:14
Yes, would be great if it was implemented into the library! @limzykenneth @stalgiag

**Comment by limzykenneth** [comment] 2019-11-11 21:26
If the `srcObject` is gotten rid of when calling `stop()` then can media strem operations still be run on it? eg. can `start()` be called on it when `srcObject` is gone? 

What about cleaning up `srcObject` on `remove()`?

**Comment by stalgiag** [comment] 2019-11-11 21:29
Yeah `remove()` might be a better place to do this.

**Comment by limzykenneth** [comment] 2019-11-11 21:31
`remove()` is a p5.Element wide method so how to pin point it to p5.MediaElement I'm not exactly sure. The inheritence there is rather messy.

**Comment by stalgiag** [comment] 2019-11-18 16:28
It would not help with messiness in the inheritance but a quick fix could be to:
```js
if (this instanceof p5.MediaElement) {
  let stream = this.elt.srcObject;
  let tracks = stream.getTracks();

  tracks.forEach(function(track) {
    track.stop();
  });

  this.elt.srcObject = null;
}
```

**Comment by singhvisha** [comment] 2019-11-27 09:11
@limzykenneth 
I would like to work on this too.

**Comment by lmccart** [comment] 2019-11-28 20:44
fixed with https://github.com/processing/p5.js/pull/4166

**Closed by lmccart** 2019-11-28 20:44 UTC
Labels: area:dom
