### ISSUE TITLE
very strange behavior

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#2365] opened 2017-11-15 07:13 UTC
something's definitely not right here...

![screenshot](https://user-images.githubusercontent.com/1088194/32823246-3ef3a7e6-c991-11e7-8c96-bc98f1414c7d.png)

**Comment by Zalastax** [comment] 2017-11-15 15:34
What is the thing you think is wrong? How can it be reproduced?
I see that the example is https://p5js.org/reference/#/p5/beginContour with `ROTATE(PI/3)` added. Comparing that page with your screenshot it looks like the style attribute is different.

**Comment by lmccart** [comment] 2017-12-27 23:37
hmm I'm not able to produce this. can you describe a little more of the behavior you're seeing? this is what I see when I inspect that example. could it have something to do with a browser plugin?
<img width="1488" alt="screen shot 2017-12-27 at 3 36 29 pm" src="https://user-images.githubusercontent.com/191056/34396111-d5caf204-eb1b-11e7-8beb-ec057929eccf.png">

**Comment by lmccart** [comment] 2018-01-13 17:58
i'm going to close this for now, please feel free to reopen if you can give more information. thanks!

**Closed by lmccart** 2018-01-13 17:58 UTC
