### ISSUE TITLE
question: how to load a json file in preload only if it exists

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js#3416] opened 2018-12-20 15:29 UTC
Tried this with with a try/catch in preload and got the error below, after which the sketch hangs on 'Loading'. Might be nice if there was a way to load, for example, a .json config file in preload (without being forced to use the callback version of loadJSON) and have the sketch continue if its not there...

```
> p5.js says: It looks like there was a problem loading your json. Try checking if the file path [config.json] is correct, or running a local server.[https://github.com/processing/p5.js/wiki/Local-server]
p5.js:62653 Uncaught (in promise) Error: [object Object]
    at p5.js:62653
```

**Comment by limzykenneth** [comment] 2018-12-21 19:33
Does it block execution? Does it show with p5.min.js? Is the error callback called when file is not present?

The first message looks like something FES throws. The second message is it coming from [this line](https://github.com/processing/p5.js/blob/master/src/io/files.js#L1142)?

**Comment by dhowe** [comment] 2019-01-08 17:43
The sketch hangs in [the preload case](https://editor.p5js.org/rednoyz/sketches/r1Jp1DfzV):

![image](https://user-images.githubusercontent.com/737638/50848627-bd70c680-13af-11e9-9265-64123effe598.png)

which happens even with a try/catch block:

![image](https://user-images.githubusercontent.com/737638/50848701-e5602a00-13af-11e9-8247-a2197f348d32.png)




and in the preload case:

**Comment by Spongman** [comment] 2019-01-09 02:48
i'm not sure if this is intentional or nor, but i think it's because the `_decrementPreload()` function is only called in the 'success' callback that's passed to `httpDo` by `loadJSON`.

https://github.com/processing/p5.js/blob/1f1463217982fc1ec9416ea370476d4f98597342/src/io/files.js#L155-L164
if we want failure to also progress to `setup()`, then i think the 'error' callback also needs to call `_decrementPreload`.

----
on a completely separate note. i noticed that the error behavior is different for these functions calling `httpDo`. some of them just call `console.error(err)`:

https://github.com/processing/p5.js/blob/1f1463217982fc1ec9416ea370476d4f98597342/src/io/files.js#L578

... and others `throw err`:

https://github.com/processing/p5.js/blob/1f1463217982fc1ec9416ea370476d4f98597342/src/io/files.js#L172

**Comment by limzykenneth** [comment] 2019-01-09 10:33
I think this is intentional behaviour because when you are loading a file in preload without error callbacks the rest of the sketch code may be expecting sucessful load of the file if they are executed. If the sketch proceeds from preload even if it is a 404 the rest of the sketch may just error out itself expecting a file to have already been loaded.

@Spongman The inconsistency probably is due to some legacy code mixed with new code. It probably should be thrown to halt execution.

**Comment by dhowe** [comment] 2019-01-10 02:06
Is there a reason not to throw an error for the preload case, which the user could catch in the admittedly rare case where this was useful? Sketch would still terminate normally if not caught..

**Comment by Spongman** [comment] 2019-01-10 02:09
the problem is that the `throw` doesn't occur until after the `loadXXX` call returns (it happens during the callback). so there's no opportunity to `catch`. in addition, for this reason, i don't think it makes sense to `throw` in the `httpDo` callbacks. there's no user code that can catch that exception, and `setup` won't get called anyway, since `_decrementPreload()` won't have been called in that if-branch.

**Comment by meiamsome** [comment] 2019-01-10 02:31
I don't think we can reasonably achieve this in the current setup.
You can do this:
```javascript
let a;
function preload() {
  a = loadJSON(url, () => {}, () => this._decrementPreload());
}
```
But obviously `_decrementPreload` is internal and should not really be used in this manner.

@Spongman you are right that throwing in those callbacks is a bit strange - mostly they just cause an uncaught promise rejection, which in most browsers is just ignored. I converted some of these to `console.error` already when I noticed there were some throwing and some using `console.error`.

This issue has implications for the promised-based revamp of this loading system (#2698) and so I'm interested in how we would want this to work going forward. In particular, we've yet to find a suitably beginner-friendly way to support preloading blocking execution that isn't confusing. Alternatively, if we had support for `async setup` (#3000) then you could just do preload in there and control when you resolve:
```javascript
let a;
async function setup() {
  try {
    a = await loadJSONAsync(url); // This is not implemented yet
  } catch (e) {}
}
```
Or with current fns:
```javascript
let a;
async function setup() {
  try {
    a = await new Promise((resolve, reject) => loadJSON(url, resolve, reject));
  } catch (e) {}
}
```

**Comment by Spongman** [comment] 2019-01-10 02:42
i'm strongly in favor of the `await loadXXXAsync` in an `async setup`.

```
let loadJSONAsync = (url) => new Promise((resolve, reject) => loadJSON(url, resolve, reject));
```

**Comment by limzykenneth** [comment] 2019-01-10 10:01
I think eventually we will want to move to better support promise based `loadXXX` functions, to be able to use it with async/await is great in terms of beginner friendlyness but from what I see this is still pretty low priority even for the library code base update to ES6.

**Comment by lmccart** [comment] 2019-12-15 15:56
closing this because it is as @limzykenneth points out intended behavior and I believe difficult to implement with the current system.

**Closed by lmccart** 2019-12-15 15:56 UTC
Labels: question
