### ISSUE TITLE
weird behaviour of pmouseX/Y combined with mouseX/Y 

### ISSUE THREAD

**Issue by v-k-** [processing/p5.js#1035] opened 2015-10-25 02:18 UTC
This simple code produces the result in the image below.

    function setup() {
      createCanvas(windowWidth, windowHeight);
    }

    function mouseMoved() {
        if(pmouseX !=0){
        line(pmouseX, pmouseY, mouseX, mouseY);
        }
    }

    function windowResized() {
        resizeCanvas(windowWidth, windowHeight);
    }

There are a lot of lines ending in points where mouse never was. The ones looking like a "hair" or a dragon's scale :) It should be pretty obvious running the code. The same code in java does not produces this artifacts.

I found that [here](http://kubrusly.com/fundom/). And isolated in the code above. In this page it happens rarely and in a different pattern. several lines are draw form the same start point. The pink line in the second picture below. 

<img width="1207" alt="screen shot 2015-10-25 at 12 15 31 am" src="https://cloud.githubusercontent.com/assets/2482677/10716654/13ad62ee-7b27-11e5-8264-a1682235c5bf.png">

![___21](https://cloud.githubusercontent.com/assets/2482677/10716650/f87641c6-7b26-11e5-8f0d-ca7510dca84d.png)

**Comment by limzykenneth** [comment] 2015-10-25 11:27
Can you describe the problem a bit more in detail? ie. what you are trying to achieve and what would be your expected result.

**Comment by v-k-** [comment] 2015-10-25 16:43
Sorry, it seemed obvious to me when I was running the code. 

I edited the 1st post with more info

You can run and see by yourself here. Just keep drawing it will happen. Click to erase.
 
http://kubrusly.com/pmouse_issue/

Can you see it?

thanks

**Comment by limzykenneth** [comment] 2015-10-25 18:18
Thanks, I see what you mean now. It happens to me only very rarely. Are you able to reproduce it reliably?

I'll take a look at the source code and if I can figure out why it is happening I'll post it here.

**Comment by v-k-** [comment] 2015-10-25 21:12
Yes, pretty much. Some times it happens a LOT, almost every segment, sometimes they are rare... But always happen eventually.
tks

**Comment by v-k-** [comment] 2015-10-25 21:23
Humm  if I don't use `mouseMoved()` I can not reproduce this... so perhaps the synchronisation thing is with `mouseMoved()`...

http://kubrusly.com/pmouse_issue/index2.html

code:

  var lastX, lastY;
    function setup() {
      createCanvas(windowWidth, windowHeight);
    }

    function mouseMoved() {
        if(pmouseX !=0){
        line(pmouseX, pmouseY, mouseX, mouseY);
        }
    }

    function windowResized() {
        resizeCanvas(windowWidth, windowHeight);
    }

    function mousePressed(){
        background(255); 
    }

**Comment by lmccart** [comment] 2015-10-25 21:56
hey @v-k- I think this may have been due to a bug that involved when the pcoords were updated vs the normal mouse coords. however, it's difficult for me to confirm the fix since I'm having trouble reproducing on my machine. if you get a chance, could you try running the code with this new version I created and see if that fixes things?
http://cl.ly/code/2X1x2B0X2D21

**Comment by v-k-** [comment] 2015-10-25 23:27
Hello @lmccart. Yep. That seems to fix it. thanks. I did alternate both p5.js versions with the same code. 

http://cl.ly/code/2X1x2B0X2D21 -> no issue

http://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.17/p5.js  -> issue

**Comment by lmccart** [comment] 2015-10-25 23:30
wonderful thanks for testing! it will be incorporated into the next release.

**Closed** 2015-10-25 23:31 UTC

**Comment by v-k-** [comment] 2015-10-25 23:34
:)
glad to help.
