### ISSUE TITLE
Feature request: check p5.js "version" from code.

### ISSUE THREAD

**Issue by grege2** [processing/p5.js#2525] opened 2018-01-10 03:18 UTC
#### Nature of issue?

- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Core

#### Details about the bug: 

- p5.js version: 0.5.16
- Web browser and version: Chrome 63.0.3239.108 
- Operating System: Mac OS 10.12.6

#### New feature details:

It could be useful to have the p5.js version no. accessible from a properties query in code, ie. be able to read the "0.5.16" as above. In my case, this is just to ensure I'm running on a version no earlier than the one I developed on, a reasonable precaution. However, I'm aware that coding to explicit releases can lead to a minefield of special casing, which we already have mountains of in Web design, eg. the plethora of ugly hacks to deal with old Internet Explorers. Maybe p5.js designers are avoiding this.

(PS. Can I get it cleanly from project.version ? I'm not a JS expert.)

Thanks, GE.

**Comment by dhowe** [comment] 2018-01-10 11:09
+1 for this

**Comment by lmccart** [comment] 2018-01-11 00:09
@dhowe the version number is currently at the top of the file: https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.16/p5.js
will see what we can do about including it in the code itself.

**Comment by grege2** [comment] 2018-01-11 00:52
Thanks Lauren.

**Comment by Jared-Sprague** [comment] 2018-01-11 17:48
@grege2 are you talking about a function you can call that will return the version number of the currently loaded p5 library?  For example:  `p5.getVersion()`

**Comment by grege2** [comment] 2018-01-11 18:31
Yes, that was the idea. Cheers, GE.

**Comment by limzykenneth** [comment] 2018-01-11 22:05
I think it can just be a constant attached to the p5 object, ie. `p5.VERSION`

**Comment by Spongman** [comment] 2018-01-11 22:43
> ensure I'm running on a version no earlier than the one I developed on

i'm confused. isn't the version that's running just whatever you specify in the `.html` file?

**Comment by meiamsome** [comment] 2018-01-11 22:45
@Spongman You don't necessarily have control if you're writing a library for p5 or similar

**Comment by grege2** [comment] 2018-01-12 00:21
@Spongman - Mmm, yes at present I specify the p5.js file in my <script> tag for my own development work. But I think I can foresee situations like @meiamsome mentioned, where I might not control the version.

**Comment by mikima** [comment] 2019-11-04 13:03
Yes that would be really useful, like having a `VERSION` constant or `p5.getVersion() `function

**Comment by dhowe** [comment] 2020-01-02 12:20
Reopening as it is important for a number of use-cases. For one, when you are using the editor and want to report a bug in p5.js, there is no easy way (correct me if I'm wrong here) to get the version from the bundled app

**Comment by micuat** [comment] 2021-03-03 13:35
+1 as I also needed the constant from a bundled script.

I think adding this to the constants would make sense (e.g. [THREE.js](https://github.com/mrdoob/three.js/blob/38cd961708c0677dfe2e531fce33eb1a0f73a790/src/constants.js#L1))

**Comment by rt1301** [comment] 2021-03-14 06:40
We could import the version from the package.json file, but it might have some security implications.

**Comment by rt1301** [comment] 2021-03-16 09:12
@lmccart @limzykenneth I would like to work on this, if the issue is open.

**Comment by 4molybdenum2** [comment] 2021-03-16 13:20
@limzykenneth Can I submit a PR if this issue isn't already taken?

**Comment by micuat** [comment] 2021-04-05 08:48
I just noticed that the const is only accessible when p5 is instantiated, which I totally didn't think about. This can be problematic in some (or most) use cases (when you need to check version after loading the module but before instantiation). Or am I missing something? if so please close the issue :)

**Comment by limzykenneth** [comment] 2021-04-05 17:13
Maybe instead of defining the version number in `constants.js` it can be directly attached to `p5` at the end  of this file, ie `p5.VERSION = ""`.

**Closed** 2021-08-18 17:53 UTC
