### ISSUE TITLE
Error when specifying an instance container via passing in the ID of the container element.

### ISSUE THREAD

**Issue by TohWenXiang** [processing/p5.js#5144] opened 2021-03-31 13:14 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible): Instance Mode, Structure

#### Details about the bug:

- p5.js version: v1.2.0
- Web browser and version: Chrome 89.0.4389.90
- Operating System: Windows 10
- Steps to reproduce this:

```
let poissonDiskSamplingSketch = function(P5) {
    P5.setup = function() {
        P5.createCanvas(300, 300);
    };
    
    P5.draw = function() {
        P5.background(50);
    };
};

new p5(poissonDiskSamplingSketch, 'poisson-disk-sampling');
```
This gives the error: 
```
🌸 p5.js says: There's an error as "appendChild" could not be called as a function (on line 55135 in p5.js [http://127.0.0.1:5500/library/p5.js:55135:30]).
Verify whether "this._userNode" has "appendChild" in it and check the spelling, letter-casing (Javacript is case-sensitive) and its type.
For more: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Errors/Not_a_function#What_went_wrong
p5.js:48629 ▶️ Error at line 55135 in "p5._main.default.createCanvas" in p5.js (http://127.0.0.1:5500/library/p5.js:55135:30)

▶️ Called from line 51340 in "p5._setup" in p5.js (http://127.0.0.1:5500/library/p5.js:51340:23)

▶️ Called from line 51300 in "p5._runIfPreloadsAreDone" in p5.js (http://127.0.0.1:5500/library/p5.js:51300:29)

▶️ Called from line 51310 in "p5._decrementPreload" in p5.js (http://127.0.0.1:5500/library/p5.js:51310:27)

▶️ Called from line 3208 in "p5.<anonymous>" in p5.sound.js (http://127.0.0.1:5500/library/addons/p5.sound.js:3208:10)
```

```
let poissonDiskSamplingSketch = function(P5) {
    P5.setup = function() {
        P5.createCanvas(300, 300);
    };
    
    P5.draw = function() {
        P5.background(50);
    };
};

new p5(poissonDiskSamplingSketch, window.document.querySelector('#poisson-disk-sampling'));
```
This works fine.

**Comment by limzykenneth** [comment] 2021-04-08 17:27
The behaviour is as documented [here](https://github.com/processing/p5.js/wiki/Global-and-instance-mode) unless you find another place where we documented that the constructor takes element ID instead?

**Comment by limzykenneth** [comment] 2021-04-08 17:31
I'm not able to replicate this problem. Using just a string arguments work with both Firefox and Chrome on p5.js 1.2.0.

**Comment by TohWenXiang** [comment] 2021-04-09 05:05
I forget to state that I'm using p5.sound [0.3.12] as well in my project. It works fine when I remove it.

**Comment by limzykenneth** [comment] 2021-04-09 13:17
I've tried it with p5.sound as well and it still works as intended. Do you have any extra code other than the example you provided?

**Comment by TohWenXiang** [comment] 2021-04-11 06:16
Here's the link to my gitlab repository.
[Poisson Disk Sampling with P5js](https://gitlab.com/Artemis_Toh/p5js-poisson-disk-sampling)

**Comment by TohWenXiang** [comment] 2021-04-11 06:29
There isn't any other codes other the example, I've publicize my repository so I think you can take a look at it.

**Comment by limzykenneth** [comment] 2021-04-11 10:01
```
<script src="library/p5.js" defer></script>
<script src="library/addons/p5.sound.js" defer></script>

<script src="sketch.js" defer></script>
```

You are loading the libraries and script in asynchronously with `defer` which I believe is what's causing your problem. p5.js does not support asynchronous loading of scripts so the `defer` keyword should not be used here.

**Comment by limzykenneth** [comment] 2021-04-11 10:04
I've cloned the repo and run it on my computer but still isn't able to replicate this problem.

**Comment by TohWenXiang** [comment] 2021-04-11 11:49
Microsoft Edge Version 89.0.774.75 and Firefox Version 87.0 Works

**Comment by TohWenXiang** [comment] 2021-04-11 11:52
I've removed the defer keyword before testing as well.

**Comment by TohWenXiang** [comment] 2021-04-11 12:01
Errors still persist when using Chrome Version 89.0.4389.114

**Comment by TohWenXiang** [comment] 2021-04-13 05:58
I've tested it on the Brave Browser Version 1.22.71 Chromium: 89.0.4389.114

**Comment by TohWenXiang** [comment] 2021-04-13 06:04
Greyfrog over at StackOverflow is having the [same issue](https://stackoverflow.com/questions/64614533/p5js-instance-mode-with-sound-library-is-throwing-error) as well.

**Comment by Qianqianye** [comment] 2024-06-05 19:54
Closing this since we are unable to replicate it

**Closed by Qianqianye** 2024-06-05 19:54 UTC
Labels: Bug
