### ISSUE TITLE
broken links 

### ISSUE THREAD

**Issue by awaywiththespoons** [processing/p5.js#1357] opened 2016-04-11 17:36 UTC
Some of the links in this wiki are broken :(
FYI :)

**Comment by awaywiththespoons** [comment] 2016-04-11 17:36
this page....

https://github.com/processing/p5.js/wiki/Embedding-p5.js

**Comment by lmccart** [comment] 2016-04-12 01:43
thanks! will work on this tomorrow. closing this issue as it is a duplicate of https://github.com/processing/p5.js/issues/1323

**Closed by lmccart** 2016-04-12 01:43 UTC
