### ISSUE TITLE
Gifs generated with saveGif() only contain a single color

### ISSUE THREAD

**Issue by KevinWorkman** [processing/p5.js#5881] opened 2022-12-03 17:38 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [X] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.5.0

### Web browser and version

Chrome 107.0.5304.107

### Operating System

Windows

### Steps to reproduce this

I originally posted this in the Processing forum: https://discourse.processing.org/t/gifs-generated-with-savegif-only-contain-a-single-color/39954

I’ve been pretty excited about the [`saveGif()`](https://p5js.org/reference/#/p5/saveGif) function, but I’m having trouble getting it to work as expected.

Here’s some code I’m trying:

```
let colors = ['red', 'yellow', 'orange', 'green', 'blue', 'purple'];

function setup() {
  createCanvas(400, 400);
  background(32);
  noSmooth();
}

function draw() {
  noStroke();
  fill(random(colors));
  circle(random(width), random(height), random(10, 20));
}

function mousePressed(){
  saveGif('test', 5);
}
```

[(View the sketch in the p5.js editor here.)](https://editor.p5js.org/KevinWorkman/sketches/M6YoHohLl)

The screen fills up with randomly colored circles (I limited the colors in case the issue is related to the gif color palette limitations), and when I press the mouse, I expect a gif of those circles to be saved.

Here’s the GIF exported using a tool called [Screen to Gif](https://www.screentogif.com/):

![animation of randomly colored circles
](https://global.discourse-cdn.com/standard10/uploads/processingfoundation1/original/3X/1/5/155fdcb9299b96f08cbb53398d29dc1cd4555647.gif)

However, if I press my mouse to trigger the saveGif() function, I get something like this:

![animation of single-colored circles](https://global.discourse-cdn.com/standard10/uploads/processingfoundation1/original/3X/0/b/0bcc07fbc54dea612ea014421174335d8e213aa9.gif)

The gif appears to only contain a single color, although I think maybe I have a mix of yellow and black circles. It might also be worth noting that it’s a different color every time I click:

![animation of red circles](https://global.discourse-cdn.com/standard10/uploads/processingfoundation1/original/3X/f/7/f794a763277c3bee7ac848345a02a596a41f6bba.gif)

The replies to the [tweet announcing this feature](https://twitter.com/p5xjs/status/1584251633218641920) seem to include a mix of folks with multi-colored gifs, and folks with gifs like mine.

I’ve tried both Firefox and Chrome on Windows, and Chrome on Android. I've also tried switching to WEBGL mode, which seems to fix the problem for other folks, but I just see black in the recorded gif in WEBGL mode.

**Edit:** It turns out that in WEBGL mode, all of my circles draw in the lower-right quadrant. If my screen magnification is set to 100%, then the GIF shows the circles in the lower-right quadrant.

![circles in lower-right quadrant](https://global.discourse-cdn.com/standard10/uploads/processingfoundation1/original/3X/c/c/cc9d822f00947d314f46a778daba83e4a45fd256.gif)

If it's set to 150% (the default), then I don't see the circles in the saved gif.

![no circles](https://global.discourse-cdn.com/standard10/uploads/processingfoundation1/original/3X/4/3/43fd51c8db363b6afc425c132e5a0393190483bc.gif)

Can anybody help me understand what’s happening? Is this a known behavior of the `saveGif()` function? Can I do anything to make sure my gifs export correctly?

**Comment by davepagurek** [comment] 2022-12-03 19:51
I think the bug might be here: https://github.com/processing/p5.js/blob/5a44d409d7087c22ebf052742f5aed475ed3440c/src/image/loading_displaying.js#L502

I suspect that we should be using `frames[f]` here instead of `frames[0]`, otherwise the palette is just made from the first frame of the gif repeated. I'll test a bit and see if that's the case!

**Comment by davepagurek** [comment] 2022-12-03 20:03
Looks like that fixed it: https://editor.p5js.org/davepagurek/sketches/wZWa8l9jh

I'll make a PR for this soon!

**Comment by davepagurek** [comment] 2022-12-03 22:44
> It turns out that in WEBGL mode, all of my circles draw in the lower-right quadrant. If my screen magnification is set to 100%, then the GIF shows the circles in the lower-right quadrant.

This is an unrelated bug that won't get fixed by my PR but is definitely still a bug! mind making a separate issue for that so we can track it on its own?

**Comment by KevinWorkman** [comment] 2022-12-04 00:03
> I think the bug might be here:
> https://github.com/processing/p5.js/blob/5a44d409d7087c22ebf052742f5aed475ed3440c/src/image/loading_displaying.js#L502
> 
> I suspect that we should be using `frames[f]` here instead of `frames[0]`, otherwise the palette is just made from the first frame of the gif repeated. I'll test a bit and see if that's the case!

This is amazing, thank you for such a fast fix!

> > It turns out that in WEBGL mode, all of my circles draw in the lower-right quadrant. If my screen magnification is set to 100%, then the GIF shows the circles in the lower-right quadrant.
> 
> This is an unrelated bug that won't get fixed by my PR but is definitely still a bug! mind making a separate issue for that so we can track it on its own?

According to [mnse on the Processing forum](https://discourse.processing.org/t/gifs-generated-with-savegif-only-contain-a-single-color/39954/4?u=kevin), this turns out to be a known behavior and not a bug: https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5

**Comment by davepagurek** [comment] 2022-12-04 01:16
Having the WebGL origin be in the center is expected, but do you still have the issue where at certain zoom levels, you see nothing in your export? That seems like something maybe not working as intended within p5

**Closed** 2022-12-05 23:06 UTC
Labels: Bug, Area:Utilities
