### ISSUE TITLE
ortho() rendering blank canvas

### ISSUE THREAD

**Issue by wagedu** [processing/p5.js#6755] opened 2024-01-21 04:58 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9

### Web browser and version

all

### Operating System

all

### Steps:
1. Add ortho()
2. Nothing is displayed
3. Add orbitControl. Still nothing displayed, until one "uses" it (ie. scroll or drag) Then the content is rendered

### Snippet:

```js

function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  background(220);
  orbitControl();
  ortho();
  sphere(100)
}

```

**Comment by Studycode001** [comment] 2024-01-21 08:26
Can I work on this issue?! @wagedu

**Comment by Vishal2002** [comment] 2024-01-21 11:09
@wagedu Bro when I am running the given code I get the spehere with grid.Can you explain what is the issue ?

<img width="960" alt="Screenshot 2024-01-21 163931" src="https://github.com/processing/p5.js/assets/35897449/6c315ac6-1518-4162-98dd-ac329b4af69f">

**Comment by davepagurek** [comment] 2024-01-21 15:59
I think this may be due to the default near/far values of `ortho` not having been updated along with some camera changes in 1.9. I believe this has been addressed in https://github.com/processing/p5.js/pull/6639, maybe someone can confirm whether this is reproducible with [the recent beta build?](https://github.com/processing/p5.js/releases/tag/v1.9.1-1)

**Comment by wagedu** [comment] 2024-01-21 18:22
@Vishal2002 Mate, does it appear **BEFORE** you interact?

To me it doesn't UNTIL interaction.
Attached it not appearing in Firefox & Safari, just in case.

![Screen Shot 2024-01-21 at 15 16 29](https://github.com/processing/p5.js/assets/1332848/50d40b16-11e0-4352-9fe7-23f64ff2763c)
![Screen Shot 2024-01-21 at 15 18 04](https://github.com/processing/p5.js/assets/1332848/f1486887-1785-4c03-8c19-19b06f23bcd9)

**Comment by wagedu** [comment] 2024-01-21 19:21
Also, @davepagurek maybe I should be asking this on the Discord but... do you know of any workaround to make this work in the current 1.9? I tried setting/unsetting a custom camera without luck.
Thanks!

**Comment by davepagurek** [comment] 2024-01-21 19:33
Here are the new default values: https://github.com/diyaayay/p5.js/blob/dc065a2b99fe8110fc617da5682620cc1f444fed/src/webgl/p5.Camera.js#L908-L915

Maybe try setting these manually in your `ortho` call instead of omitting the parameters? i.e.:
```js
ortho(-width/2, width/2, -height/2, height/2, 0, max(width, height) + 800)
```

**Comment by wagedu** [comment] 2024-01-21 19:55
@davepagurek , thanks, now it works perfectly.

Previously I had tried with the values given in the reference, where the "far" value is 500, instead of max(w,h) + 800
And also has the top/bottom signs inverted

Thanks a lot!

**Comment by davepagurek** [comment] 2024-01-21 20:21
Good point, I think the `translate(0,0,500)` in the example is maybe misleading, as it is compensating for the `far` value. I'll see if I can update that for this next release.

**Closed** 2024-01-26 16:15 UTC
Labels: Bug, Area:Core, Area:WebGL
