### ISSUE TITLE
text("hello world") should work out of the box

### ISSUE THREAD

**Issue by jedahan** [processing/p5.js#1802] opened 2017-02-07 23:56 UTC
It would be real nice, if we didn't need to specify an X and Y for it to show up on the canvas. Not sure if this will break things.

**Comment by lmccart** [comment] 2017-02-08 15:08
Hm, so my firt intuition would be for it to default to (0,0)? The problem is that this is the bottom left of the text so it would still not really show up on the screen and might cause more confusion. I'm not sure then where the default position would be. I also wonder if this sets up the expectation that entering image() or even rect() without x/y should show up as well?

**Comment by jedahan** [comment] 2017-02-08 16:51
Yeah this is kinda tricky - have we done breaking changes to the api before?

How bad would it be to encode more complicated defaults for text(), image() and rect()? Would it be surprising for them to be `width/2`, `height/2`? Technically 0, 0 is just as arbitrary, but I'd like to hear counter-arguments.

**Comment by limzykenneth** [comment] 2017-02-09 05:19
I have a personal preference for having things explicit and not do too much by default. Sometimes, if I made a mistake or typo and the default kicks in it usually takes longer to pin down where the error occurs, if I notice it at all. But this is just my preference 😄

**Comment by lmccart** [comment] 2017-02-17 00:28
I tend to feel the same. Another concern is that adding a default for this opens up questions about defaults for a lot of other methods and whether it would be hard to find consistency across them. Also thinking about this as a teaching tool, perhaps it's good to teach students to use methods according to their signature. I'd prefer rather than adding defaults, to finish the work on the friendly errors and provide better warnings if the wrong number of arguments is provided. If this sounds ok, I'd like to close this for now and revisit after the friendly errors have been implemented to see if it's still an issue.

**Comment by dhowe** [comment] 2017-02-17 03:19
I agree. I originally had RiTa objects default to center of screen, then later removed the feature as it caused more confusion (when teaching) than it seemed to help.

**Comment by lmccart** [comment] 2017-03-10 00:02
I haven't heard any other strong opinions so I'm going to table this for now. Let's revisit if it comes up again.

**Closed by lmccart** 2017-03-10 00:02 UTC
