### ISSUE TITLE
CreateCapture constraints not working

### ISSUE THREAD

**Issue by vidasdemo** [processing/p5.js#3667] opened 2019-04-03 22:01 UTC
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by vidasdemo** [comment] 2019-04-03 22:04
Hi, I am using the same code with constraints as is shown in the P5 Dom reference library. Constraint values provided are ignored. I am trying to capture a HD image size on webcam and CreateCapture always returns 300 wide 50 height. Is this a bug?

**Comment by limzykenneth** [comment] 2019-04-04 11:24
@vidasdemo Can you provide an example code demonstrating the problem? Also it would be very helpful if you can fill in the issue template otherwise we may ask you the same questions anyway or we can't isolate the problem.

**Comment by vidasdemo** [comment] 2019-04-04 14:10
Hi

 

Apologies for bit filling in your template…I wasn’t sure if this was bug or “pilot error”!

 

This is the exact code in the p5 dom library… it just returns error

 

function setup() {

  createCanvas(480, 120);

  var constraints = {

    video: {

      mandatory: {

        minWidth: 1280,

        minHeight: 720

      },

      optional: [{ maxFrameRate: 10 }]

    },

    audio: true

  };

  createCapture(constraints, function(stream) {

    console.log(stream);

  });

}

 

Here is another version…. I still get the same error “Error {}”

Console log returns same width, height  of 300,150 regardless of values in constraints.

 

 

var videocam;

 

function setup() {

  // create full screen canvas

  createCanvas(windowWidth,windowHeight);

  background (0,166, 182);  

  console.log("my canvas width",width,"height",height);

  // acquire webcam

  var constraints = {

    video: {

      mandatory: {

        minWidth: 1280,

        minHeight: 720

      }

    }

  };

  videocam = createCapture(constraints,VIDEO);

  console.log ("webcam width", videocam.width, "height", videocam.height);

  console.log ("window width", windowWidth,"windowheight", windowHeight);

   // Hide the video element, and just show the canvas

  videocam.hide();

}

 

function draw() {

 

  

   image (videocam,0,0);

}        

 

 

Interestingly, if I use RTC API from vanilla Javascript I can change constraint options,…

but the whole point of me trying p5 is to be able to use the p5 DOM library and play with capture image in an easier way.

Right now I am  stuck on step 1: being able to control pixel size and accurately determine coordinates when using a HD Webcam source!

Any light you can shine on this will be greatly appreciated!

**Comment by limzykenneth** [comment] 2019-04-04 14:55
Both of the code examples you provided works on my end on macOS 10.14.3, on Firefox, Chrome and Safari.

I will still need you to provide more information, namely the p5.js version you are using, the OS + version you are using, and the browser + version you are using. Also are you using the web editor?

**Comment by vidasdemo** [comment] 2019-04-04 15:21
Tried my system again and error message is gone but…

*	console log is still returning images size of 300 by 150
*	display does not fill the entire canvas size (crops the right hand side)

my css is plain:

 

html, body {

  margin: 0;

  padding: 0;

}

canvas {

  display: block;

}

 

 

On 1st demo my console output is:

 

MediaStream {constructor: Object}

    <constructor>: "MediaStream"

         name: "MediaStream"

 

On second demo my console output is

 

my canvas width 1008 height 567

webcam width 300 height 150

window width 1008 windowheight  567

 

 

My system info is :

 

Windows 10 pro v1809

Chrome browser (latest)

Using P5.js web editor

**Comment by lmccart** [comment] 2019-04-27 22:23
This example (based on your code) is working for me on Mac:
https://editor.p5js.org/lmccart/sketches/4km34wzhP

Does it work for you @vidasdemo? Can anyone else test on windows 10?

**Comment by lmccart** [comment] 2019-04-27 22:24
This other example from your code works as well:
https://editor.p5js.org/lmccart/sketches/1sWjdkEye

One thing I notice is that it does print the webcam width/height as 300 x 150. This is because at the time of logging, the camera is not yet fully initialized, so it prints the default sizing. Despite that, it is showing up at the 1280x720 resolution in the browser.

**Comment by stalgiag** [comment] 2019-04-29 18:40
I am able to get both examples working on Windows 10 in the online editor with latest Chrome. And as you said the incorrect width logging has to do with unfinished initialization if I add:
```
function mousePressed() {
  console.log ("webcam width", videocam.width, "height", videocam.height);
}
```
to the second example and click I get the expected 1280x720

**Comment by vidasdemo** [comment] 2019-05-03 19:38
Thanks for responding.

 

As per your observation I added a delay before displaying image in browser and then I get the full expected resolution size.

As a side issue I also found that I needed to make sure that the webcam image I am displaying is inside canvas size and canvas size is inside browser window. These “experiments” were undertaken because I want my app to work in both landscape and portrait mode.

Probably obvious to you but I’m only a “newbie”!

**Comment by stalgiag** [comment] 2019-05-03 19:46
Cool thanks for responding @vidasdemo. "Newbies" are always welcome. I noticed that you asked a question [on the forum first](https://discourse.processing.org/c/p5js) which is definitely always the correct play if you aren't sure whether the issue is with p5 or your code. Sorry no one responded over there! 

I am closing this now for organization.

**Closed by stalgiag** 2019-05-03 19:46 UTC
