### ISSUE TITLE
webgl's filter function exhibits different behavior in handling transparency than in 1.7.0

### ISSUE THREAD

**Issue by inaridarkfox4231** [processing/p5.js#6514] opened 2023-10-30 12:19 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [X] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

Chrome

### Operating System

Windows11

### Steps:
1. Apply filter(INVERT) to images with transparent background.
2. Paste it onto an opaque canvas.
3. The results obtained are different between 1.7.0 and 1.8.0.

### Snippet:

```js
function setup() {
  createCanvas(400, 400);
  let gr=createGraphics(100,100);
  gr.textAlign(CENTER,CENTER);
  gr.textSize(80);
  gr.text("🦊",50,50);
  gr.filter(INVERT);

  background(128);
  image(gr,100,100);
}
```

## version 1.7.0
![INVERT_170](https://github.com/processing/p5.js/assets/39549290/42e55af2-737e-4a20-980d-a008a5fde3c5)

## version 1.8.0
![INVERT_180](https://github.com/processing/p5.js/assets/39549290/0b89285c-c1c8-4b98-ad31-473f5cc9c8cf)

I'm going to report this as a bug, but I don't know if it can be considered a bug just because the behavior is different.

**Comment by inaridarkfox4231** [comment] 2023-10-30 12:38
For filters other than INVERT, the results when applied to transparent images seem to be different between 1.7.0 and 1.8.0.
[APPLY_FILTER_TO_ALPHA](https://editor.p5js.org/dark_fox/sketches/DZNX2T0MC)

```js
let img;

function preload(){
  img = loadImage("https://inaridarkfox4231.github.io/assets/season/summer_small.png");
}
function setup(){
  createCanvas(img.width, img.height);
  background(img, 64);
  filter(BLUR, 4);
}
```

## version 1.7.0 BLUR

![BLUR_64_170](https://github.com/processing/p5.js/assets/39549290/055b1b11-9289-4e39-aae6-a939ed145bba)

## version 1.8.0 BLUR

![BLUR_64_180](https://github.com/processing/p5.js/assets/39549290/83e7addb-2608-4524-97da-26bb33b87730)

**Comment by perminder-17** [comment] 2023-10-30 14:58
I've noticed some unusual and hazy behavior when attempting to render images using filters in a WebGL renderer. I'm not sure if this is a limitation of using fast GPU filters or if it's a bug. @davepagurek , if you could pinpoint where this buggy behavior is occurring, it would be very helpful.

**Comment by davepagurek** [comment] 2023-10-30 17:06
@perminder-17 my initial guess is that this is also caused by not clearing the canvas in enough places. Similar to how I was suggesting adding a `clear()` in the non-blur branch of `filter`, we might need to add a `clear()` in the blur branch of the if statement here, probably before each `pg.rect()` call:
https://github.com/processing/p5.js/blob/611941ae36de4a1110ffc1f7ad544c2253df1197/src/webgl/p5.RendererGL.js#L1096-L1112

Hopefully that fixes it? Otherwise there might be some additional we have to do in the blur shader with how alpha is handled.

**Comment by davepagurek** [comment] 2023-11-05 01:52
This has now been resolved by https://github.com/processing/p5.js/pull/6503, so I'm going to close this branch for organizational purposes. Let me know if there are any other cases not covered that we still need to fix!

**Closed by davepagurek** 2023-11-05 01:52 UTC
Labels: Bug, Area:Color, Area:WebGL
