### ISSUE TITLE
tint fails in 2d canvas with webgl p5.Graphics

### ISSUE THREAD

**Issue by micuat** [processing/p5.js#5046] opened 2021-02-17 15:52 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.1.9
- Web browser and version: any
- Operating System: any
- Steps to reproduce this:

using `tint` inside a 2D canvas with webgl p5.Graphics causes error
https://editor.p5js.org/micuat/sketches/9hh8x1HjF

```javascript
TypeError: canvas.getContext(...) is null (sketch: line 14)
```

from https://github.com/processing/p5.js/pull/3709#issuecomment-780163378

**Comment by stalgiag** [comment] 2021-02-18 21:25
Thank you @micuat !

This problem is fixed and grunt passes if [the function here](https://github.com/processing/p5.js/blob/main/src/image/filters.js#L34) is changed to:
```js
Filters._toPixels = function(canvas) {
  if (canvas instanceof ImageData) {
    return canvas.data;
  } else {
    if (canvas.getContext('2d')) {
      return canvas
        .getContext('2d')
        .getImageData(0, 0, canvas.width, canvas.height).data;
    } else if (canvas.getContext('webgl')) {
      const gl = canvas.getContext('webgl');
      const len = gl.drawingBufferWidth * gl.drawingBufferHeight * 4;
      const data = new Uint8Array(len);
      gl.readPixels(
        0,
        0,
        canvas.width,
        canvas.height,
        gl.RGBA,
        gl.UNSIGNED_BYTE,
        data
      );
      return data;
    }
  }
};
```

This isn't ideal for a few reasons, it uses `getContext` to check whether the context is 2D or 3D. It also reproduces much of the code from `loadPixels()` which is more efficient because it checks for an existing pixel cache. I don't have time to write a better version right now. Off the top of my head, I think a lot of this could be fixed by passing the renderer instead of the canvas (when there is one). I don't have time to try at this precise moment so if anyone else wants to take it up they are welcome. Otherwise, I can return to this at some point in the next month or so.

**Comment by ShenpaiSharma** [comment] 2021-02-21 12:42
Hi, @stalgiag, I would like to work on this.

**Comment by montoyamoraga** [comment] 2021-02-21 12:45
hi @ShenpaiSharma we assigned this issue to you,
please link it when you submit a PR, good luck, and thanks!

**Closed** 2021-03-28 13:18 UTC
Labels: area:webgl, bug
