### ISSUE TITLE
Text wrap not working

### ISSUE THREAD

**Issue by j-stodd** [processing/p5.js#5478] opened 2021-11-24 17:58 UTC
I am unsure why text wrap is not working. I specified the parameters as text(str,x,y,w,h) and it did not  create a textbox to wrap the text within. I tried changing everything, the string, the parameters, the rectMode() and other things. I even downloaded the p5js files again and injected them into my project again. Didnt do anything.

The weirdest thing about this is it was working before a few weeks ago im pretty sure. I was using the text wrap for something else, and it looks like the text wrap for that thing is broken now.

I am using Brave Browser. And actually it looks like its working if i use firefox. So it might be something wrong with the brave browser. Brave is just a fork of chromium though so i dont understand why it would just be randomly broken.

**Comment by limzykenneth** [comment] 2021-11-24 23:37
Hi @j-stodd, can you provide a basic code snippet that we can use to replicate your problem? Thanks.

**Comment by j-stodd** [comment] 2021-11-25 19:28
> Hi @j-stodd, can you provide a basic code snippet that we can use to replicate your problem? Thanks.

Yes. here is the sketch: https://editor.p5js.org/Jstodd/sketches/klBXzGjCA

And here is the screenshots of it NOT working in the brave browser, but it working and giving the expected behavior in the firefox browser
![BraveBrowser](https://user-images.githubusercontent.com/65479705/143492908-f9927ba3-e1c0-4553-bc04-06399af1b59d.png)
![FireFox](https://user-images.githubusercontent.com/65479705/143492910-5b30416e-ad2f-49be-96cf-68f9dd0fa141.png)
:

**Comment by dhowe** [comment] 2021-11-26 03:56
I'm not able to recreate this with the current Brave on OSX (see below). Can you include your OS/version?

Brave: Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (x86_64)
OS X: 11.3 (Big Sur)


<img width="880" alt="Screenshot 2021-11-26 at 11 54 05 AM" src="https://user-images.githubusercontent.com/737638/143524432-82526b6a-c239-4a7e-97c3-e281757bf6d3.png">

**Comment by j-stodd** [comment] 2021-11-28 03:15
> https://editor.p5js.org/Jstodd/sketches/klBXzGjCA

I am using v 1.32.106. My operating system is Ubunto 20.04 LTS (Linux). 
![braveversion](https://user-images.githubusercontent.com/65479705/143727450-76db53e1-b887-4fe0-a0e7-22c45c53fc53.png)

**Comment by j-stodd** [comment] 2021-11-28 03:26
> I'm not able to recreate this with the current Brave on OSX (see below). Can you include your OS/version?
> 
> Brave: Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (x86_64) OS X: 11.3 (Big Sur)
> 
> <img alt="Screenshot 2021-11-26 at 11 54 05 AM" width="880" src="https://user-images.githubusercontent.com/737638/143524432-82526b6a-c239-4a7e-97c3-e281757bf6d3.png">

Alright I just Updated Brave to the same version you have, "Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)". the problem persists.
![updatedbrave](https://user-images.githubusercontent.com/65479705/143727674-8a58ab31-0f0a-49c7-8de6-2359ce1bd53e.png)

**Comment by dhowe** [comment] 2021-11-28 05:12
Hmm, very strange. I also cannot recreate this on current Brave for Ubuntu 18.04. Does anyone have a Ubunto 20.04 to test on?
<img width="519" alt="Screenshot 2021-11-28 at 1 10 31 PM" src="https://user-images.githubusercontent.com/737638/143730483-091677cb-66f9-4191-bd40-dac4986a9cde.png">

**Comment by Nitin-Rana** [comment] 2021-11-28 05:28
> Hmm, very strange. I also cannot recreate this on current Brave for Ubuntu 18.04. Does anyone have a Ubunto 20.04 to test on? <img alt="Screenshot 2021-11-28 at 1 10 31 PM" width="519" src="https://user-images.githubusercontent.com/737638/143730483-091677cb-66f9-4191-bd40-dac4986a9cde.png">

I have Ubuntu 20.04 and using Brave(Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (64-bit)) and I also can't recreate it.

**Comment by limzykenneth** [comment] 2021-11-28 15:55
@j-stodd Could it be a browser extension or settings in brave that is altering the rendering somehow?

**Comment by j-stodd** [comment] 2021-11-28 18:44
> https://editor.p5js.org/Jstodd/sketches/klBXzGjCA

Yes! If i turn off brave shields, it works properly... But this is still a problem. Why is brave shields preventing p5js from formatting text properly? that is very strange. And creates a bad ux for anyone using my app. Is p5js doing something brave thinks is creepy? Its saying it blocked a tracker. And no i didn't change any settings i dont think, if i did then they were minimal and i dont understand why theyd affect this. Currently its blocking third party cookies and sending a do not track request to sites.
![braveblockingp5js1](https://user-images.githubusercontent.com/65479705/143781500-b6fff4b1-88cf-4080-ad00-dec4f6ca7062.png)
![braveblockingp52](https://user-images.githubusercontent.com/65479705/143781501-fe89cd95-5c97-44c2-b63b-d71a07e274ce.png)

**Comment by limzykenneth** [comment] 2021-11-28 19:26
Blocking google analytics is pretty common and shouldn't break things like this (I use privacy badger to block google analytics as well). Just to confirm this is the problem would it be possible for you to run the sketch from a local server (ie. not from the p5.js editor) and see if the problem is still there?

**Comment by j-stodd** [comment] 2021-11-28 19:59
> Blocking google analytics is pretty common and shouldn't break things like this (I use privacy badger to block google analytics as well). Just to confirm this is the problem would it be possible for you to run the sketch from a local server (ie. not from the p5.js editor) and see if the problem is still there?

Well if i understand what you mean, then i already have. i originally found the bug on my app which has a nodejs server involved. I was still using brave to view the frontend though. The problem persists using my own local server. So then i guess youre right and its probably not google analytics? 

I just now tested it again, yes its still broken in my app, and it does in fact "fix" it if i disable brave shields. But the only thing listed under brave shields is upgrading the http to https.  Another thing that i bet is unrelated. Which is confusing as to why brave shields is affecting the text wrap on p5js because brave shields isnt saying what exactly its blocking with the shields

**Comment by dhowe** [comment] 2021-11-28 20:25
> edit: I clicked under trackers and it said it blocked the following link: https://www.google-analytics.com/analytics.js

unrelated to the specific problem here, but why are we using google analytics in the p5.js editor?

**Comment by limzykenneth** [comment] 2021-11-28 20:56
@j-stodd In that case the problem is probably a bit more unusual than expected and unless we can figure out what brave shield is trying to do I expect it would be hard to fix on our side, a quick glance at the text rendering code I don't see anything obvious that should be affecting this. 

You may want to reach out to Brave (or search their forums) to see if something similar has happened before. I may try to replicate and debug this a bit more when I have the time, but not sure when that will be.

@dhowe I think p5js.org is using it as well, it is a good question to raise I think. Maybe open an issue on the web editor and the website repo?

**Comment by j-stodd** [comment] 2021-11-29 00:31
> @j-stodd In that case the problem is probably a bit more unusual than expected and unless we can figure out what brave shield is trying to do I expect it would be hard to fix on our side, a quick glance at the text rendering code I don't see anything obvious that should be affecting this.
> 
> You may want to reach out to Brave (or search their forums) to see if something similar has happened before. I may try to replicate and debug this a bit more when I have the time, but not sure when that will be.
> 
> @dhowe I think p5js.org is using it as well, it is a good question to raise I think. Maybe open an issue on the web editor and the website repo?

I just turned off strict block fingerprinting and switched it to standard block fingerprinting, and that fixed the text wrap without turning brave shields off. Maybe thats why others couldnt replicate the problem. Try turning that on and maybe youll see the same thing as me.

Even though that part is figured out, I still cant fathom why this would break a text wrap

**Comment by dhowe** [comment] 2021-11-30 01:40
> Even though that part is figured out, I still cant fathom why this would break a text wrap
have you inspected and compared the CSS between the two versions?

**Comment by j-stodd** [comment] 2021-11-30 17:44
I dont think i see a difference
![1](https://user-images.githubusercontent.com/65479705/144099886-0bb1ae69-1cfc-4253-a0fc-628c9a625636.png)
![2](https://user-images.githubusercontent.com/65479705/144099889-1ba9af7b-e9be-400a-b8bf-4a0555e7d817.png)

**Comment by limzykenneth** [comment] 2021-12-13 22:20
I manage to do a bit of testing and found where the problem is. Brave with strict fingerprinting blocking is preventing the usage of `measureText()` [here](https://github.com/processing/p5.js/blob/main/src/core/p5.Renderer2D.js#L1189) (it always returns 0 instead of the measured render width of the text) which without that information there's no way we can do text warp. As seen in the linked code, using a custom font may work but I have not tested it yet.

Ultimately, as expected, there is nothing we can do on our side and I don't suppose brave will enable `measureText()`on their end for strict fingerprint blocking, so your choice is to use standard fingerprint blocking or try using custom loaded font.

I'm closing this for now as this is not fixable on our end but we can continue discussions here if needed.

**Closed by limzykenneth** 2021-12-13 22:20 UTC
