### ISSUE TITLE
Pushing video objects to a 2D array

### ISSUE THREAD

**Issue by adellelin** [processing/p5.js#1165] opened 2015-12-06 23:38 UTC
Hi,

I am trying to create a 2D array of video objects. This is part of a larger system where I am combining sprites with video objects and have got a prototype working for a regular array. However now I am trying to push video objects to a 2D array and have isolated that area of code. I think the issue is in this line of code but haven't been able to work it out:
tvObjArray.push(new NewTvObj(createVideo(videoFiles[i][j]), false, 0, 0));

Any ideas appreciated!

full code:

    var tvCtrlArray = [[],[]];
    var videoFiles = [
      ["videos/cityDream.mp4", "videos/cityDream.mp4"],
      ["videos/cityDream.mp4", "videos/cityDream.mp4"]
    ];
    
    function setup() {
      createCanvas(1000, 576);
      // create a new tv object for each screen that needs to appear
      for (var i = 0; i < videoFiles.length; i++) {
        for (var j = 0; j < videoFiles[i].length; j++) {
          tvObjArray.push(
            new NewTvObj(createVideo(videoFiles[i][j]), false, 0, 0));
          tvObjArray[i][j].tv.loop();
          tvObjArray[i][j].tv.hide();
          tvObjArray[i][j].tv.pause();
        }
      }
    }
    
    function NewTvObj(tvObj, playingBool, xposVal, yposVal) {
      this.tv = tvObj;
      this.playing = playingBool;
      this.xpos = xposVal;
      this.ypos = yposVal;
    }
    
    function draw() {
      background(255, 100, 100);

      // locate tvs on building
      for (var i = 0; i < videoFiles.length; i++) {
        for (var j = 0; j < videoFiles[i].length; j++) {
      image(tvObjArray[i][j].tv, tvObjArray[i][j].xpos + i * 320, 
        tvObjArray[i][j].ypos + j * 200);
    }

    drawSprites();
      }
    }

**Comment by blindfish3** [comment] 2015-12-07 14:47
The only issue is with your code.  Keep your questions on the [forum](https://forum.processing.org/two/discussion/13821/create-a-2d-array-of-video-objects-uncaught-typeerror#latest) where they belong...

**Comment by lmccart** [comment] 2015-12-07 16:03
@blindfish3 p5.js is a community that takes very seriously its intent to be welcoming and supportive to new people (and to everyone). please be considerate with the tone of your posts. it's great to teach someone who may be less familiar with the protocols/workflows, but please make sure you are encouraging in doing so. thanks! :)

hi @adellelin, it looks like maybe when you initialize the array it's called `tvCtrlArray`, but when you push objects in, you are adding to `tvObjArray`, and I don't see this one initialized anywhere. then in this line
`tvObjArray.push(...)`, since it is a 2D array, you will want to actually assign it's position, rather than using push. push will just push things onto the end like it's a 1D array. so something like `tvObjArray[i][j] = new NewTvObj(createVideo(videoFiles[i][j]), false, 0, 0);`.

hope that helps! in general, yes, it's best to post programming questions to the forum and use this github issues list for bug reports. but I know sometimes it's hard to tell which is happening, so no worries!

**Comment by blindfish3** [comment] 2015-12-07 17:37
@adellelin: apologies if I caused offence

@lmccart: point taken: written in a hurry and with not enough consideration :/
However, I wouldn't have been so abrupt if I hadn't already posted some constructive criticism on the forum itself: my link above goes back to adellelin's cross post there, where I had already pointed out the two obvious issues with the code; and was intended to avoid anyone here having to respond...

**Comment by lmccart** [comment] 2015-12-09 19:52
hey @blindfish3 thanks for your apology and for answering the question on the forum!

**Closed by lmccart** 2015-12-09 19:52 UTC
