### ISSUE TITLE
Frame Rate significantly higher than target on high refresh rate displays (>200Hz)

### ISSUE THREAD

**Issue by silverslither** [processing/p5.js#5684] opened 2022-05-29 23:52 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

1.4.1

### Web browser and version

Firefox 100.0.2

### Operating System

Windows 11 build 22000

### Steps to reproduce this

To reproduce, run the following code on a display with a refresh rate higher than 200Hz:
```
let s = performance.now(),
    t = 0;

function setup() {
    frameRate(60);
}

function draw() {
    t++;
    console.log(1000*t/(performance.now() - s));
}
```
You should see that the numbers logged are significantly higher than 60. I have a 240Hz display and I am getting ~80fps.

The reason behind this is because `this._draw()` (/src/core/main.js) checks for the current time to be within a 5ms window of the intended time, and then updated the time for the next intended frame using the time of the current frame!
The simple solution is to simply change `this._lastFrameTime = now;` to `_this._lastFrameTime = _this._lastFrameTime + target_time_between_frames;` as well as some other changes to account for this difference, however I believe that at some point a refactor to use async/await should be implemented as to avoid hacky workarounds.

**Comment by JoeCastor** [comment] 2022-10-20 02:49
Hi, I will be working on this issue!

**Comment by davepagurek** [comment] 2022-10-20 12:09
Thanks @JoeCastor, I'm assigning this to you!

One small heads up: The change described in the issue will fix the frame rate issue, but the `deltaTime` property also uses `_lastFrameTime`, so we might need to introduce a new property rather than changing `_lastFrameTime` in order to not change how `deltaTime` behaves.

**Comment by davepagurek** [comment] 2022-10-20 14:39
Thanks @silverslither, good point, we should test for that too! @JoeCastor let me know if you need any pointers on how to set up unit tests for behaviours like that.

**Comment by JoeCastor** [comment] 2022-10-22 04:00
So I had a couple of attempts at this and I'm not sure which one would be preferred.
The first time, I simply changed
`this._lastFrameTime = now;` to 
`this._lastFrameTime = max.Math(_this._lastFrameTime + target_time_between_frames, now);`
I did some manual testing with this, and it keeps the frame-rate at 60 when using  above 200Hz, as expected since `_this._lastFrameTime + target_time_between_frames` will be typically greater than `now`, so it acts as described in @silverslither's 'simple solution'. It also avoids the problem with tabbing out of the page, since this will result in `now` being far greater than `_this._lastFrameTime + target_time_between_frames`, so it will act the same as before the fix. I tested the tabbing with a simple moving ellipse animation: with the original 'simple solution', tabbing caused the ellipse to move quickly to a far-away spot after tabbing back in, whereas taking the maximum caused the ellipse to remain in the same spot as where it was when tabbing out, then moving as usual when tabbing back in. 

This didn't resolve concerns over potential effects on `deltaTime`, so I had a go at creating a new property which I called `_deltaFrame`. I initialised this the same way as `_lastFrameTime`, by calling `this._deltaFrame = window.performance.now();` before `this._draw()`. 
Then, after the line with the fix described previously, I had `this._deltaFrame = now;`.
And finally, instead of having `this.deltaTime = now - this._lastFrameTime;`, I have `this.deltaTime = now - this._deltaFrame;`.
Essentially, `_deltaFrame` is just what `_lastFrameTime` was originally, thus `deltaTime` is also just what it was originally since it is now defined by `_deltaFrame`. 
These changes caused it to behave the same way (in my limited, manual testing) as in my previous attempt.

I think the second option is better since it seems to me that it resolves both the concerns listed (tabbing and `deltaTime`).
There could be some problems though, and I would love some pointers on how to set up unit tests @davepagurek :)

**Comment by davepagurek** [comment] 2022-10-22 17:04
> I tested the tabbing with a simple moving ellipse animation

What do you animate the ellipse based on? I think the expected behaviour when you tab back would change based on what you use:
- Position derived from `frameCount`: I think the ellipse should stay in the same place, since no frames have been drawn while in the other tab
- Position derived from `millis()`: I think the ellipse should jump, as time has passed and position is based on time
- Position incrementally updated based on `deltaTime`: I think this should work the same as `millis()`

Let me know if those make sense and if there are other cases we should consider!



> I would love some pointers on how to set up unit tests @davepagurek :)

I think maybe the best way to test this is to replace `window.performance.now` and `window.requestAnimationFrame` so that we can manually trigger the next frame quickly in the test, and so that we can pretend that it took however long we want.

For replacing the time, you can use `cosnt clock = sinon.useFakeTimers()` to mock `window.performance.now` and `clock.tick(someTimeHere)` to set the time that will be read. Combining this with a stub for `requestAnimationFrame` could look something like this:

```js
let clock;
let prevRequestAnimationFrame;
let nextFrameCallback = () => {};
let myp5;
beforeEach(() => {
  clock = sinon.useFakeTimers();

  // Save the real requestAnimationFrame so we can restore it later
  prevRequestAnimationFrame = window.requestAnimationFrame;
  // Use a fake requestAnimationFrame that just stores a ref to the callback
  // so that we can call it manually
  window.requestAnimationFrame = (cb) => {
    nextFrameCallback = cb;
  };

  myp5 = new p5(function(p) {
    p.setup = function() {
      p.createCanvas(10, 10);
    };
  });
});
afterEach(() => {
  clock.restore();
  window.requestAnimationFrame = prevRequestAnimationFrame;
  nextFrameCallback = () => {};
  myp5.remove();
});
test('timing behaviour', () => {
  sinon.spy(myp5, 'draw');
  clock.tick(1000 / 200); // Simulate a 200Hz refresh rate
  nextFrameCallback(); // trigger the next requestAnimationFrame
  // Do some assertions here on myp5.draw.mock.calls to see if it drew or not
  // Maybe also do assertions on the value of myp5.deltaTime
});
```

**Comment by davepagurek** [comment] 2022-10-25 12:00
@JoeCastor I'm happy to take a look if you want! Although typically what I'll do if I run into errors in my tests is to run `grunt yui:dev` to launch a local server from p5, then go to http://localhost:9001/test/test.html?grep=something (replacing `something` with a keyword in your test's name to focus on just that test) and then you can use the debugger in your browser to see the full error, set breakpoints, and everything else you might want to do to debug 🙂

**Closed** 2023-01-26 15:10 UTC
Labels: Bug, Area:Core
