### ISSUE TITLE
mouse button blocking mouseMoved() callback

### ISSUE THREAD

**Issue by facebamm** [processing/p5.js#4013] opened 2019-09-14 05:33 UTC
Hi there! 

My bug is there: When I am trying to log the mouseMove event it will be work fine but when I press a mouse button then the mouseMove - callback doesn't call anymore.

#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version:  p5.js v0.9.0 July 01, 2019 
- Web browser and version: 77.0.3865.75 (Offizieller Build) (64-Bit) (cohort: 77_75_Win)
- Operating System: Windows Version 1903 (Build 18362.356)
- Steps to reproduce this:
```js
let fr = 30;
let offsetX;
let offsetY;

function setup() {
    frameRate(fr);
    createCanvas(windowWidth, windowHeight, WEBGL);
    pixelDensity(1);
    ...
    offsetX = 0;
    offsetY = 0;
    ...
} 

function mouseMoved(event) {
    console.log(mouseIsPressed + " test");
    if (mouseIsPressed) {
        if (mouseButton === LEFT) {
            offsetX += event.movementX;
            offsetY += event.movementY;
        } 
    }
}
```

**Comment by stalgiag** [comment] 2019-09-14 08:45
Hi @facebamm Thanks for the well-written issue. This is intended behavior. [In the documentation](https://p5js.org/reference/#/p5/mouseMoved) for `mouseMoved()`, it says 'The mouseMoved() function is called every time the mouse moves and a mouse button is not pressed.'

In the source code [on this line](https://github.com/processing/p5.js/blob/master/src/events/mouse.js#L608) you can see that if the mouse button is down while moving `mouseDragged()` is called instead of `mouseMoved()`. 

So your code would look more like:
```
function mouseDragged(event) {
  if (mouseButton === LEFT) {
      offsetX += event.movementX;
      offsetY += event.movementY;
  } 
}
```

Hope this helps!

**Comment by stalgiag** [comment] 2019-09-14 08:49
I am going to close this issue for organizational purposes. If you feel that the design of mouse events in the API should be different feel free to post in here and I'll reopen for discussion.

**Closed by stalgiag** 2019-09-14 08:49 UTC
Labels: area:events
