### ISSUE TITLE
Using select() and option() with a <select> HTMLelement

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#1864] opened 2017-03-20 14:48 UTC
This is going to be confusing due to the word "select" meaning two different things, let me see if I can explain!

The following works:

```javascript
var dropdown = createSelect();
dropdown.option('apple');
dropdown.option('mango');
```

However, if I have an existing HTML element like:

```html
<select id="fruitlist></select>
```

The following does not work:

```javascript
var dropdown = select('#fruitlist');
dropdown.option('apple');
dropdown.option('mango');
```

It seems that the `p5.Element` created is not properly noted as a `<select>` element and therefore does not have the `option()` method attached?

I am happy to investigate this further, feedback or thoughts welcome.

**Comment by JimishF** [comment] 2017-03-22 07:26
I'm working on this issue. It can be resolved by adding methods of select prototype at the time of returning `wrapElemet()`

**Comment by tigoe** [comment] 2017-04-02 22:35
An added detail: 

This also doesn't work when you use p5.js in Cordova/PhoneGap. It used to, prior to 0.5.4, but in that version there was a problem  that caused touch events to be generated twice, e.g. every button press would generate two touchEnded() events. The  touchEnded fix  may have broken the select methods?

I've only tested on Android, but so far, no love.

Here's a test for this in PhoneGap:

1. Follow [Jjiashan's instructions](https://github.com/OhJia/p5Mobile/wiki/Phonegap) to make a p5 PhoneGap project. 
2. Add p5.dom.js to the list of script includes in the index.html as well. 
3. Put the following in the sketch.js:

````
var responseDiv, opts;
function setup() {
  console.log('starting');
  opts = createSelect();
  opts.position(10, 10);
  opts.size(150, 30)
  opts.option('Pick a device', '');
  opts.option('fee', '');
  opts.option('fie', '');
  opts.option('fo', '');
  opts.changed('fum');

  responseDiv = createDiv('tap the scan button to begin');
  responseDiv.position(10, 100);
}

function draw() {
}

function fum() {
  responseDiv.html(opts.value());
}
````

4. Run the sketch on the phone, then try to touch the select. You'll get no action.

**Comment by JimishF** [comment] 2017-04-03 13:54
`changed()` is from p5.Element.prototype, which is simply attaching change listener to particular element. I guess `opts.changed(fxn);` is accepting a function rather than a string. 
Try `opts.changed(function(e){ console.log( e.target ) })`

**Comment by tigoe** [comment] 2017-04-03 14:10
That's a typo on my part. Remove the quotes around fum and you've got the test I actually used, which is roughly equivalent. The div remains unresponsive.

**Comment by JimishF** [comment] 2017-04-03 14:12
yeah my mistake. i didn't saw further that you've declared `function fum()` later after i noticed that you've given string as arguments.

**Comment by tigoe** [comment] 2017-04-03 14:18
No really, it was my mistake (though thanks for being kind). 

I've been digging to find the version of p5 that I ran on phonegap where the option menus did work, but haven't successfully reproduced it. I thought it was 0.5.3, but it seems to be failing with that too.   strange.  Will keep looking so we can pinpoint where the change happened. Though I suspect the final fix to #1868 will probably solve it.

**Comment by JimishF** [comment] 2017-04-03 14:18
Here is the your problem.
`opts.option('fee', '');` means create an option with inner-text "fee"
 having value empty.
Passing only one argument `opts.option('fee');` will assign inner-text as well as value.

**Comment by tigoe** [comment] 2017-04-03 14:31
That doesn't solve it, unfortunately. Still unresponsive in PhoneGap, but works fine in the browser. You can see the difference if you use the Chrome developer's console device emulator and try any of the phones listed.  

Doesn't solve the full issue, either, because the createSelect() and options() is supposed to be able to set both an option and a value. In the actual code I'm using it for, for example, I'm filling in the empty value with a string that's a long UUID the user doesn't need to see, which is a reasonably common use case.  I also tried passing in non-blank values, same result.

Weirdly, I am able to add options to the list, unlike Shiffman's original issue....

**Comment by JimishF** [comment] 2017-04-03 14:35
This is totally different from Shiffman's issue. You should read it again. it says he is not able to apply selectbox methods while selecting (using query selector) an existing dropdown from dom.

**Comment by tigoe** [comment] 2017-04-03 14:42
Right. I will shift over to #1868, which is perhaps more related.

**Comment by lmccart** [comment] 2017-05-10 12:13
fixed with https://github.com/processing/p5.js/pull/1868

**Closed by lmccart** 2017-05-10 12:13 UTC
Labels: area:dom
