### ISSUE TITLE
WEBGL: texture not being set when using shapes

### ISSUE THREAD

**Issue by pflannery** [processing/p5.js#1561] opened 2016-08-20 08:51 UTC
p5js version: 0.5.3

Example:  https://jsfiddle.net/7nxcL1tf/19/

But if box() is called prior to endShape() then the texture is applied to the shape correctly.

**Comment by pflannery** [comment] 2016-08-20 09:02
I think this is because there are no uv data being sent to the texture shader when drawing shape.

**Comment by indefinit** [comment] 2016-08-23 18:00
Good catch.  Working on a patch for this now.

**Comment by cqx931** [comment] 2016-11-02 14:28
Hi, is there any progress on this issue?
If I replace the shape in the above example with something like this:
```
 beginShape()
  vertex(0,250,0)
  vertex(250,250,0)
  vertex(0,0,0)
  endShape(CLOSE)
```
I can see the texture applied to the border but there is no texture in the shape.
Is this problem also related to this ticket?
https://github.com/processing/p5.js/issues/1582

**Comment by dhowe** [comment] 2016-11-03 03:53
@indefinit would be great to get a fix for this one...

**Comment by calpa** [comment] 2017-03-25 14:14
Hello everyone, I also find this problem when I am using `beginShape()` and `vertex()` functions to create a plate filled with image.

Although I input box(100,1), it can generate a flat plate...

Example: http://codepen.io/calpa/pen/ZejWem

**Comment by pflannery** [comment] 2017-05-10 15:43
@lmccart 

:( this still doesn't work. I've updated the fiddler to use p5.js v0.5.9 https://jsfiddle.net/7nxcL1tf/29/

I've also made sure that I call `endShape(CLOSE)` in the fiddler example but no joy.

**Comment by pflannery** [comment] 2017-05-10 15:44
maybe something to do with `TRIANGLE_STRIP`?

**Comment by cqx931** [comment] 2017-06-22 07:34
same here,  it still doesn't work when I try to fill a shape created by `beginShape()` and `vertex() `

**Comment by mlarghydracept** [comment] 2017-06-22 20:16
So on my end it is texturing the shape but it is being inverted and there are ton of errors being fed to the console with subsequent code after endShape not firing. With this code ::

```
  push();
  texture(img);
  translate(-150, -100, 0);
  rotateZ(frameCount * 0.01);
  rotateX(frameCount * 0.01);
  rotateY(frameCount * 0.01);
  box(70);
  pop();

  texture(img);
  push();
  beginShape(TRIANGLE_STRIP);
  vertex(100, 100, 0);
  vertex(-100, 100, 0);
  vertex(0, 0, 0);
  endShape(CLOSE);
  pop();
```
I get this ::

![screen shot 2017-06-22 at 1 15 16 pm](https://user-images.githubusercontent.com/10382506/27453917-ddda33b4-574c-11e7-888c-d8806511c53a.png)

@kjhollen and I are working on the WebGL this summer and will try to address this. Thanks for pointing out the problem!

**Comment by kjhollen** [comment] 2017-09-20 07:42
Is this a duplicate of #1424? Note that in the examples given, you'd need to add u, v coordinates to each vertex call to make this work; none of these examples will work as-is. 

I'm going to mark this as fixed because we've now added support for u,v texturing with vertex()! If I'm misunderstanding something here and this should be reopened, let me know.

**Closed by kjhollen** 2017-09-20 07:42 UTC
Labels: area:webgl, bug, GSOC

**Comment by rdsilver** [comment] 2017-11-20 18:45
@kjhollen , @mlarghydracept 
Is there a working example of this? I'd want to add this to the main p5.js site for reference purposes.
