### ISSUE TITLE
User defined shaders are never used when a texture is specified because isTextureShader always returns false.

### ISSUE THREAD

**Issue by sflanker** [processing/p5.js#5507] opened 2021-12-19 00:26 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.4.0
- Web browser and version: Chromium (by would repo in any)
- Operating System: Mac OS X
- Steps to reproduce this:
1. Create a custom shader where the vertex shader handles the `vec2 aTexCoord` attribute and the fragment shader expects a `sampler2D uSampler` uniform.
2. Apply a texture, then specify the custom shader, then draw some 3d geometry.

**Expected:** The custom shader should be applied to the geometry
**Actual:** The default shader is used

#### Workaround:

After creating the custom shader, explicitly set `yourShader.samplerIndex = 1`.

This works because `isTextureShader` checks `this.sampleIndex > 0` but `p5.Shader._loadUniforms` never actually initializes that as an instance property (it is only a local variable).

#### Defect:

https://github.com/processing/p5.js/blob/main/src/webgl/p5.Shader.js#L159

**Comment by sflanker** [comment] 2021-12-19 00:27
Example with workaround in place: https://openprocessing.org/sketch/1406878

Credit for finding the bug: https://discourse.processing.org/t/paint-an-image-with-transparency-on-a-quad-via-a-fragment-shader/34189

**Comment by aferriss** [comment] 2021-12-20 02:08
I believe that the `texture()` function is not intended to be used with custom shaders, and is more meant as a quick way to texture geometry. When using the `shader()` function, you are expected to pass your own uniforms to the shader.

If you want to send your texture to the shader directly, you can add this line after the call to the `shader(shdr);` function. 

```
shader(shdr);
shdr.setUniform('uSampler', img);
```

I'm going to close this issue since I think this is intended behavior instead of a bug, but if you feel otherwise, feel free to reopen!

**Comment by sflanker** [comment] 2021-12-20 02:45
@aferriss I disagree with the current behavior being considered by design for the following reasons:

1. If you do not have a texture set, UV coordinate normalization will not happen and the `vertex()` function will spam the logs with `'You must first call texture() before using vertex() with image based u and v coordinates'` even if you pre-normalize your UVs.
2. While I haven't tested it the way you suggest, the `texture()` function handles animating gifs, which I believe would not be possible otherwise unless the image being used as a texture was also drawn off screen or something forcing animation (since `Image._animateGif` is a private/internal function).
3. If it were by design for this to function this way, why would the `_isTextureShader()` function even exist, and why would it be called in `_getRetainedFillShader()` on what appears to always be a user defined shader (`this.userFillShader`).
4. It seems to be that such a design would only makes things less intuitive for the end user (although the lack of prominent documentation for the set of standard attributes and uniforms is a problem, it is a separate problem).

Unless you have additional arguments for why the current behavior is by design I would appreciate it if you would reopen this bug (I don't think I have the ability to do so).

Additionally, I think this should be a very straightforward fix and I intend to submit a PR, I just have a few other things on my plate right now.

**Comment by aferriss** [comment] 2021-12-20 06:20
Happy to reopen! I'll take another look at this later when I have some more time. Thanks for the detailed writeup!

**Comment by sflanker** [comment] 2021-12-20 09:09
Great, no rush, thank you for looking into it. As I said I'd like to contribute the fix myself as soon as I have the time.

**Comment by aferriss** [comment] 2021-12-22 23:27
First off, I'll say that I think this is probably a change worth making, as it's a really small update, and doesn't seem to impact anything else. However, I'm still not sure that this was the original intention for the texture function, but I do think it is an interesting workaround to send a texture to a shader.

To your points:
1. We should revisit why this warning is here, and if we want to keep it, we should not trigger it when a texture has been set using setUniform(). I also noticed that the warning went away when I called `textureMode(NORMAL)`. I'll open an issue for this. 

2. Another good spot! This is definitely a bug. The `setUniform()` function should receive updated textures for gifs, but it seems to be broken right now.  I'll open another issue for this as well

3. Not entirely sure about this one. The webGL has been under a few transformations, so it's possible some things are left over from previous iterations. My guess is that isTextureShader was being used to denote when the texture function had been called, but we might not have been expecting it to be used with a custom shader. This just happens to be a side effect of giving your uniforms the same name as what the renderer is using under the hood. One limitation of using the `texture()` function in this way, is that you can only set a single texture from the `texture()` function call, and subsequent textures would need to be set using the `shader.setUniform()` function.

4. Lack of documentation is definitely an issue we'd like to solve. There's been [some work on this](https://github.com/processing/p5.js-website/issues/1017), but it may have paused. Would love a contribution here. If I recall correctly, one issue we ran into was where to put the documentation on the site. Since the documentation is generated from  inline comments, there wasn't a natural place for it to go. We talked about making a separate page, but I'm not sure what came of that.

Anyhow, hope that helps give some more context! It seems we have a couple other new issues to iron out now as well :)

**Closed** 2021-12-30 19:46 UTC
Labels: bug, area:webgl
