### ISSUE TITLE
getUserMedia not supported in this browser error in Firefox when p5.sound is not included

### ISSUE THREAD

**Issue by Utopiah** [processing/p5.js#3210] opened 2018-09-13 17:30 UTC
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Image
- [x] IO
- [x] Utilities

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: p5.js v0.5.16 October 11, 2017
- Web browser and version: Firefox 62.0
- Operating System: Windows_NT 10.0
- Steps to reproduce this:
```
<html>
<script src="https://ml5js.org/scripts/p5.min.js"></script>
<script src="https://ml5js.org/scripts/p5.dom.min.js"></script>
<!-- <script src="https://ml5js.org/scripts/p5.sound.min.js"></script> -->
<!-- comment out p5.sound to get in Firefox
      "uncaught exception: getUserMedia not supported in this browser" -->
<div id="canvasContainer"></div>
<script>
function nosetup() {
  let video;
  createCanvas(320, 240).parent('canvasContainer');
  video = createCapture(VIDEO);
}
</script>
</html>
```

Found via https://github.com/ml5js/ml5-examples/pull/65

**Comment by lmccart** [comment] 2018-11-09 07:12
there's no setup or draw defined in your example code, so p5 is likely not getting initialized at all, causing createCapture() to fail perhaps. for more help, you can post on the forum: https://discourse.processing.org

**Comment by Utopiah** [comment] 2018-11-09 08:17
It's unrelated to setup/draw, cf official example https://p5js.org/examples/dom-video-capture.html which does require p5.js-sound for something seemingly unrelated. Consequently I believe it's a bug in term of getUserMedia support being delegated (probably just better error handling) in `p5.js-sound`.

As mentioned in the linked ml5js PR adding p5.js-sound does make it work in Firefox so personally I'm OK, not need for extra help via forum.

**Comment by lmccart** [comment] 2018-11-09 15:10
oh I see thank you.  here's an example illustrating the issue.
https://editor.p5js.org/lmccart/sketches/H1EZXQQ67

**Comment by pietschj** [comment] 2018-11-21 15:31
this happens to me when following shiffmans tutorial on webcam classification with ml5.js on Win10x64 and Firefox v. 63.0.1

**Comment by limzykenneth** [comment] 2018-11-26 15:41
I'm not encountering this issue in Firefox 63.0.3 on macOS Mojave

**Comment by Utopiah** [comment] 2018-11-28 06:08
Still have the same problem on 63.0.3 (64-bit) on WIndows 10.

**Comment by stalgiag** [comment] 2019-06-26 01:39
I am unable to recreate the bug with Firefox 67.0.4 on Windows 10 with the current master branch or with the editor example link posted above which uses 0.7.2.

Perhaps a problem with Firefox that has been fixed?

**Comment by stalgiag** [comment] 2019-07-01 22:24
Closing now for organization purposes. If someone can reproduce in a recent version of Firefox, just @ me here and I will reopen.

**Closed by stalgiag** 2019-07-01 22:24 UTC
Labels: area:io

**Comment by parthghughri** [comment] 2020-08-02 08:28
Again getting same issue, Firefox version 79.0 (64-bit)

![image](https://user-images.githubusercontent.com/16538468/89118983-163f0d00-d4c8-11ea-9977-b44a5f4d2273.png)

**Comment by limzykenneth** [comment] 2020-08-02 10:20
@parthghughri The p5.js version that is used in the linked sketch is very old (0.6.0). Update it to the latest version (1.1.9) in `index.html` and it should work as expected. You will need to remove the line requiring p5.dom.js as well since it has since been merged with the main library.

**Comment by parthghughri** [comment] 2020-08-02 13:13
Thank You!

> @parthghughri The p5.js version that is used in the linked sketch is very old (0.6.0). Update it to the latest version (1.1.9) in `index.html` and it should work as expected. You will need to remove the line requiring p5.dom.js as well since it has since been merged with the main library.

Thanks, I wasn't aware of that older version.
