### ISSUE TITLE
Firefox global function "Animation"Issue

### ISSUE THREAD

**Issue by apardo04** [processing/p5.js#2004] opened 2017-06-14 16:07 UTC
Console Log returns this on Firefox: p5 had problems creating the global function "Animation", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.

Has anyone had this issue or have a fix? None of my variables are named Animation

**Comment by bomoko** [comment] 2017-06-15 10:18
Hi @apardo04 
Would you be able to share a sketch/some code that demonstrates this issue when it's run in Firefox?

**Comment by apardo04** [comment] 2017-06-15 14:00
Hey @bomoko 

I have it hosted on Bitbucket right now for privacy reasons until I launch it on my site, then I'll put it here on Github(I am very close to getting the first level live, just need to fix this cross browser issue). If you give me your bitbucket username/or email I will share the repo with you.

**Comment by lmccart** [comment] 2017-06-15 15:11
we're really just looking for a few few line snippet of code that illustrates the issue so we may reproduce and debug. no need to share the whole project, this actually makes it more difficult for us to isolate the problem. thanks!

**Comment by apardo04** [comment] 2017-06-15 15:36
OK so I found the issue about why the game wasnt running on firefox or IE. It had to do with "p5.sound.js", once i commented out these lines it worked:
```
function preload() {
fart = loadSound("assets/audio/fart.wav");
}
function setup() {
fart.setVolume(0.1);
}
function draw() {
fart.play();
}
```

I am still getting the "Animation" variable console log on firefox. I made a quick example of my source code for you guys. I should also mention that I am using p5.play.js and CSS animation(I should of mentioned this earlier, I posted this issue on p5.play.js github repo as well)
```
let robin, robin_cycle, robin_sheet, robin_animation;
let robinWidth = 150;
let robinHeight = 200;

function preload() {
    robin_cycle = [
        {"name": "bird_flight01", "frame": {"x": robinWidth * 4, "y": 0, "width": robinWidth, "height": robinHeight}},
        {"name": "bird_flight01", "frame": {"x": robinWidth * 3, "y": 0, "width": robinWidth, "height": robinHeight}},
        {"name": "bird_flight01", "frame": {"x": robinWidth * 2, "y": 0, "width": robinWidth, "height": robinHeight}},
        {"name": "bird_flight01", "frame": {"x": robinWidth * 1, "y": 0, "width": robinWidth, "height": robinHeight}},
        {"name": "bird_flight01", "frame": {"x": 0, "y": 0, "width": robinWidth, "height": robinHeight}}

    ];
    robin_sheet = loadSpriteSheet('assets/img/robin_sheet.png', robin_cycle);
    robin_animation = loadAnimation(robin_sheet);
}

function setup() {
    let myCanvas = createCanvas(window.innerWidth, window.innerHeight);
    myCanvas.parent("canvas");
    // Everything below this comment is on an external JS file on my actual game
    robin_sprite = createSprite();
    robin_sprite.addAnimation("default", robin_animation);
    robin_sprite.height = robinHeight;
    robin_sprite.width = robinWidth;
    robin_sprite.position.x = robinWidth/2;
    robin_sprite.position.y = robinHeight/2;
}

function draw() {
    clear();
    drawSprites();
}
```
It's a pretty big game, with quite a bit of moving parts.

**Comment by bomoko** [comment] 2017-06-16 04:58
Well, this is interesting, everything actually looks to be working correctly.
There's still an error, but p5's behaviour is exactly as expected.

It seems as though Firefox has a window.Animation() function!
So when p5 tries to bind p5.play.js' Animation function, it (rightly) throws an exception.

This explains _why_ we're seeing this in FF, but since this is p5.play.js specific, perhaps that's the right forum to deal with the issue?

**Comment by bomoko** [comment] 2017-06-16 05:06
Well, this is interesting, everything actually looks to be working correctly (from p5's perspective).
There's still an error, but p5's behaviour is exactly as expected.

It seems as though Firefox has a window.Animation() function!
So _createFriendlyGlobalFunctionBinder (rightly) throws an error notifying the user that there has been a namespace clash.

This explains why we're seeing this in FF, but since this is p5.play.js specific, perhaps that's the right forum to deal with the issue (on the issue @apardo04 opened there)?

**Comment by bomoko** [comment] 2017-06-16 10:29
Quick update - it's definitely the Web Animations API in FF doing this.
If you set **dom.animations-api.element-animate.enabled** in your FF preferences to **false**, then rerun the script, you'll find that the "Animation" object is no longer part of the global scope.

**Comment by lmccart** [comment] 2017-06-16 19:24
@bomoko thanks for looking into this. it sounds like this is an issue with FF and p5.play, and since the issue is already open on the p5.play repo, I think we can close it here.

**Closed by lmccart** 2017-06-16 19:24 UTC
