### ISSUE TITLE
Mouse/touch is being triggered twice again on mobile

### ISSUE THREAD

**Issue by jacorre** [processing/p5.js#2079] opened 2017-07-18 23:13 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.5.11
- Web browser and it's version: Google Chrome v59
- Operating System: Android
- Steps to reproduce this:

- See the following [CodePen example](https://codepen.io/anon/pen/dRaYWj) using an Android mobile device with Google Chrome as the browser.
- Select the Test button.
- Notice that the alert is triggered twice instead of once.

NOTE: This doesn't appear to be a problem on iOS or desktop.

**Comment by lmccart** [comment] 2017-07-19 00:04
Duplicate of #1815

**Closed** 2017-07-20 21:16 UTC
