### ISSUE TITLE
arc renders unexpectedly when start and stop angle are the same

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js#2919] opened 2018-05-18 23:36 UTC
I noticed some weird behavior in the arc function when the start and stop angles are the same. It will render a full circle from 0 up to 90 degrees, beyond that it begins to render a 180degree~ arc that rotates, and then around degree 300 the arc starts to flash on and off.

What is the intended behavior when the values are the same? I was imagining that nothing would be drawn. I'm wondering if this line is causing some of the weirdness https://github.com/processing/p5.js/blob/5f6b4ab7e1c1a680186e52a9a1ac3f63450e8406/src/core/2d_primitives.js#L100-L103 

#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.1
- Web browser and version: Firefox 60
- Operating System: Linux Ubuntu 16.04
- Steps to reproduce this: Set the same value for start and stop in arc(). Here's an example: https://alpha.editor.p5js.org/aferriss/sketches/SkpGgyaCf

**Comment by aferriss** [comment] 2018-05-18 23:59
I'm also a little confused about the purpose of these lines, which I think are also part of the problem. I assume the intent was to ensure that you can't go completely round the arc more than 360, so there will always be some portion of the arc drawn. 
https://github.com/processing/p5.js/blob/5f6b4ab7e1c1a680186e52a9a1ac3f63450e8406/src/core/2d_primitives.js#L96-L98

When I comment out both these and the lines I mentioned above things work like I would imagine. i.e. 
````
arc(x, y, w, h, 180, 180); // nothing is drawn when the start and stop are equal
arc(x, y, w, h, 0, 360); // a full circle is drawn
arc(x, y, w, h, 0, 720); // the arc goes around twice 
````
I can pull those out and make a PR if that makes sense.

**Comment by kjhollen** [comment] 2018-05-19 20:12
thanks @aferriss! @AdilRabbani this is related to your work on arc for web GL, do you want to take a look at this?

**Comment by AdilRabbani** [comment] 2018-05-19 22:55
Yep! Already looking into this!

**Comment by AdilRabbani** [comment] 2018-05-20 11:13
@kjhollen what should the actual behavior be when same angles are provided for the start and stop parameters? I'm guessing the arc should complete a full circle. Starting from a specific angle, completing the round trip along the perimeter of the circle and stop at the same angle?

**Comment by aferriss** [comment] 2018-05-21 17:17
FWIW the way it works in desktop processing when the start and stop are the same, nothing is drawn. When you have an angle that is larger than 0 - TWO_PI, you just end up with a circle no matter how big of a difference between the start and stop.

So:
````
arc(x, y, width, height, 0, 0); // should draw nothing

arc(x, y, width, height, 0, TWO_PI * 10) // should draw a circle
````

**Comment by AdilRabbani** [comment] 2018-05-21 19:00
right! @aferriss the latest commit for arc right now, fixes the flickering issue. It would also deal with the case when the start and stop are the same (should draw nothing), but when given parameters such as 0,TWO_PI*10 for start and stop it would account for a full circle for this one as well, drawing nothing. According to the reference https://p5js.org/reference/#/p5/arc for drawing a full circle it is preferable to use ellipse. Let's just see what @kjhollen has to say?

**Comment by kjhollen** [comment] 2018-05-21 20:34
I think that the implementation @aferriss describes is preferable. If the arc range is greater than 2 * PI, we should default to drawing a circle. While generally it is better for the user to use ellipse if they know they are drawing a circle, this implementation would also allow them to make some nice arc animations (as you've done in your example code).

**Comment by aferriss** [comment] 2018-05-29 17:37
Hey not sure if this is related or not but arc also seems to render really strangely when I use rotate() on it with intervals of 270 (-90, 630, etc). It seems to flash a rect on the screen intermittently. Take a look here

http://alpha.editor.p5js.org/aferriss/sketches/rJ9iyfi17

**Comment by mlarghydracept** [comment] 2018-05-29 18:41
Thanks for catching this @aferriss! Just confirming that this appears in the webgl-gsoc-2018 branch as well.

**Comment by joecridge** [comment] 2018-07-29 15:20
Hi all – sorry, I completely missed this discussion! Hopefully I can add some clarification on the intended behaviour, and how we arrived at that behaviour in the first place.

There’s a lot going on here, so I’ll try to break it down into independent components.

## General start/end behaviour

The interpretation of `start` and `end` in p5.js is slightly different from that in Processing, motivated by the fact the Processing often decides to draw nothing (e.g. if you wanted the arc to cross the x-axis) or decides to swap `start` and `end` if that would be more convenient for the renderer (the net effect is that some sizes/rotations of arc are impossible to draw). The intended behaviour in p5.js is as follows (consider drawing it yourself on paper):

1. Draw the underlying ellipse in pencil, and draw the horizontal/vertical lines through its centre.
2. Put your protractor so that zero is along the horizontal _to the right_.
3. Mark the `start` and `end` points on the ellipse using the protractor.
4. Put your pen down at the `start` point, and follow the underlying ellipse around _clockwise_ until you reach the `stop` point.
5. (Erase the construction lines in pencil.)

Note that adding/subtracting 360° has no effect on where you mark the `start` and `end` points on the ellipse, so there is no notion of ‘going round twice’ etc. (hence the two lines @aferriss queried).

Previous discussion about the above: see [this comment](
https://github.com/processing/p5.js/issues/740#issuecomment-113974932). Here’s the original description of the change:

> - Removes odd behaviour for arcs that cross the zero degrees line: arcs are now always drawn clockwise from `start` to `stop`.
> - Removes dependence on angular convention: arcs will now be drawn correctly regardless of whether you use -PI to PI, 0 to TWO_PI, an unbounded range, or even with a different convention each for `start` and `stop`.

## When start and end refer to the same point

The intended behaviour when `start` and `end` are marked in the same place is as @aferriss expected: _nothing should be drawn_. From the current docs:

> Note that drawing a full circle (ex: 0 to TWO_PI) will appear blank because 0 and TWO_PI are the same position on the unit circle. The best way to handle this is by using the ellipse() function instead to create a closed ellipse, and to use the arc() function only to draw parts of an ellipse.

Why did we decide on that behaviour? Mainly to keep things predictable – take a look at [this discussion](
https://github.com/processing/p5.js/issues/902).

_However_, [this later commit](
https://github.com/processing/p5.js/issues/902) (as @aferriss has identified in the original post) contradicts the above, and is the source of the original issue in this ticket.

## Flickering

As per my comment on #3097, I believe that the flickering is separate and induced by a [different commit](https://github.com/processing/p5.js/pull/3042/files#diff-b224eabb1710349c5e23fcf38de6c7d9R451   ). It might also be worth looking at the discussion on #1779 – we’ve had graphics card-specific issues in the past that cause the appearance of random rectangles which weren’t directly related to the arc implementation.

## Special-casing the full circle

Regarding @aferriss’ suggestion of forcing a full ellipse when `Math.abs(start - end) > TWO_PI`: I _very strongly disagree_ with this. It’s yet another special-case amendment (the sort which has caused existing issues), and a breaking change which rules out a whole host of current use cases (consider e.g. a clock animation where the `start` angle is the minute hand and the `stop` angle is the hour hand; at present I can set it off running with `start += 60 * step` and `stop += step` each frame, and get an animation which loops fovever; under the proposed changes it would break at some random point and get stuck displaying a full circle forever).

## An enthralling read. But what should we actually do?

At this point I would propose the following actions:

1. Revert e13341f (will fix this ticket).
2. Revert ebdda95 (_should_ fix flickering).
3. Remove the changes to `src/core/p5.Rendered2D.js` from #3097.

If, after the above, the flickering (and rotation issue) still persists _and_ it can be replicated on two different browsers/machines, then we know we have a problem with the underlying arc implementation itself, and we should open a new issue for that and discuss how to fix it properly.

**Comment by Spongman** [comment] 2018-07-29 15:44
I believe the actual problem may indeed be
some kind of sensitivity to rounding, but I agree that tracking it down whatever it is would be preferable to layering bandaids.

**Comment by AdilRabbani** [comment] 2018-07-29 16:15
Just some notes from my side :

1) #3042 isn't merged to master, as I closed it because it didn't seem like a proper fix to the "flickering rect issue" (But the PR was meant to fix the issue not to induce it). Note that this issue is different from what this original issue is based on which was already fixed in #2942.

2) My original implementation was to not render anything when `Math.abs(start - end) > TWO_PI` (See my comment above on May 22). I guess this is how the arc should behave?....But then I changed it to render a full circle after approval from @kjhollen

**Comment by Spongman** [comment] 2018-07-29 17:20
ok, something very strange is going on here that i don't understand.

here is a simple repro of the bug using 0.6.1: https://codepen.io/Spongman/pen/WKXewG?editors=0010

![image](https://user-images.githubusercontent.com/1088194/43368751-1f7f3376-9317-11e8-9d8f-719f1c62dab0.png)
(Chrome 67.0.3396.99, Windows 10.0.17134.48, Nvidia GT 520 v391.35)

the sketch includes an implementation of p5.Renderer2D.prototype.arc that outputs the bezier coordinates to the console:
```
moveTo( 50 0 )
bezierCurveTo( 50 27.61423749153968 27.614237491539683 49.99999999999999 3.061616997868383e-15 50 )
bezierCurveTo( -0.2908900547139141 50 -0.5817745711145361 49.997461489283 -0.8726203218641627 49.992384757819565 )
```


now, here's a non-p5js pen that just uses the canvas API directly to make those _exact_ same drawing calls with the numbers above: https://codepen.io/Spongman/pen/vaWBgo?editors=0010

no bug:
![image](https://user-images.githubusercontent.com/1088194/43368849-42cf314a-9318-11e8-8c14-d4c00ce3bab5.png)

so, either i'm missing some other detail that helps to cause this rendering bug, or the numbers being passed to the `bezierCurveTo` function are not the same (due to float rendering/parsing loss) and that difference is what's triggering it.

**Comment by joecridge** [comment] 2018-07-29 17:38
Oops... apparently I was looking at the wrong diff!

@AdilRabbani I can't speak for WebGL, but your changes in #2942 are **not** compatible with the Renderer2D implementation of `arc()`. (Not that you could have known, though... it doesn't seem to be documented anywhere :grimacing:.)

`p5.Renderer2D.prototype.arc` has the following requirements:

- `0 <= start < TWO_PI`
- `0 <= stop < TWO_PI`

Currently, we have `0 <= stop < 2 * TWO_PI` (the [if](https://github.com/processing/p5.js/pull/2942/files#diff-a60317395a4f472a4b9231fcde6b59caR103) and [else if](https://github.com/processing/p5.js/pull/2942/files#diff-a60317395a4f472a4b9231fcde6b59caR110) branches in your `p5.prototype.arc` changes); and `-Infinity < start < Infinity` and `-Infinity < stop < Infinity` in the implicit `else` branch. This will cause some _very_ weird (by which I mean very extreme arc shapes -- not the rectangular distortion @Spongman has just posted) arc drawing under Renderer2D (except for trivial inputs).

Also, you seem to have removed two [else](https://github.com/processing/p5.js/pull/2942/files#diff-a60317395a4f472a4b9231fcde6b59caL110) branches in the linear scaling adjust; these are still necessary -- at the moment, angles in the upper-right quadrant are being drawn off kilter!

---

@Spongman what you have there is definitely #1779 again. I suggest that we re-open that issue and discuss it there (I think that somewhere in Renderer2D's machinery we must be unintentionally calling something that is moving the pen position mid-arc; it might be the code that draws the fill for certain arc types). I am pretty certain that it is unrelated to the start/stop interpretation and full-circle behaviour.

**Closed** 2019-03-11 17:22 UTC
