### ISSUE TITLE
Precision problem with angle conversion on webkit

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js#2648] opened 2018-02-15 13:34 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Math

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.6.0
- Web browser and version: Safari 11.0.3
- Operating System: macOS 10.13.3
- Steps to reproduce this:

This is a bit of a spaghetti of a bug but I'll try my best to show my findings. Sorry in advance for the long report.

First, the tests are failing on my computer, giving only `Fatal error: test.titlePath is not a function` as message, with no info about what that means exactly. I figured it wasn't a p5 related error so I searched online to find it's a problem with mocha and a possible problem is that some test is failing and mocha somehow isn't able to handle the thrown error (someone can look more into this).

That means some test is failing and I cannot tell which one so I switch the reporter from Nyan to spec which I managed to trace it to a test for `atan` (as much as I love Nyan, maybe it's not fit for purpose anymore 😢). Specifically the test for `atan` in degree mode. The test is testing for equality between `atan` in degree mode and `Math.atan` converted to degree with `degree()`. The log result from the test show that they are not equal, `atan` gives 26.565051177077994 and `Math.atan` gives 26.56505117707799

I tried to run these two in a standalone sketch and in Firefox and Chrome they are both equal to 26.56505117707799, while Safari gave the same result as above. I'm not sure what is common between Safari and node.js on my computer and different with Firefox and Chrome so I have no idea why the precision problem arise.

However, looking into the source I found where the problem stem from: `angleMode(DEGREES)` and `degrees()` uses different function to convert from radians to degrees. `angleMode` uses [`p5.prototype._fromRadians`](https://github.com/processing/p5.js/blob/master/src/math/trigonometry.js#L370) while `degrees` uses [polargeometry.js `radiansToDegrees`](https://github.com/processing/p5.js/blob/master/src/math/polargeometry.js#L8). One uses 180 and PI while the other uses 360 and 2*PI.

For a start we need to decide which one to use consistently as they are doing the same thing just [one uses Pi the other uses Tau](https://www.youtube.com/watch?v=ZPv1UV0rD8U). As for the mocha issue, we'll need to look for more info.

**Comment by Spongman** [comment] 2018-02-15 17:25
Here's the grunt-mocha bug: https://github.com/disqus/grunt-mocha/pull/7 it's not deployed to mpm yet, though.

**Comment by limzykenneth** [comment] 2018-02-18 12:33
Yeah, I figured comparing floats with high precisions are probably not ideal. Any idea on how we can better handle them in tests? I figured if the conversion went through the same path they should end up with the same precision and hence number, is that a correct assumption to make?

**Comment by tau-** [comment] 2018-02-22 17:43
Yes, if the the conversions followed the same code path they will produce the same output. I agree that the issue is the floating point rounding, along with the dependence on the order of operations, impacting the numerical precision. In Chrome 63.0.3239.140 I get the following by mimicking the two call sites:

![screenshot 2018-02-22 at 9 38 00 am](https://user-images.githubusercontent.com/1418502/36554489-45351f1a-17b4-11e8-98fd-f2f7417c0c04.png)

This should be resolved by creating a single code path for the degree to radian conversion. I can go through and clean it up if you want to assign this to me.

**Comment by tau-** [comment] 2018-02-24 02:51
Looks like no tests under Trigonometry are failing on my machine at head. Has this been resolved? I will clean up the conversions regardless.

**Closed** 2018-03-02 19:12 UTC
