### ISSUE TITLE
resizeCanvas error

### ISSUE THREAD

**Issue by arashsa** [processing/p5.js#1221] opened 2016-01-24 16:41 UTC
When resizing the canvas on changes to window size, I get the error:

> 'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.

Here is my code:

```
var header = function (s) {
	s.setup = function () {
		s.createCanvas($("#header").width(), 200);
		s.background(0);
	};

	s.draw = function () {

	};

	s.windowResized = function () {
		s.resizeCanvas($("#header").width(), 200);
	};
}

$(document).ready(function () {
	var temp = new p5(header, "header");
});
```

I have not had this issue in the past.

**Comment by limzykenneth** [comment] 2016-01-24 21:57
Can I know what browser you are using? From what I can find it should be stemming from [here](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L903) but if there is `imageSmoothingEnabled` in the browser you are using, `webkitImageSmoothingEnabled` should not have been called at all.

**Comment by lmccart** [comment] 2016-02-01 21:17
I am only able to reproduce this if I toggle open the inspector while the sketch is running, or with the inspector open, toggle mobile emulation on/off. If I have the console already open and reload the page, I see no warning. I think this warning may be just popping up due to switching contexts of what the browser thinks its rendering or emulating. This is just a hypothesis though. Looking at the code, it looks correct, so I don't know if there's anything to be fixed here. If you have more concrete steps to reproduce, please feel free to reopen this issue.

**Comment by lmccart** [comment] 2016-02-01 21:17
oops, i take that back... i am seeing it on resize now.. will investigate further.

**Comment by lmccart** [comment] 2016-02-01 21:33
ok it looks like this key is set on the CanvasRenderingContext2D by default in the browser, we aren't explicitly setting it. then on resize, every property already set is reapplied after the canvas is resized, and this is triggering the warning. i can't really think of anything to do about this besides the hacky method of manually deleting this property, which seems unnecessary. so i propose we leave as is for now, it's just a warning and it will disappear as soon as chrome actually stops supporting and adding this property.
https://github.com/processing/p5.js/blob/master/src/core/rendering.js#L136

**Comment by arashsa** [comment] 2016-02-01 21:36
Ok, and it seems to only be an issue with Chrome. I don't remember right now, but I've seen other similar warnings using p5js in Chrome that seem to be related, will post these at a later time.

**Comment by lmccart** [comment] 2016-02-01 21:36
ok sounds good. closing this for now... we can reopen if it becomes a bigger problem, but i think it will disappear naturally, eventually.

**Closed by lmccart** 2016-02-01 21:36 UTC
