### ISSUE TITLE
Monitor scale problem.

### ISSUE THREAD

**Issue by EmmanuelPil** [processing/p5.js#4867] opened 2020-10-21 08:58 UTC
- screen scale problem.

Hi.
I'm using a Windows 7 Ultimate 64bit PC with the latest Chrome version.
It's quite common to use at least a 125 % 'scale' screen setting for medium to larger screen resolutions.
And they can be changed rapidly to test. But if you leave the normal 'browser' zoom at 100% the sketches are not playing properly.
For example in [this sketch](https://www.openprocessing.org/sketch/984401), the arrows points are not drawn when the browser zoom setting is not set to 80%. Only lines.  
I have added a temporary workaround, asking once to adjust the zoom in an alert.
[Another sketch ](https://www.openprocessing.org/sketch/878781)also doesn't play or well when zoom isn't correct

**Comment by limzykenneth** [comment] 2020-10-25 16:44
Hi @EmmanuelPil, can you take some screenshots of the problem demonstrating expected and actual behaviour? It is a bit hard for me to diagnose what the problem is from just reading your description and looking at sketches without knowing what they should look like in the first place. Thanks!

**Comment by EmmanuelPil** [comment] 2020-10-25 18:20
Thank you for looking into this. My windows scale (or sometimes called video) setting = 125 %  on my 1920 * 1080 monitor,
otherwise, the font and other items are far too small.
When I leave the normal zoom at 100% in the Chrome browser, the arrow points of the vector-lines in the sketch linked above, are not drawn. When I set the zoom to 80%, they are. In the second sketch, with no zoom adjustment, the fill flood does not work properly.

![Image 41](https://user-images.githubusercontent.com/31894775/97115434-79120000-16d5-11eb-80da-7abad7b86438.png)
![Image 42](https://user-images.githubusercontent.com/31894775/97115438-7d3e1d80-16d5-11eb-86f3-f9d8d657c980.png)
Thank you.

**Comment by limzykenneth** [comment] 2020-10-27 19:41
I don't have a Windows machine to test and also not too familiar with WebGL. I'll refer to @stalgiag to have a look at this. Would be helpful if you can create a bare minimum example then we can get testing the problem quickly.

**Comment by EmmanuelPil** [comment] 2020-10-27 21:52
Of course. I should have done that in the beginning.
I have tracked down the problem.
It is the strokeWeight() function that in a bigger scale percentage amplifies incorrectly.
Testing this code with different browser zoom settings at higher than 125% monitor scale will make this obvious.

```
function setup() {
  createCanvas(40, 40, WEBGL);
  background(0);
  stroke(255);
  strokeWeight(30);
  point(0, 0, 0);
}
```

**Comment by stalgiag** [comment] 2020-10-27 22:26
@EmmanuelPil thanks for the simple example. I tested extensively at zoom settings ranging from 30% to 300% and could not see any issues on my Mac with latest Chrome or Firefox. I will test again on Windows when I get a chance.

**Comment by EmmanuelPil** [comment] 2020-10-28 03:54
Thanks. Just to clarify, It's not just the browser zoom. It only happens when using the windows scale setting above 100%.
See this link.  https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10

**Comment by ashwalk33r** [comment] 2020-11-08 18:32
I can confirm problems with that.

When using Windows Text and UI scale on 125% (those are 2 separate settings) my canvas is 2 times bigger and pixelDensity is 2.
When I lower it to 100% canvas has exact measures and pixelDensity is 1.
I use this feature as my eyesight is impaired and cant really use computer without it.

But why p5js bugs on this?

**Comment by stalgiag** [comment] 2020-12-06 15:14
Hi @EmmanuelPil I got a chance to look at this with Windows. I adjusted the windows scale setting and up and down. I didn't notice a change in the example code you posted. Perhaps it is subtle and I am missing it? Can you post a picture of what renders on your computer with that sketch when your scale is at 125%? Thanks!

**Comment by EmmanuelPil** [comment] 2020-12-06 16:00
![80 percent zoom 100 percent scale](https://user-images.githubusercontent.com/31894775/101285053-fabf7800-37c1-11eb-8982-6f5bbded88c2.png)
![100 percent zoom 100% percent scale](https://user-images.githubusercontent.com/31894775/101285055-ff842c00-37c1-11eb-9b92-0335945280f3.png)
![80 percent zoom 125 percent scale](https://user-images.githubusercontent.com/31894775/101285060-07dc6700-37c2-11eb-804d-f7d80c6f3636.png)
![100 percent zoom 125 percent scale](https://user-images.githubusercontent.com/31894775/101285062-0ca11b00-37c2-11eb-8c8c-5a031fe1a1fb.png)

**Comment by stalgiag** [comment] 2020-12-09 17:00
Thank you @EmmanuelPil ! This is really helpful. Sorry it took me so long to see. Sometimes the more obvious something is the harder it is to see.

I looked into it and the reason this is happening is that the `RendererGL.pointSize` [property](https://github.com/processing/p5.js/blob/main/src/webgl/p5.RendererGL.js#L193) is not modified by `pixelDensity`. It seems a bit odd to me that we are tracking two properties for `strokeWeight`one for points and one for strokes. I faintly recall this decision being made so that there could be different default weights for strokes and points in GL because the 1pixel points are hard for people to see.

Anyways! This can be fixed by adjusting the value of `this.pointSize` when passing to the shader. One could send  `this.pointSize * this._pInst._pixelDensity` instead. [All of this happens in ](https://github.com/processing/p5.js/blob/main/src/webgl/p5.RendererGL.js#L1306)`p5.RendererGL.prototype._setPointUniforms`.

This could be a good issue for someone interested in trying out WebGL contributions.

**Closed** 2020-12-20 07:09 UTC
Labels: area:webgl, bug, good first issue, level:beginner
