### ISSUE TITLE
`orbitControl` Rotation Resets on Canvas Resize

### ISSUE THREAD

**Issue by SableRaf** [processing/p5.js#6382] opened 2023-08-28 06:54 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

1.7.0

### Web browser and version

* Chrome version 116.0.5845.110 (Official Build) (arm64) 
* Safari Version 16.5 (18615.2.9.11.4)

### Operating System

MacOS

### Steps to reproduce this

1. Setup a basic p5.js sketch with `WEBGL` renderer.
1. Use the `orbitControl()` function to allow user interaction with the canvas.
1. Add an event to allow resizing of the canvas using the `windowResized` and `resizeCanvas` functions.
1. Rotate the canvas using the mouse.
1. Resize the browser window.

### Code snippet:

```js

function setup() {
  let s = min(windowWidth,windowHeight)
  createCanvas(s, s, WEBGL);
}

function draw() {
  background(220);
  
  orbitControl();
  strokeWeight(width*0.0015)
  box(width*0.2)
}

function windowResized() {
  canvasSize = min(windowWidth, windowHeight);
  resizeCanvas(canvasSize, canvasSize);
}
```

### Expected Behavior
The rotation should be preserved and the canvas should adjust to the new size.

### Actual Behavior
The rotation gets reset to its initial position when the canvas is resized.

**Comment by inaridarkfox4231** [comment] 2023-08-28 11:03
The issue is discussed in this pull request. Please take a look.
[Created fix for camera settings getting reset each time resizeCanvas() is called](https://github.com/processing/p5.js/pull/6216)

**Comment by davepagurek** [comment] 2023-08-28 13:11
While this is being worked on, in the mean time, [p5.EasyCam](https://github.com/freshfork/p5.EasyCam) probably has enough flexibility for you to be able to preserve orientation across canvas resizes I think!

**Comment by Garima3110** [comment] 2023-10-21 10:37
Hey @SableRaf  I am interested in working on this issue. It would be very helpful if you could point me to the file where the code for the same has been written. Thank you.!

**Comment by davepagurek** [comment] 2023-10-24 22:52
Part of the problem is that right now, the camera's distance from the center changes based on the aspect ratio of the canvas. This is currently why the camera resets on resize. In https://github.com/processing/p5.js/pull/6216, the @RandomGamingDev is going to see what happens if we try to use a fixed distance regardless of aspect ratio, which would eliminate the need to reset the camera position on resize.

If it turns out that we still need that change in distance, then we'd potentially need to update this code to move forward or backwards according to the change in aspect ratio rather than fully resetting the camera:
https://github.com/processing/p5.js/blob/1c2273d6c9113b8ae279de8f0921fabebbc87095/src/webgl/p5.Camera.js#L1984-L1988

But as a first step, I think we need to just experiment with whether or not the camera still looks OK with a fixed distance. This currently happens here, maybe try replacing this with a constant? https://github.com/processing/p5.js/blob/1c2273d6c9113b8ae279de8f0921fabebbc87095/src/webgl/p5.Camera.js#L1952-L1953

**Comment by davepagurek** [comment] 2023-10-26 21:50
I'm going to close this now that https://github.com/processing/p5.js/pull/6216 is merged in, since it addresses this too!

**Closed by davepagurek** 2023-10-26 21:50 UTC
Labels: Bug, Area:Events, Area:WebGL
