### ISSUE TITLE
Error: Cannot read property 'transpose3x3' of null 

### ISSUE THREAD

**Issue by Flishworks** [processing/p5.js#1770] opened 2017-01-20 15:53 UTC
I was getting the following error in a script I wrote:

`Uncaught TypeError: Cannot read property 'transpose3x3' of null
    at p5.Matrix.inverseTranspose (p5.js:29775)
    at p5.RendererGL._setMatrixUniforms (p5.js:30711)
    at p5.RendererGL.drawBuffers (p5.js:30434)
    at p5.RendererGL.ellipse (p5.js:31617)
    at p5.ellipse (p5.js:7736)
    at draw (ripple.js:54)
    at p5.redraw (p5.js:13810)
    at p5.<anonymous> (p5.js:8927)`

While I don't fully understand what this is doing, I was able to hack my way by it by throwing a conditional around line 29775, executing only if p5.Matrix.prototype.invert3x3() does not return null, like so:

`  if(this.invert3x3()!== null){
    this.invert3x3().transpose3x3(this.mat3);
  }`

Though i don't know what else this might affect, it seems to work for my routine. You can see the full script at http://avikazen.com/. Before the fix, i would only get the error when clicking near the bottom two corners of the screen. This creates a ripple propagating from those points.

**Comment by lmccart** [comment] 2017-01-21 00:54
Could you please post an isolated snippet of code that creates this error? It's difficult to track down from a full working project because there's a lot going on. Thanks!

**Comment by lmccart** [comment] 2017-01-29 00:12
I'm going to close this because I haven't been able to reproduce, please feel free to reopen if you can post a snippet we can use to debug. Thanks!

**Closed by lmccart** 2017-01-29 00:12 UTC
Labels: can't reproduce

**Comment by Zemingsoares** [comment] 2017-03-20 10:54
@lmccart 
@Flishworks 

I am new to p5 and javascript so I am not sure if there is something wrong with the code  or if I am getting the same bug (but not that new I would think I could make a blue rectangle rotate......). But I saw you requested a smaller sketch or snippet to isolate the bug so I hope this helps:

```
function setup() {
  createCanvas(1000, 500, WEBGL);
  background(100);
}

function draw() {
    for (var i = 0; i < 360; i++){
        var rad = radians(i);
        rotate(rad);
        fill(0, 0, 255);
        plane(50, 50);
    }
}
```

This is what I am getting: 
`
31017: Uncaught TypeError: Cannot read property 'transpose3x3' of null`

**Comment by Chovanec** [comment] 2017-06-24 19:20
i got same error on this code:

```
var rotate = 0;

function setup()
{
	var w = 900;
	var h = 900;
	createCanvas(w, h, WEBGL);
}

function draw()
{
	background(55);

	rotateY(rotate);
	rotate += .1;

	fill(255);
	box(50);
}
```

**Comment by slothdude** [comment] 2018-10-23 15:18
I was able to reproduce the error by using react router, p5-react-wrapper, and bootstrap. This error would pop up when following a `<Link />` react-router element from a page where I had a 3d sketch to a page just displaying "hi". I was also able to stop the error by changing the code in the p5.js lib folder by wrapping it in a null check like so: 

```
if(this.invert3x3()){
    this.invert3x3().transpose3x3(this.mat3);
}
```

I would like to submit a pull request if possible to implement this. Here is my repository where the errors came from: https://github.com/slothdude/react-bootstrap-redux
