### ISSUE TITLE
DOM library: Uncaught type error input is not a function

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js#1355] opened 2016-04-06 21:42 UTC
I'm working on a tutorial and came across an issue with the DOM library's text input object.  Not sure if this is just user error, but I can't seem to find the input event listener in the src.  running the example code from the p5 website produces uncaught type error:

```
function setup() {
  var inp = createInput('');
  inp.input(myInputEvent);
}

function myInputEvent() {
  console.log('you are typing: ', this.value());
}
```

**Comment by indefinit** [comment] 2016-04-06 21:48
FWIW the changed() listener works as expected, so if input() is not a preferred event listener, perhaps changed() is better?

**Comment by lmccart** [comment] 2016-04-12 13:52
hm, i am having a hard time reproducing the error. i'm testing with p5.dom.js version v0.2.9 in the browser and p5 editor. can you give more details about OS and browser you're using?

**Comment by indefinit** [comment] 2016-04-13 12:04
I tried it on Mac/Chrome 50.0.2661.66 beta (64-bit).  I'll try to replicate on other browsers.

**Comment by indefinit** [comment] 2016-04-13 12:27
Ah, ok I was able to isolate the problem.  It seems I get the error only when I'm using Thimble (been testing this editor with my class).  If using the p5.js Desktop editor or vim/sublime with localhost, I'm not able to replicate.  I just tried the same code in instance mode in case the issue was coming from global namespace pollution, but I get the same error.  Since Thimble isn't an official p5 editor, I think it's ok to mark this issue as resolved and if we start to use Thimble more widely and encounter the error in the future we can reopen.

**Comment by lmccart** [comment] 2016-04-13 15:17
aha interesting! thanks for tracking this down. i'll test it in thimble and see if i can figure out the problem, and if i can't ill give up and close this issue for now, per your suggestion. :)

**Comment by lmccart** [comment] 2016-05-11 18:59
oddly, I'm still not able to reproduce in thimble. here's a test, does this work for you? maybe it was fixed recently?
https://thimbleprojects.org/lmccart/66589/

**Comment by lmccart** [comment] 2016-06-28 01:11
I'm going to close this for now since I haven't been able to reproduce, please feel free to reopen if there's further info or example demonstrating the issue.

**Closed by lmccart** 2016-06-28 01:11 UTC
Labels: area:dom, can't reproduce

**Comment by orazdow** [comment] 2018-10-13 01:41
I am getting this error, even if the only line in my code is `radio = createRadio();` in setup().

The full error is:
p5.dom.min.js:1 Uncaught TypeError: a._validateParameters is not a function
    at e.a.createRadio (p5.dom.min.js:1)
    at setup (main.js:29)
    at e.<anonymous> (p5.min.js:4)
    at e.<anonymous> (p5.min.js:4)
    at new e (p5.min.js:4)
    at e (p5.min.js:3)

**Comment by AngeloGiacco** [comment] 2019-03-21 19:02
I am getting a similar error. 

The console shows an error message of "Uncaught TypeError: p5._validateParameters is not a function at p5.dom.js:421"

The line that causes the error is the following:
`fadeSlider = createSlider(1, 4, 2, 0);`

Any ideas?
