### ISSUE TITLE
p5 line() function saying that only two arguments were present when 4 were given.

### ISSUE THREAD

**Issue by Ongshu777** [processing/p5.js#4389] opened 2020-03-17 19:40 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 0.10.2
- Web browser and version: Chrome 80.0.3987.132
- Operating System:  Windows 10
- Steps to reproduce this: 

```
translate(width/2, height/2) // Probably doesn't matter
line(0, -height/3, 0, 0) // Logged Error : p5.js says: line() was expecting at least 4 arguments, but received only 2 at about:srcdoc:77:3. [http://p5js.org/reference/#p5/line] 
```
I think, since 0 is a falsey or falsy, p5 checked if the arguments were truthy but ignored the case of 0.
My suggestion would be to replace `!x` with `(!x && x !== 0)`.

**Comment by DivyamAhuja** [comment] 2020-03-18 07:45
https://editor.p5js.org/DivyamAhuja/sketches/3AsTbVfU

am not able to reproduce same problem

**Comment by fenilgandhi** [comment] 2020-03-18 12:44
+1 @DivyamAhuja ,  even i cannot reproducethis bug.

Hey, @Ongshu777, are you sure this is the exact code that you were testing because in your given code even `rotate` would definetly give an error. As `rotate` expects a number array or a p5 vector in the second parameter while you have passed a number.

**Comment by Ongshu777** [comment] 2020-03-18 14:57
Right. It's actually a `translate`. Edited.

**Comment by akshay-99** [comment] 2020-03-18 15:32
@Ongshu777 Hi there! Even with translate it still seems to work properly as seen here
https://editor.p5js.org/akshay.padte/sketches/tOVTEUcUb

Or as @DivyamAhuja pointed out with his link, it worked with rotate too. 

There must be something else at play here. 
Can you please verify if the version you mentioned is correct or provide more details to the problem?

**Comment by Ongshu777** [comment] 2020-03-18 21:01
@akshay-99  The version is the one in p5.js editor.

**Comment by DivyamAhuja** [comment] 2020-03-18 23:05
@Ongshu777 Is it working correctly with the links we provided? and can you provide link to code in editor... because sometimes it maybe pe problem with other part of code or slight negligence which can cause error

**Comment by Ongshu777** [comment] 2020-03-19 08:39
@DivyamAhuja That project was changed, so I can't provide a link.

**Comment by montoyamoraga** [comment] 2020-05-03 15:31
since we weren't able to replicate the error, i am closing this issue

**Closed by montoyamoraga** 2020-05-03 15:31 UTC
Labels: bug
