### ISSUE TITLE
keyPressed() only works once per key (for certain keys) in Chrome, keyReleased() not at all

### ISSUE THREAD

**Issue by rruubboott** [processing/p5.js#3569] opened 2019-03-05 15:51 UTC
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Events

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 
v0.7.3
- Web browser and version: 
72.0.3626.119
- Operating System: 
macOS mojave
- Steps to reproduce this:

keyPressed() will fire once for any of the arrow keys, then never again. Many other keys (most letters, for instance) are fine - but some letters will only fire once (e,a,c - for example). This does not happen in editor.p5js.org nor on Opera. Just Chrome....

let counter = 0;

function setup() {
  createCanvas(800,800);
}

function draw() {
  // put drawing code here
}

function keyPressed(){
  counter++;
  console.log(counter);
}

**Comment by sanketsingh24** [comment] 2019-03-05 20:10
I feel this is same as #3450 and #3193, the solution is being discussed there atm.

**Comment by outofambit** [comment] 2019-03-05 20:20
@ruairimurphy thanks for filing this issue, this is a really helpful write up!

@sanketsingh24 this issue looks different than #3193 as it doesn't rely on having multiple sketches to reproduce the bug and #3450 hasn't been investigated enough to know if its a bug in the library or just mistakes in the examples. i'd like to keep this issue open and separate (but its good to have them all linked together).

**Comment by DavidWeiss2** [comment] 2021-04-16 05:39
This is not presented in the current version.
@rruubboott, can you try to reproduce it on your machine? (I tried with the same version of the webserver but on windows and the current version of p5).

**Comment by Qianqianye** [comment] 2024-05-22 19:49
Closing this because it's not reproducible.

**Closed by Qianqianye** 2024-05-22 19:49 UTC
Labels: Bug, Area:Events
