### ISSUE TITLE
p5.Image.blend() throws TypeError

### ISSUE THREAD

**Issue by vassiliskrikonis** [processing/p5.js#1275] opened 2016-02-29 13:44 UTC
Calling the `blend()` function on an `p5.Image` instance object throws a TypeError "_cannot read property 'blend' of 'undefined_'".

```javascript
img.loadPixels();
var pixelStrip = img.get(lineX, 0, 1, height);
img.blend(pixelStrip, 0, 0, 1, height, 1, 0, 1, height, MULTIPLY);
img.updatePixels();
```

**Comment by JamesJDillon** [comment] 2016-03-02 16:35
I know this is 2 days late, but here's the p5.js [reference for blend()](http://p5js.org/reference/#/p5/blend). You'll see that blend() is a P5.Image method, and should be called like `blend(img1, 0, 0, 33, 100, 67, 0, 33, 100, LIGHTEST);` and not `img.blend(pixelStrip, 0, 0, 1, height, 1, 0, 1, height, MULTIPLY);`

**Comment by lmccart** [comment] 2016-03-03 21:50
thanks @JamesJDillon!

**Comment by limzykenneth** [comment] 2016-03-03 23:09
Erm...actually there is a `blend()` function under the `p5.Image` object: [reference](http://p5js.org/reference/#/p5.Image), [source](https://github.com/processing/p5.js/blob/master/src/image/p5.Image.js#L540).

I haven't test the code myself but it shouldn't be undefined at least...

**Comment by lmccart** [comment] 2016-03-03 23:13
erp! i will check it out. thanks. :)

**Comment by PaliwalSparsh** [comment] 2016-03-05 09:30
@lmccart @limzykenneth when writing examples for p5.image similar problem occured to me, this was the reason I didn't write any example for blend() but for every other of p5.Image's method. I guess I should have filed an issue then only.

**Comment by indefinit** [comment] 2016-04-25 13:13
just wanted to bump this issue up if possible.  It seems blend should be a method of p5.Image, however the problem is that the src references this._renderer which reassigns the scope globally.  Also, I wonder if arguments 2-9 should be optional since it's a lot of parameters to write when all you want to do is quickly blend two images together.

**Closed** 2016-04-25 14:06 UTC
