### ISSUE TITLE
Cone with transparent texture is opaque on half of its surface

### ISSUE THREAD

**Issue by DiDi2018** [processing/p5.js#4482] opened 2020-04-22 22:43 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.0.0
- Web browser and version: Firefox 75.0, Chrome 81.0.4044.122
- Operating System: Kubuntu 19.10
#### Steps to reproduce this:

When using a transparent texture with text created with createGraphics() on a cone, it will only be transparent on half of its surface. When putting a bigger value on detailY, the cone will be more transparent, but a quarter of the cone will still be opaque. Adding a background(0,0,0,0) to the graphics created won't do anything. Drawing or not drawing the base of the cone also doesn't make a difference.

Example sketch: <a>https://editor.p5js.org/DiDi2018/sketches/RLTOdkhwG</a>

**Comment by DivyamAhuja** [comment] 2020-04-24 10:40
@stalgiag I wonder if this has something to do with #4458

**Comment by violetcraze** [comment] 2020-05-10 12:55
Looks to maybe related to depth test.

If you put:
```
let gl = document.getElementById('defaultCanvas0').getContext('webgl');
gl.disable(gl.DEPTH_TEST);
```
in setup then it solves this particular problem.

However depth test is there for a reason so don't know if it's a universal solution. Hope it helps find where the problem is coming from.

**Comment by sflanker** [comment] 2022-03-29 02:16
This is related to https://github.com/processing/p5.js/issues/3736. Fragments the get drawn out of order (i.e. front most triangle drawn before occluded triangle), will take precedence over fragments behind them even when they have low alpha values. The best solution is to draw all triangles back to front which works so long as you don't have intersecting triangles. However when you don't have control of how he geometry is being drawn you don't have control of the drawing order, which is the case here with p5.js 3d primitives. A quick fix assuming your texture consists of either opaque or transparent pixels is to use a custom shader with the following:

```
if (color.a < 0.5) {
    discard;
}
```

cite: https://github.com/processing/p5.js/issues/3736#issuecomment-640545729

**Comment by davepagurek** [comment] 2023-01-16 11:28
Hi! This is related to rendering of images with transparency, so I'm going to close this issue in favor of https://github.com/processing/p5.js/issues/3736 so all related discussion can be in one place. Feel free to continue the conversation over there 🙂

**Closed by davepagurek** 2023-01-16 11:28 UTC
Labels: Bug, Area:WebGL
