### ISSUE TITLE
smooth() breaks ortho() and perspective() in WebGL

### ISSUE THREAD

**Issue by martinleopold** [processing/p5.js#3348] opened 2018-11-27 19:30 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.2
- Web browser and version: 70.0.3538.110 (Official Build) (64-bit)
- Operating System: macOS 10.13.6
- Steps to reproduce this:

```
// Once smooth() is called, switching projection (ortho or perspective) doesn't work anymore
// Also smooth() seems to overthrow stroke() and fill() settings
//
// Instructions: 
// * Run code as is. Rotating code is rendered with parallel projection. 
// * Click on cavas.  Cube should be rendered with perspective projection but isn't. 
// * Set useSmooth to false and repeat steps to see desired behaviour.

let useSmooth = true;
let useOrtho = true;

function setup() {
  createCanvas(500,500,WEBGL);
  setupCamera();
  
  stroke(255);
  fill(0);
  if (useSmooth) smooth(); // erases stroke and fill from before
}

function draw() {
  background(0);
  rotateY(TWO_PI / 1000 * frameCount);
  box(250);
}

function setupCamera() {
  if (useOrtho) ortho(); else perspective();
}

function mouseClicked() {
  useOrtho = !useOrtho;
  setupCamera();
}
```
As a side note: The reference docs say that smooth() is set by default, which doesn't seem to be the case in WebGL. Is 3D/WebGL support experimental?

**Comment by stalgiag** [comment] 2019-02-12 23:45
Hi @martinleopold this no longer reproduces in master. As far as defaults for antialiasing and resetting of fill and stroke, this is because of the fact that a new context is created when you call smooth.  This is just part of the current implementation of smoothing. Perhaps a future documentation change is order but since the main problem here is gone I will close this for organizational purposes. Thanks!

**Closed by stalgiag** 2019-02-12 23:45 UTC
