### ISSUE TITLE
brightness() doesn't work unless HSB colorMode

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#563] opened 2015-03-05 15:12 UTC
This works:

```
  createCanvas(640, 360);
  background(0);
  colorMode(HSB, 255);
  var c = color(0, 126, 255);
  var value = brightness(c); 
  fill(value);
  rect(50, 20, 35, 60);
```

But this fails:

```
  createCanvas(640, 360);
  background(0);
  colorMode(RGB, 255);
  var c = color(0, 126, 255);
  var value = brightness(c);
  fill(value);
  rect(50, 20, 35, 60);
```

As an aside, I'm wondering if `brightness()` should be overloaded to work if an array of 4 values is passed in, this way code can be written like: `var b = brightness(get(x,y));`

**Comment by zacharystenger** [comment] 2015-04-07 18:43
Hey @shiffman, I was looking into this issue and brightness in RGB mode is working fine for me.  Both code snippets created a white rectangle on a black background.

**Comment by workergnome** [comment] 2015-05-26 18:42
I also tried the provided test case, and it works for me.  @shiffman, can you add any clarification? 

(also, I like the overloading idea.)

**Comment by workergnome** [comment] 2015-05-27 11:56
I created a feature request for the overload.

Closing this as **Cannot Reproduce**—@shiffman, if you still are seeing this issue, please reopen it!

**Closed by workergnome** 2015-05-27 11:56 UTC
Labels: area:color, can't reproduce

**Comment by shiffman** [comment] 2015-06-01 13:47
Indeed this is working for me, perhaps whatever I saw before was fixed or I was just confused!
