### ISSUE TITLE
TypeError: strokeWeight is not a function

### ISSUE THREAD

**Issue by cblf** [processing/p5.js#1989] opened 2017-06-07 15:14 UTC
I'm trying a very simple action : setting the width of the plotter.
strokeWeight(40) should do the job. However, it simply does not exist as a function 👎 

TypeError: strokeWeight is not a function

version is current 0.5.11.

**Comment by mlarghydracept** [comment] 2017-06-07 17:42
Hi, I tested with 0.5.11 and this is what I got --
![screen shot 2017-06-07 at 10 37 48 am](https://user-images.githubusercontent.com/10382506/26892627-c242979e-4b6d-11e7-8b9f-9120bb4faf96.png)

Are you sure that you are calling `strokeWeight()` from within a function such as `setup()` or `draw()`? Maybe refer the questions about global vs instance mode [here].(https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions)

**Comment by cblf** [comment] 2017-06-08 09:32
Thank you for this answer, mlarghydracept.

I have tested by calling directly from draw() and it works but it does not work when called from a function that is called by draw().
That is a serious drawback because I'm on a quite complex drawing that require to change stroke weight regularly. The code need to be structured by function in order to be readable.
I can't see why strokeweight is restricted to the closure of draw() but it is a serious restriction.

**Comment by lmccart** [comment] 2017-06-08 13:51
```javascript
function setup() { 
  createCanvas(400, 400);
} 

function draw() { 
  background(220);
	doStuff();
	ellipse(200, 200, 50, 50);
}

function doStuff(){
	strokeWeight(10);
}
```

this example, calling strokeWeight from a function called by draw(), seems to work fine.
can you please post a snippet of your code that demonstrates the problem?

**Comment by lmccart** [comment] 2017-06-11 22:04
I'm closing this since I can't reproduce but please feel free to reopen if you can post a snippet that illustrates the issue.

**Closed** 2017-06-11 22:03 UTC
