### ISSUE TITLE
keyPressed works only for one instance of p5.js

### ISSUE THREAD

**Issue by Ajayneethikannan** [processing/p5.js#3508] opened 2019-02-09 06:12 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: chrome 72.0.3626.96

- Operating System: ubuntu 16.04 
- Steps to reproduce this:

https://codepen.io/AjayTDM/pen/qgxYYd

- Here in this sketch I am trying to use keyPressed in two different instances, and it registers only in one instance. The mousePressed works on both the instances though.
- The bug also causes isKeyPressed and keyIsPressed to be detected only for one instance.

Looking forward to solve this issue!

**Comment by meiamsome** [comment] 2019-02-09 07:37
This is a duplicate of #3193, I believe.

**Comment by Ajayneethikannan** [comment] 2019-02-09 07:48
Oh I am sorry, I will work on that issue then ,  thank you ! Should I close this issue?

**Comment by meiamsome** [comment] 2019-02-09 07:52
@Ajayneethikannan Yep, I think so - hopefully the comments on there will be helpful :)

**Closed** 2019-02-09 07:54 UTC
