### ISSUE TITLE
Can't get loadTable() to pull in csv dataset but works when i use the loadStrings() url in preload

### ISSUE THREAD

**Issue by sofia12343** [processing/p5.js#2749] opened 2018-03-29 13:18 UTC
Hi I made a map with earthquake data with an earthquakes api using loadStrings() url 

function preload() {
	mapimg = loadImage('https://api.mapbox.com/styles/v1/mapbox/dark-v9/static/0,0,1,0,0/1024x512?access_token=pk.eyJ1Ijoic29maWFmZXJyYXJvMTk5NiIsImEiOiJjamZiMzQ1bmkzbXJ2MnpvNG1nd3Z2ZWl2In0._hdJnbjf7jxau1PkMoK7Cw');
 earthquakes = loadStrings('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.csv'); past day

}

But when I try to change the url dataset into a loadTable() csv file, it doesnt work. Do you have an advice or could you direct me how? Please let me know if you can, Thanks!

**Comment by kjhollen** [comment] 2018-03-31 21:10
Hi @sofia12343 can you provide some more details? When I copied your code to test, there was an error because "past day" on the line after loadStrings produced an error. When I removed that and changed to loadTable, that seemed fine—what was the error that you saw? Thanks!

**Comment by lmccart** [comment] 2018-04-07 01:13
hi @sofia12343 I'm going to close this for organizational purposes, but please feel free to reopen if you have more details to reproduce the issue

**Closed by lmccart** 2018-04-07 01:13 UTC
