### ISSUE TITLE
Stretched 3D renders

### ISSUE THREAD

**Issue by zettam** [processing/p5.js#1010] opened 2015-10-15 03:57 UTC
I have noticed that when ````resizeCanvas(windowWidth, windowHeight);```` is called under ````windowResized()```` the 3d content stretches.

Is this a bug, or a feature?

**Comment by indefinit** [comment] 2015-10-15 13:32
Hi Zettam,

Are you calling resizeCanvas() manually in your app or do you mean through another built-in method?  resizeCanvas() by default is just for resizing the canvas element size which works a little differently in 2D vs webgl.  In webgl, since we also have a model view matrix, resizing the canvas without changing the MVMatrix (through a function like perspective() ) will produce a stretched aspect ratio as you describe.  

Feel free to post a code example so we can debug further. Thanks!

**Comment by lmccart** [comment] 2015-11-08 03:43
@indefinit it's been a while, so if we can't reproduce I think it's fine to close this. it can always be reopened later if there's sample code or clarification.

**Comment by indefinit** [comment] 2015-11-08 03:51
I haven't been able to reproduce a bug, so good to close. Thanks

**Closed by indefinit** 2015-11-08 03:51 UTC
Labels: area:3d

**Comment by RanzQ** [comment] 2015-11-16 16:16
@Imccart @indefinit I'm having this issue, not sure if I'm doing something wrong or if p5 needs a fix. I created a codepen:

http://codepen.io/anon/pen/YyBrYP

What I'd like in my scene, is to keep the spheres round with every aspect ratio. I use `height` to calculate the radius. Now they initialize round (with different window sizes) as expected but on resize they stretch.

After load:
![image](https://cloud.githubusercontent.com/assets/1150613/11187163/072c6394-8c8e-11e5-97aa-a31d30947311.png)

And when resized:
![image](https://cloud.githubusercontent.com/assets/1150613/11187144/e800e5bc-8c8d-11e5-9115-1131dbb7f9b4.png)

**Comment by RanzQ** [comment] 2015-11-17 06:34
Resetting perspective after resizeCanvas seems to fix this:

`p.perspective(60 / 180 * p.PI, p.windowWidth/p.windowHeight, 0.1, 100)`
