### ISSUE TITLE
printing an array from setup() doesn't behave as expected

### ISSUE THREAD

**Issue by mct** [processing/p5.js#4070] opened 2019-10-11 20:00 UTC
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.9.0 (using editor.p5js.org)
- Web browser and version: Chrome 76.0.3809.132 
- Operating System: MacOS 
- Steps to reproduce this:

I expected this code:

```javascript
var foo = [0, 0]

function setup() {
  print(foo);
}

function draw() {
  foo[0]++;
}
```
to output `[0,0]`.

But I was quite surprised when it generated `[1,0]` instead.

The bug appears to be related to a timing/race condition of some kind.  If I add `frameRate(1)` to `setup()`, the bug goes away.  And if I change it to `frameRate(1000)`, I usually see `[2,0]`.

**Comment by stalgiag** [comment] 2019-10-12 19:14
Hm I think this has more to do with how the console in the online editor is working. The array is being logged by reference, and the editor's console doesn't print the value until 1 frame into the draw loop.

If you open your browsers window and look at the log instead, it will likely be a larger number, frozen at whatever point it is first 'viewed' (at least in Chrome).

This for example behaves as expected:
```
var foo = [0, 0]

function setup() {
  print(foo.slice());
}

function draw() {
  foo[0]++;
}
```
Which tells us that the code inside of `setup()` is running before that first pass through `draw()`.

This might be a quirk of how the editor console is written, I am unsure. This could be of interest to the people that work on the editor so I'll pass it along to there.

**Comment by stalgiag** [comment] 2019-10-12 19:21
Actually I checked out the issues in the [p5.js-web-editor repository](https://github.com/processing/p5.js-web-editor), and I think I can safely say that this is a duplicate of [this issue.](https://github.com/processing/p5.js-web-editor/issues/1055)

I would subscribe to that issue for updates on this bug. In the meantime, I am going to close this issue. Thanks again!

**Closed by stalgiag** 2019-10-12 19:21 UTC
