### ISSUE TITLE
noiseMode(SIMPLEX)

### ISSUE THREAD

**Issue by kaitabuchi314** [processing/p5.js#6193] opened 2023-06-08 13:48 UTC
### Increasing Access

I think Simplex Noise would be a very good enhancement. It seems p5.js is not working on it. 

Here are some reasons Simplex is better:
Improved computational efficiency.
Higher quality and smoother results.
Improved isotropy and higher-dimensional performance.
Easier implementation and understanding.
Accessibility:
Improved Visual Accessibility: Simplex noise provides smoother, more visually appealing results compared to Perlin noise. This characteristic is especially important for users who may have visual impairments or sensitivities. By incorporating Simplex noise into p5.js, individuals with different visual abilities will have access to a wider range of visually pleasing and inclusive generative art experiences.

Enhanced Performance and Optimization: Simplex noise is computationally efficient, making it particularly valuable for users who may be working on resource-constrained devices or have limited processing power. Its improved performance can benefit users with diverse computing capabilities, ensuring a smooth experience across a broader range of devices.

Easier Implementation and Understanding: The implementation of Simplex noise is generally considered to be simpler and more intuitive than that of Perlin noise. By adding Simplex noise to p5.js, you lower the barrier of entry for newcomers and make it easier for developers of all levels of expertise to create complex and engaging graphics. This fosters inclusivity within the p5.js community and encourages a wider range of people to explore creative coding.

Diverse Artistic Possibilities: Simplex noise offers a distinct aesthetic quality that differs from Perlin noise. By introducing Simplex noise into p5.js, you empower artists, designers, and creative coders to experiment with new visual styles and artistic expressions. This diversity of possibilities further enriches the p5.js ecosystem and encourages a more inclusive community of creators.

This is a feature request based on issue (It was a discussion) #6152.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [X] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

If you want to make sure that the previous projects don't break, here is a solution:
I fell that it would be a good idea to have maybe a noiseMode(SIMPLEX) and noiseMode(PERLIN), this would allow a decision by the user, if they want Perlin Noise they could use noiseMode(PERLIN), or just leave it out (It could be the default for compatibility), or if they want to use (better) Simplex Noise they could use noiseMode(SIMPLEX).

**Comment by limzykenneth** [comment] 2023-06-08 19:25
Hi @kaitabuchi314, sorry the access statement and other feature request details can be added in #6152 instead of opening a new issue (which will just be a duplicate of the other one). I'll close this issue in favour of continuing conversations in #6152, especially since @hellonearthis has participated there already. Thanks.

**Closed by limzykenneth** 2023-06-08 19:25 UTC
Labels: Feature Request, Area:Math
