### ISSUE TITLE
The directional light example doesn't work right

### ISSUE THREAD

**Issue by JimBrink** [processing/p5.js#4716] opened 2020-07-27 14:18 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
The example on https://p5js.org/reference/#/p5/directionalLight is supposed to change when the mouse is moved.  But it doesn't.
If the position of the light is changed in the code before the run, the light is moved.  It kind of seems to me that light position is fixed by the first time directionalLight is called.
- p5.js version:  p5.js v1.1.9 July 22, 2020 
- Web browser and version: tested in Firefox, Chrome and Opera
- Operating System: Windows 10
- Steps to reproduce this:
Run the example on the reference page.

**Comment by matvs** [comment] 2020-07-27 15:13
I would like to work on this issue.

**Comment by akshay-99** [comment] 2020-07-27 16:14
Hi!

Thanks @JimBrink for reporting this and @matvs for your interest. I still believe this should have been fixed in #4406 and that the fix should have been applied after the latest release. So I was just trying to see why it didn't :sweat_smile: . I noticed that despite the release, the p5 version used by the examples is still 1.0.0 as seen here: https://p5js.org/assets/js/p5.min.js  
The banner still says `p5.js v1.0.0 February 29, 2020`. I think we should first try updating that.

If this problem still exists after the version issue on the website is addressed, feel free to work on it :smile:

**Comment by limzykenneth** [comment] 2020-07-27 19:10
The version that should be deployed onto the live site is showing the [correct version](https://github.com/processing/p5.js-website/blob/gh-pages/assets/js/p5.min.js). @lmccart Did the deploy from the github branch to the live site run for the new releases?

**Comment by lmccart** [comment] 2020-07-27 21:04
The deploy did happen, and I just ssh'd in and confirmed the file is at v1.1.9. A cacheing issue then? I seem to recall this happening a couple times in the past but we never tracked it down.

**Comment by limzykenneth** [comment] 2020-07-27 21:14
Ah yes, should be caching then. Most resources have query string that ensure when the file changed a new version is cached but since `p5.min.js` doesn't have the query string attached it probably is still cached.

**Comment by lmccart** [comment] 2020-07-27 21:17
So if we add a query string into the website pages that link to this file, would this fix it?

**Comment by limzykenneth** [comment] 2020-07-27 21:18
I'd expect so.

**Closed** 2020-08-03 06:22 UTC
Labels: bug
