### ISSUE TITLE
WebGL rendering issue on transparent geometries

### ISSUE THREAD

**Issue by rich-gg** [processing/p5.js#2105] opened 2017-08-02 14:29 UTC
- [ X ] Found a bug
- [ X ] WebGL
- [ X ] Desktop/Laptop
 
#### Details about the bug: 
Hi there :)

As mentioned on [this ](https://forum.processing.org/two/discussion/comment/103189#Comment_103189)forum post (where you'll find screenshots)
It looks like when you run this code :

var redHourAlpha = 0;
var alphRedHour = 0;
 
function setup() {
  createCanvas(800, 600, WEBGL);
} 
 
function draw() {
  background(240);
  alphRedHour = map(mouseY, 0, height, 25, -25);
  ladder();
}
 
function ladder() {
  //LADDER
  for (var i = -45; i <= 45; i += 3.75) {
    redHourAlpha = i;
    var redHourAlpha2 = map(alphRedHour, -12, 12, -45, 45);
    //
    var ladderAlphaR = sq(abs(redHourAlpha - redHourAlpha2));
    var radiusRladder = 285;
    var redHourXladder = radiusRladder * cos(radians(redHourAlpha));
    var redHourYladder = radiusRladder * -sin(radians(redHourAlpha));
    //
    push();
    rectMode(CORNER, CENTER);
    translate(-redHourXladder+100, redHourYladder, 0);
    fill(128, ladderAlphaR);
    //
    rect(0, 0, 200, 2);
 
    pop();
  }
}

on a PC, you get a clean fading to transparency of the dark grey lines
and, when you run the same code on a Mac, you get some  fading to white instead of transparency

you can also see it when going to this link:
[http://rich.gg/fuzo/](http://rich.gg/fuzo)

**Comment by mlarghydracept** [comment] 2017-08-02 17:57
Hi! Thanks for submitting the issue. I don't have a PC to test on at the moment but just a quick question - Are you using the same browser across those platforms in your testing?

**Comment by rich-gg** [comment] 2017-08-07 07:54
I have had the thing tested on Chrome for both Mac and PC
The thing works good on PC and bad on Mac

the bug is: 
 - using fill(128, alpha); 
 * the alpha value turns the color to TRANSPARENT on PC 
 * the alpha value turns the color to WHITE on MAC

Here is another test I made
http://rich.gg/alphaBars/

the code is ultra simple

`  function setup() {
    createCanvas(800, 600, WEBGL);
  }

  function draw() {
    background(240);
    for (var i = 0; i < 255; i++) {
      push();
      rectMode(CENTER);
      translate(0, -255 + (i * 2), 0);
      fill(128, i);
      rect(0, 0, 200, 2);
      pop();
    }
  }`

**Comment by mlarghydracept** [comment] 2017-08-08 05:15
I am able to recreate it. You can see a leftover silhouette from prior sketches which seems to mean the buffer isn't clearing correctly.

![screen shot 2017-08-07 at 10 13 51 pm](https://user-images.githubusercontent.com/10382506/29057248-bcd3034a-7bbd-11e7-82fd-d31b3348fdc7.png)

It also seems specific to Chrome+Mac because the results are correct on Firefox+Mac

![screen shot 2017-08-07 at 10 14 48 pm](https://user-images.githubusercontent.com/10382506/29057257-d8dc9c04-7bbd-11e7-81ca-308531f34f67.png)

I will investigate a bit.

**Comment by rich-gg** [comment] 2017-08-08 06:13
great !

**Comment by mlarghydracept** [comment] 2017-08-08 06:47
This seems to be due to a combination of z-fighting and how the different browsers blend into the background web page. You can test this by adding `style="background:black"` inside of the `<body>` tags of your index.html file.

I [made a branch](https://github.com/mlarghydracept/p5.js/tree/fix_alpha_fill_on_chrome) that adds `gl.depthFunc(gl.ALWAYS)` to calls to fill. This should fix the z-fighting but will still be colored by the back dom element. But you can make that the same color as your canvas background as a workaround. This is a very temporary fix and may break other things in your code but I thought I'd put it up for you in case it is helpful.

**Comment by rich-gg** [comment] 2017-08-08 07:09
having the thing tested by my "mac friends" so I'll tell you if it fixes it fine for me
But thank you ! I'm impressed by how quickly and skillfully you handled that :O

**Comment by rich-gg** [comment] 2017-08-08 07:42
had the   <body style="background:#f0f0f0"> trick tested on Mac and it doesn't help on Safari or Chrome
It is not a matter of life or death to me anyway, I just thought It would be helpful to report the bug :)

**Comment by mlarghydracept** [comment] 2017-08-08 20:54
Yeah the background color trick won't work by itself because of the z-fighting. If you build that branch that I pointed to it and use the background color trick it should work on Chrome and Safari on Mac at least in my testing. But as I said since I changed the `gl.depthFunc(gl.ALWAYS)` then this could potentially break something else in your code if your project is much more complicated than the example code.

Anyways, if it isn't a pressing issue then I wouldn't worry about doing the above for now. There is a lot of work happening on WebGL right now and one of us may uncover an actual fix for this along the way.

**Comment by rich-gg** [comment] 2017-08-09 06:43
ok cool
so this stays open as actual issue to be addressed along the way ?

Thank you guys form the tremendous work you do, really, you empower people AF ;)
rich

**Comment by BiLachner** [comment] 2017-10-08 17:37
Is this the same error? I have in in GeoGebra which offers a HTML5 based 3D-view that uses afaik WebGL -> Link to the interactive page https://www.geogebra.org/m/nJzV8Euq#material/S2UP5RRz
![screenshot_20171008_193531](https://user-images.githubusercontent.com/13196996/31319228-e9b2ad3e-ac5f-11e7-8e6a-e32a88e26b18.png)

**Comment by Spongman** [comment] 2018-01-07 22:51
maybe. i believe part of the problem is the interaction between `depthMask()` and `clear()`. in #2511 i added a call to `depthMask()` in `background` which should fix that part of this bug. there also may be some z-fighting issues that may be fixed with the processing shader.

**Comment by mlarghydracept** [comment] 2018-01-08 16:19
Closing as I am pretty sure this was fixed with a combination of #2511 and #2515. If the issue is still present when building from the latest master branch just post here and I will reopen.

**Closed by mlarghydracept** 2018-01-08 16:19 UTC
Labels: area:webgl
