### ISSUE TITLE
Example for createVector() is very confusing.

### ISSUE THREAD

**Issue by hellonearthis** [processing/p5.js#4285] opened 2020-02-14 23:28 UTC
#### Most appropriate sub-area of p5.js?

- [X] Math

#### Feature enhancement details:
The example used to explain the [createVector()](https://p5js.org/reference/#/p5/createVector)  is confusing and needs another simpler example that creates a vector using x y x  like the example in [p5.vector ](https://p5js.org/reference/#/p5.Vector)

**Comment by aajaggi** [comment] 2020-02-16 15:01
Hey @hellonearthis  can I work on this?

**Comment by stalgiag** [comment] 2020-02-17 20:18
Good catch @hellonearthis ! The WebGL example is missing a call to a suitable material so you can't see what is happening. But more importantly, I think this doesn't need to be GL at all.

You are welcome to work on it @aajaggi . I would follow @hellonearthis 's advice and make this a simple example similar (but not identical) t[o the class example](https://p5js.org/reference/#/p5.Vector). Thanks!

**Comment by devashish1099** [comment] 2020-02-24 22:33
@stalgiag  can i work on this issue

**Comment by stalgiag** [comment] 2020-02-25 02:16
@devashish1099 when there is already someone assigned to an issue it is best to give them a chance to work on it. If there has been no activity from @aajaggi after 1 month, then you should @ them directly to ask whether they would still like to work on the issue.

**Comment by DivyamAhuja** [comment] 2020-02-27 16:20
@stalgiag Am beginner to this stuff...so to test this out I updated it with code provided in #4301 .So can I initiate a pull request

**Comment by stalgiag** [comment] 2020-02-27 17:20
@DivyamAhuja as I said above, if someone is assigned to an issue then it is important to give them a chance to complete the task. @aajaggi is assigned to the issue. If after 1 month, @aajaggi has not made any work on the task, you can @ them to check to see if they still want to work on the issue.

**Comment by hellonearthis** [comment] 2020-02-28 03:22
Anyone should be aloud to work on this and the best result should be
accepted into the repository.
It seems odd to discourage someone from trying.

**Comment by stalgiag** [comment] 2020-02-28 03:50
@hellonearthis the goal for the repo is to cultivate a culture that makes people feel comfortable trying to submit contributions when they haven't already. If someone asked to give the issue a try and was assigned through first-come-first-serve then it makes sense to give them a chance to work on it without other pull requests overriding them or intimidating them.

In critical situations, it might make sense to let anyone submit a solution quickly and accept the best one but in cases like this where the issue isn't critical, is beginner-friendly, and a new contributor asked to try it out, we should give them a generous window with no pressure so they feel comfortable trying to submit something. The goal is to avoid creating a competitive atmosphere on the repo. The repo is itself an opportunity for learning.

If you feel that this isn't a good approach and would like to suggest something different, we are discussing similar topics over on #4321

**Comment by fenilgandhi** [comment] 2020-03-14 00:42
@aajaggi, @hellonearthis Is anyone even working on this ?

**Comment by DivyamAhuja** [comment] 2020-03-14 04:10
@fenilgandhi well I was working on this one but as @aajaggi was assigned so I decided to wait for a month and see

**Comment by fenilgandhi** [comment] 2020-03-14 21:35
Cool, @DivyamAhuja since you were already working on it, you do it.

**Comment by stalgiag** [comment] 2020-03-14 22:34
Thanks for the patience everyone!

@aajaggi it has been roughly a month. Let me know if you want to keep working on this. No pressure! If we don't hear from you in 24 hours then we will let @DivyamAhuja give it a try. Feel free to @ me with any questions.

**Closed** 2020-03-16 19:35 UTC
Labels: enhancement, help wanted
