### ISSUE TITLE
difference in text and syntax for arguments for rect() in the reference

### ISSUE THREAD

**Issue by Tyson1950** [processing/p5.js#3259] opened 2018-10-07 03:23 UTC
Hi, Not sure if this is the appropriate place and I may be wrong because this is the first night I started learning JavaScript but I noticed in the reference area for p5.js for the rect() function there is a discrepancy between the wording in the text and the description in syntax. The text description says the 5th argument is top right corner but under syntax, it lists the 5th argument as [tl] and the 6th argument as [tr]

**Comment by LanceFun** [comment] 2018-10-07 14:10
Duplicate of #2879

**Comment by lmccart** [comment] 2018-10-07 15:16
thanks. just updated the reference, should be correct now: https://p5js.org/reference/#/p5/rect

**Closed by lmccart** 2018-10-07 15:16 UTC
