### ISSUE TITLE
ambientMaterial() turns off specular material

### ISSUE THREAD

**Issue by sanketsingh24** [processing/p5.js#3782] opened 2019-06-01 22:22 UTC
#### Nature of issue?
- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?
- [x] WebGL

Currently, when using `ambientMaterial()`, [`specularMaterial()` is turned off](https://github.com/processing/p5.js/blob/7208bc63e91e9da88075ac0193b8f8d06973bc57/src/webgl/material.js#L615). I wanted to know the logic behind this code, and is it necessary for specular properties to be turned off to render ambient material, as I think is not the case with Processing. I wanted to know about this because I will be working closely with this part of code.

Tagging @karenpeng because she was the author, @stalgiag @aferriss

**Comment by stalgiag** [comment] 2019-09-20 09:37
Hi @sanketsingh24 I am going to close this as it seems to be a duplicate of #3806 . The difficulties with changing this behavior that are discussed in that issue are relevant here as well, so we can track the problem and continue the discussion there. Thanks!

**Closed by stalgiag** 2019-09-20 09:37 UTC
Labels: area:webgl
