### ISSUE TITLE
saveFrames() if called one after the other will combine and mix up the frames from both into one array

### ISSUE THREAD

**Issue by akshay-99** [processing/p5.js#4456] opened 2020-04-03 02:57 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.0.0
- Web browser and version:  Chrome 79.0.3945.88
- Operating System: Ubuntu 18.04
- Steps to reproduce this:

If I use the following code
```js
function draw() {
 background(mouseX);
 }

 function mousePressed() {
   saveFrames('aaa', 'png', 1, 25, data => {
     print(data);
   });
  saveFrames('bbb', 'jpg', 1, 25, data => {
     print(data);
   });
 }
```
I would expect that since there are two different callbacks, each would get an array of roughly the same size with one callback getting frames with all filenames of aaa and all ext of type png
```js
{
  imageData: "data:image/octet-stream;base64,iVBO....", 
  filename: "aaa0", 
  ext: "png"
}
```
The other should get frames with all filenames of bbb and ext of type jpg
```js
 {
  imageData: "data:image/octet-stream;base64,/9j/4AAQSkZ...", 
  filename: "bbb0", 
  ext: "jpg"
}
```

However in actuality, one array has size 43 and the other has size 0
![image](https://user-images.githubusercontent.com/38867671/78319061-f3393680-7583-11ea-8e66-5d3dba01142c.png)

Moreover the contents that should be passed to two different callbacks is merged into the larger array and passed to just one callback
![image](https://user-images.githubusercontent.com/38867671/78319318-8b372000-7584-11ea-8e21-1b47b8232be9.png)

Check here https://editor.p5js.org/akshay.padte/sketches/8_58URlX7
I don't think this is the expected behaviour here.

**Comment by limzykenneth** [comment] 2020-04-03 17:26
For me this is "expected behaviour", in quotes because it's not necessarily "desired behaviour". The reason I can see this happening is because of the async nature of the callbacks, when calling `saveFrame()` twice on the same instance, it create a race condition in which case the function run twice before the first callback is called thus the duplicate data, then the array is likely flushed resulting in an empty array when the second callback is called.

I'm not sure how to fix this or even if it should be fixed since this is the expected behaviour of async functions.

**Comment by akshay-99** [comment] 2020-04-03 21:26
Yes to me it seems that the problem is due to the fact that `frames` array is "global" [here](https://github.com/processing/p5.js/blob/master/src/image/image.js#L20) in the image module. A race condition wouldn't arise if the two calls were not modifying a shared array. If I move the declaration of `frames` inside `saveFrames()` and just have `makeFrame` return the frame instead of pushing it directly, I am able to fix this issue. 

![image](https://user-images.githubusercontent.com/38867671/78405509-4069e680-761e-11ea-8035-d05108030665.png)

Both calls of `saveFrames()` still run asynchronously, but now they would not interfere with each other. 
I encountered the issue while writing tests for `saveFrames` and I didn't directly patch it then because I am unsure as to why `frames` has been kept global. If keeping it global is not required, I will patch it and move ahead with the tests. Otherwise, I will think of a workaround for testing it.

**Comment by limzykenneth** [comment] 2020-04-03 21:53
Does `frame` still accumulate if it is defined locally in `saveFrames()`? Or does it need to be attached to the instance perhaps?

**Comment by akshay-99** [comment] 2020-04-03 22:20
The array is still populated, this time correctly and passed to the callbacks.
![image](https://user-images.githubusercontent.com/38867671/78409312-fa655080-7626-11ea-93f0-7ec7a742f2f1.png)

I have simply changed the code as so
```js
  let frames = [];
  const cnv = this._curElement.elt;
  const frameFactory = setInterval(() => {
    frames.push(makeFrame(fName + count, ext, cnv));
    count++;
  }, 1000 / fps);
```
and used a `return myFrame`  at the end of `makeFrame` instead of pushing it there itself.

It wasn't attached to the p5 instance as far as I could see and since it was declared with `let`, only the functions within the image.js file could use it. I went through the code and saw the only two functions that used the globally declared frames array were `saveFrames` and `makeFrame`. The way we get the image data is via `cnv.toDataURL(mimeType);` and this doesn't depend on frames being global or local.

**Comment by akshay-99** [comment] 2020-04-03 22:53
I changed the sketch to add color to the background to make it easier to distinguish and downloaded the images by removing the callback to make sure they were proper. It appears to be running as expected
| number | aaa |  bbb |
|:---------- | ------------- |:-------------:|
| 0 |![aaa0](https://user-images.githubusercontent.com/38867671/78410630-8a58c980-762a-11ea-9917-79ff11d2b496.png) | ![bbb0](https://user-images.githubusercontent.com/38867671/78410674-a78d9800-762a-11ea-8f96-738743e108c2.jpg)
| 1 | ![aaa1](https://user-images.githubusercontent.com/38867671/78410629-89c03300-762a-11ea-80e1-f623f9d23c6a.png) | ![bbb1](https://user-images.githubusercontent.com/38867671/78410672-a78d9800-762a-11ea-9e8f-943f96fd9a7f.jpg)
| 2 | ![aaa2](https://user-images.githubusercontent.com/38867671/78410628-89279c80-762a-11ea-9579-f97a93e21363.png) | ![bbb2](https://user-images.githubusercontent.com/38867671/78410670-a65c6b00-762a-11ea-8b0c-318c0ed39493.jpg)

**Comment by akshay-99** [comment] 2020-04-05 22:52
@limzykenneth should I go ahead with redefining frames as local to the function?

**Comment by limzykenneth** [comment] 2020-04-06 12:42
@akshay-99 Go ahead, do make sure to take note of existing behaviour and see that the fix doesn't change it. Thanks.

**Closed** 2020-05-04 05:59 UTC
Labels: bug
