### ISSUE TITLE
date/time/hour example

### ISSUE THREAD

**Issue by tchoi8** [processing/p5.js#1375] opened 2016-04-23 21:23 UTC
Hi there

I'm making a tutorial inspired by On Kawara's Date paintings.
![image](https://cloud.githubusercontent.com/assets/683107/14764057/da79a3cc-0977-11e6-939b-b7f937909cc7.png)

I'm using a clock/ calendar http://p5js.org/reference/#/p5/hour and http://p5js.org/reference/#/p5/day  and other time inputs.

When I try  
var day = day();
I get an error. "Uncaught TypeError: undefined is not a function" 
Also same with month = month(); and other related references for time inputs. 
 ![image](https://cloud.githubusercontent.com/assets/683107/14764048/8fd78726-0977-11e6-8f36-8ba555193d3d.png)

but it works when I use
var d = day();

![image](https://cloud.githubusercontent.com/assets/683107/14764052/bcfca22c-0977-11e6-8c37-0da3eff04608.png)

I wonder if I'm missing something, or not following the reference correctly. 
 

Thanks!

**Comment by lmccart** [comment] 2016-04-23 21:31
Ah yes, the problem is that when you declare a variable with the same name as a p5 function, it overwrites the function, and p5 no longer knows what to do when you call it. That's why `var d = day()` works, because in this case no overwriting is happening. This is the way that JavaScript works, it doesn't throw any warning, which can be confusing. Actually, @toolness has been working on adding functionality to p5 to warn you if you try to name a variable the same things as a p5 function. This will be in the next release. :)

**Comment by tchoi8** [comment] 2016-04-23 21:36
Cool. How about editing the time and date input references like http://p5js.org/reference/#/p5/day to var d= day ()?

**Comment by lmccart** [comment] 2016-04-23 21:38
ooh yeah terrible typo! will fix, thank you.

**Closed** 2016-04-23 21:40 UTC
