### ISSUE TITLE
random(low, high) can return high

### ISSUE THREAD

**Issue by atgeflu** [processing/p5.js#1495] opened 2016-06-30 19:58 UTC
On the Processing.js github an [issue](https://github.com/processing-js/processing-js/issues/244) was opened, that `random(low,high)` can return `high `when the interval `low .. high` is sufficiently small.

I thought that this might only be a Processing.js issue, but Processing and P5.js seem to be affected as well. I've already opened a ticket for Processing as well.

I guess this use case should be rather rare, but I thought you might still like to know about this issue.

Code example:
```

function setup() 
{
  noLoop();
  
  var answer;
  var found1 = 0;
  var myLow = 0.99999999999;
  var trials = 10000000;
  for (var i = 0; i < trials; i++) {
    answer = random(myLow, 1);
    if (answer >= 1) {
      found1++;
    }
  }
  println("highs found: " + (found1) + " (correct): " + (trials-(found1)));
} 
```

**Comment by limzykenneth** [comment] 2016-06-30 21:54
@atgeflu That really isn't something that can be solved, even more more low level language like C++. The reason simply put is floating point precision error. By their nature, floating point numbers don't have an infinite amount of decimal (it will max out around 17 places more or less), that means that if there isn't any more precision to generate a unique random number, the computer simply round it up, which is why the `high` here occurs basically all the time.

See better explanation in this [video](https://www.youtube.com/watch?v=PZRI1IfStY0)

**Comment by nok** [comment] 2016-07-01 11:14
This is the best part of the referenced video: https://www.youtube.com/watch?v=PZRI1IfStY0&feature=youtu.be&t=426 👍 

By the way in JavaScript are more popular rounding errors, e.g.:

```
0.1 + 0.2 == 0.3
=> false (0.30000000000000004)
```

But it also depends on your local system architecture (32bit/64bit) and used software. For me, the following oneliner works without errors:

```
(function(){var found = 0; for (var i = 0; i < 100000000; i++) { if (Math.random(0.999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999, 1) >= 1) { found++; } } return found; })();
=> 0
```

**Comment by atgeflu** [comment] 2016-07-01 11:30
@limzykenneth Thanks a lot for pointing this out and for the link to the video on floating point numbers. 

In light of this, I guess it might make sense to close the issue. 

Maybe it would be a good idea to add some information to the current reference on the random() function about the possibility that `high` might be returned in rare cases due to the way floating point arithmetic works (perhaps with a link to aforementioned video). That way if someone runs into this again in the future a check of the reference would suffice for them to see why the issue happens.

**Comment by limzykenneth** [comment] 2016-07-01 23:59
@nok +1 on that bit of the video, that's also why opengl uses float by default and not double.

@atgeflu I think we might have discussed this before on another issue about floating point numbers with a link to that video as well, I think it might have ended up as a wiki or not done yet...I'll do some digging when I have the time. We might need to think about where to put this information as a lot of the functionality in p5.js deals with floating point numbers and adding this info to all the cases might seem too much of a duplication and complicates the docs unnecessarily.

**Comment by lmccart** [comment] 2016-07-04 09:31
maybe the [faq page](https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions) could be a good spot for this?

**Comment by atgeflu** [comment] 2016-07-04 18:11
@limzykenneth I agree that adding the floating point info to all cases might complicate the docs unnecessarily. It's pretty useful info, but it's hard to say where the info would fit best / be most useful.

@lmccart I guess the faq might be a good place.

**Comment by lmccart** [comment] 2016-07-05 06:50
@atgeflu sounds good. do you feel clear enough on the issue and the info to add it to the faq page? you should be able to edit it directly if you click the "edit" button. I'm happy to review if you'd like. or I can make the update if you'd prefer.

**Comment by atgeflu** [comment] 2016-07-05 19:59
@lmccart I think I might be able to write something for the faq page, though I probably won't get around till the weekend if that's all right with you.

**Comment by lgto4** [comment] 2016-07-10 02:17
While the problem is rooted in the finite precision of floating point numbers, declaring it intractable is a mistake.  If the interval `[a .. b)` is non-zero then clearly we can generate numbers in that interval.  The worst case is when `a` and `b` are two consecutive floating-point numbers. In that case the only viable number is `a`.

Assuming `Math.random` reliably returns a random number in the interval` [0 .. 1)`, then we compute a random number `r` in the interval `[a .. b)` as `r = a + Math.random() * (b - a)` .  In the worst case scenario, `Math.random()` values greater than (and maybe equal to) 0.5 will result in `r` being `b`.  That is, 50% of the time we expect the answer to be wrong.

What happens if `a`, `z`, and `b` are three consecutive floating-point numbers?  Then the answer is wrong only 25% of the time.  And so it goes.  For any non-zero interval `[a .. b)` there exist values returned by `Math.random()` in the interval `(m .. 1)` that cause the wrong answer.  (That interval may be zero.)

The solution then is to ignore `Math.random()` values that are greater than `m`, and to simply ask for another random value.  I have no idea how to compute `m` for any given `a` and `b`.  None-the-less, it's trivial to detect when `Math.random()` delivered such a number.  That's when `a + Math.random() * (b - a)` equals `b`.

This analysis is independent of the number of bits in a floating number and is independent from humans' (mis)conceptions of floating point numbers.

**Comment by limzykenneth** [comment] 2016-07-10 18:10
@lgto4 That's a very interesting point. Thanks for the input! Though I feel it has less to do with floating point precision but more with rounding errors, I totally agree if `random(min, max)` is to map closely to `Math.random()` then reasonably it should only return in the range `[min, max)`.

Implementation wise, a check for `a + Math.random() * (b - a) == b` should not be too big of a problem, except for when `a` and `b` are close enough to cause problem OP had, in that case, the RNG will only come up with the same (max) value every time (ie. `b` everytime) which will obviously go into an infinite recursion. To demonstate why:

Edited from [`random.js`](https://github.com/processing/p5.js/blob/master/src/math/random.js#L125)
```javascript
var rand = Math.random();

if (min > max) {
  var tmp = min;
  min = max;
  max = tmp;
}

return rand * (max-min) + min;
```

The key line here is `rand * (max-min) + min;`. What we want is to check is if the result is equals to `max`, it will call the RNG again. However, if `min` and `max` is close enough to cause floating point precision problem, `1 == 0.999999999999999999999` or `max == min` will be true and `max - min == 0` so `rand * (max-min) + min == min == max` as well. In such a case, the number is so precise the computer doesn't differentiate between `min` and `max` because to it, they are the same number, ie. it is the same  as doing `1 + Math.random() * (1 - 1)`. We can ask the function in this case to return `min` but same problem, it will return what seemed to be `max` because they are "equal".

**Comment by lgto4** [comment] 2016-07-10 21:00
@limzykenneth You are welcome.

I do not know what OP or RNG are.  The notion that `1` is or is not  `0.999999999999999999999` is of no concern.  When two arguments `a` and `b` are passed to the function, either the interval `[a .. b)` is non-zero or `a==b`.

If the interval `[a .. b)` is non-zero then there is no chance of infinite retries.  Clearly the code must catch the degenerate case of when `a==b`.  Historically, the function returned `a` (rather than, say, throwing an error).

Swapping arguments is a mistake since the interval [a .. b) is not the same as the interval [b .. a).  It is also unnecessary.  The code historically functioned equally well for increasing intervals and decreasing intervals, despite an unfortunate choice of variable names.  My proposed fix also is insensitive to the direction of the interval.

**Comment by limzykenneth** [comment] 2016-07-10 22:02
Sorry, OP means original poster ie @atgeflu and RNG is random number generator which is `Math.random()` or `random()` in this case.

The problem is say you have `a` which is `0.999999999999999999999` and `b` which is `1` and we know it can return `a` which is `0.999999999999999999999` but it is not possible to represent `0.999999999999999999999` in javascript so what it will do is return `1` instead. There isn't a problem with returning `a` just that it will look like it returned `b` (it won't throw an error). We know there is of course a random number between `0.999999999999999999999` and `1` but the problem is that it is not representable (thus don't exist) in javascript (and most other floating point implementation).

Something can be done about swapping there. I agree.

**Comment by lgto4** [comment] 2016-07-10 22:41
If `0.999999999999999999999` cannot be represented in Javascript then how is it ever be passed as an argument to the function?  The function assumes its arguments are floating point numbers; they are not some strings that a programmer typed in his source code.

I believe that attempting to discuss the issues using base ten notions muddies the water.  ...not that I am proposing any other base.   Perhaps a coded example of the issue would be instructive?

**Comment by lmccart** [comment] 2016-07-11 00:01
very interesting discussion. I wonder if this case is sort of an edge one and perhaps beyond the scope of this library. I am in favor of adding some notes to the faq as @atgeflu has proposed, and leaving it at that.

**Comment by limzykenneth** [comment] 2016-07-11 14:02
@lgto4 `0.999999999999999999999` cannot be represented doesn't stop anyone from passing it into a function, it will simply be treated as `1` when the javascript engine came across it. To demonstrate:

```javascript
var a = 0.999999999999999999999;
console.log(a); // Will print "1"

// It can also be seen as follows (eval here is just for demonstration)
eval("console.log(0.999999999999999999999)"); // Will print "1" as well
```

To the javascript engine, you are just giving it some strings of numbers to work with, if it cannot represent the strings of number, it will just read it as something it can represent. If you have a program like the following where you generate the number dynamically:

```javascript
var string = "0.9";

for (var i=0; i<20; i++){
  console.log(makeNewNumber());
}

function makeNewNumber(){
  string += "9";
  var number = parseFloat(string);

  return number;
}
```

The result will be:

```
0.99
0.999
0.9999
0.99999
0.999999
0.9999999
0.99999999
0.999999999
0.9999999999
0.99999999999
0.999999999999
0.9999999999999
0.99999999999999
0.999999999999999
0.9999999999999999
1
1
1
1
1
```

I'm actually very interested in the native base2 representation of floating point numbers so I'm doing it anyway 😉 

Javascript's number follows IEEE 754 specifications so I'm using a handy [converter](http://www.h-schmidt.net/FloatConverter/IEEE754.html) to help me. Whether it's 32-bit or 64-bit depends on implementation but for simplicity sake I'll just use 32-bit.

As we can see `1.0` is represented in 32-bit binary as `00111111100000000000000000000000`. To break it down:

```
0 01111111 00000000000000000000000
```
The first bit is the sign(+/-); the next 8 bits minus 127 are the exponent; the next 23 bits is the mantissa or the significant number. To get the number in decimal you follow the equation `sign * 2^exponent * mantissa`. Since you only have a finite number of bits in the mantissa, the largest number that you can represent in 32-bit floating point number in the range [0, 1.0) is `0.99999994` or `0 01111110 11111111111111111111111` in binary. To represent anything in the range (0.99999994, 1.0) you will need extra bits on your mantissa which doesn't exist. That is why it cannot be represented in javascript.

@lmccart The issue with the swap might need fixing although for it to cause a problem is likely to be extremely rare, ie. `random(10, 1)` according to docs it should not return 1 since it should be in the range [10, 1), but by swapping them, there is a very rare chance to get 1 and never 10. I don't think the rest need changing as well.

**Comment by lgto4** [comment] 2016-07-11 14:52
@limzykenneth  If you use 64 bit floating point numbers, then you will have a one-to-correspondence to Javascript's numbers.  Then you can write Javascript code to directly demonstrate issues.  For example
`var a = 0.3;
var b = 0.2 + 0.1;`
You can go on to show that `a` and `b` are not equal and that there are no floating point numbers between `a` and `b`.  That is, `a` and `b` are consecutive floating point numbers.  A visual inspection of the two floating point number will show the same...  By the way, what is the Javascript computed average of `a` and `b`?

**Comment by limzykenneth** [comment] 2016-07-11 15:42
Whether it's 32 or 64 bits doesn't really matter in principle, it's just the precision that is different. 

> You can go on to show that `a` and `b` are not equal and that there are no floating point numbers between `a` and `b`.

Yes we can show all that for some cases, and I think the current code deals with that perfectly, but the problem is still that it isn't possible to represent `0.999999999999999999999` in javascript and it will automatically be cast as `1` thus you cannot show that they are not equal. So when you call a random function like so `random(0.999999999999999999999, 1)` it is the same as `random(1,1)` and it will only return `1`.

Not sure what you meant by computed average of `a` and `b` though...

**Comment by atgeflu** [comment] 2016-07-11 19:49
This is quite an interesting discussion.
I think there might be two main points, one being whether the problem is tractable and the other being whether an implementation (if feasible) is worth it, considering that it's bound to be a rare edge case. 

As an aside, I've seen that in the original processing there was a check included for the rare case that `random(3) = 3`, ie:
```
public final float random(float high) {
    // avoid an infinite loop when 0 or NaN are passed in
    if (high == 0 || high != high) {
      return 0;
    }

    if (internalRandom == null) {
      internalRandom = new Random();
    }

    // for some reason (rounding error?) Math.random() * 3
    // can sometimes return '3' (once in ~30 million tries)
    // so a check was added to avoid the inclusion of 'howbig'
    float value = 0;
    do {
      value = internalRandom.nextFloat() * high;
    } while (value == high);
    return value;
  }
```
but no special check was included for the case that `random(a,b) = b`. 

I think that @lmccart has a point and that implementing a check for the rare cases where  `random(a,b) = b` might be overkill for a library like this. 

I'll happily keep following this discussion though, and if in the end we see that an implementation isn't feasible or that we decide against it, I'll happily add something to the faq.

**Comment by lgto4** [comment] 2016-07-11 20:47
@atgeflu  I haven't figured out how to access Processing source code.  If you have some quick pointers to share, I'd appreciate them.

I (like many others) would be thrilled and  astounded to see a case where `high != high` .  I do not understand how a check for random(a,b) = b can be performed if the function only defines one parameter.

The code and comments essentially speak to the same basic problem that I reported.  Though the implementer may not know why it works (actually why it fails), the solution is identical to my proposal.

While I understand the cost of fixing a bug must be weighed against the likelihood of the bug manifesting itself, I believe that adding one additional compare to make the function do what it purports to do is not onerous.  This in light of counter proposals to document the misbehavior indicates that it ought to be fixed.   Is anybody old enough to remember https://en.wikipedia.org/wiki/Pentium_FDIV_bug ?

**Comment by atgeflu** [comment] 2016-07-11 21:07
@lgto4 I've forked the processing repository which makes it easier to find things in the source code. 

The check for `high != high` is there in case the function is called with NaN for example (as far as I can tell). 

The code snippet was only for the case of calling `random` with one argument, since I thought it was interesting that they had an extra check to ensure `random(b) !== b`.

I only mentioned that there was no special check for the case  `random(a,b) == b` but didn't include the code. So for completeness sake here it is:
```
  public final float random(float low, float high) {
    if (low >= high) return low;
    float diff = high - low;
    return random(diff) + low;
  }
```

**Comment by lgto4** [comment] 2016-07-11 21:29
@limzykenneth Let emphatically agree that `random(0.999999999999999999999, 1)` is the same as `random(1,1)` and it will only return `1`, and that the general invocation of `random(a, a)` should (and does) return only `a`.  I just wish we could agree that when execution begins in the `random` function that it has no way of telling what the programmer did to produce  the arguments.

The bug that I reported was that `random(a, b)` sometimes returns `b`.  Though not explicitly stated, the degenerate case where `a==b` is of no interest.

An example of the bug is when `var a = 0.3; var b = 0.2 + 0.1;`.  The function is in error 50% of the time.  A demo is at https://www.khanacademy.org/computer-programming/random-failure-demo/5127104869302272

**Comment by lgto4** [comment] 2016-07-11 22:18
@artdent Thanks!   I am thrilled and astounded to learn that the test `high != high` is both viable and useful, though its affects could have percolated down through the bottom of the function.

**Comment by artdent** [comment] 2016-07-11 22:20
I think you meant to tag @atgeflu :-).

**Comment by lgto4** [comment] 2016-07-11 22:23
"Oops" said the Texan.

**Comment by lmccart** [comment] 2016-10-12 18:13
thanks for all the thorough discussion. for organizational purposes, I'm going to close this issue as I feel it's an edge case that is not high priority right now, but if anyone would like to submit a PR I'd be happy to review it.

**Closed by lmccart** 2016-10-12 18:13 UTC
