### ISSUE TITLE
translate() doesn't reset in draw() loop

### ISSUE THREAD

**Issue by IgorBabalich** [processing/p5.js#1193] opened 2016-01-04 20:28 UTC
// p5.js v0.4.20 December 11, 2015

      var x = 0;
      var y = 0;
      
      function setup() {
         createCanvas(640, 640);
         background(204);
      }

      function draw() {
         translate(x,y);
         rect(0, 0, 30, 30);

         x += 0.01;
         y += 0.01;
      }

**Comment by lmccart** [comment] 2016-01-05 00:17
thanks! this was just fixed in the new version 0.4.12

**Comment by julsgud** [comment] 2016-02-11 20:48
Same issue over here with v 0.4.22! translate() will only work as expected when used in setup(). Ran into this when adapting [this](http://www.generative-gestaltung.de/P_2_0_01) from the generative gestaltung book.

`
function setup() {
  createCanvas(500, 500);
  translate(width/2, height/2);
}

function draw() {
  // translate(width/2, height/2); not working when used here!
  strokeCap(SQUARE);
  smooth();
  noFill();
  background(255);
  
  var circleResolution = map(mouseY, 0, height, 2, 80);
  var radius = mouseX-width/2 + 0.5;
  var angle = TWO_PI/circleResolution;
  
  strokeWeight(mouseY/20);
  
  beginShape();
  for (var i = 0; i <= circleResolution; i++) {
    var x = cos(angle*i) * radius;
    var y = sin(angle*i) * radius;
    line(0, 0, x, y);
    // vertex(x, y);
  }
  endShape();
}`

**Comment by lmccart** [comment] 2016-02-12 01:06
hm, your angle gave some error, but here is a simplified version i used to test:
```javascript
function setup() {
  createCanvas(500, 500);
  //translate(width/2, height/2);
}

function draw() {
  background(0);
  translate(width/2, height/2);
  ellipse(0, 0, 50, 50);
}
```

I'm using v0.4.22 (downloadable here: http://p5js.org/download/) and it seems to look fine. Can you try running this simple code and see if it works? If not, can you tell me which OS / browser you're using?

**Comment by julsgud** [comment] 2016-02-12 04:08
Thanks for the prompt response! Using the p5 editor v0.5.7, the example you posted using translate() inside draw() does not reset the transformation on every loop. Ellipse runs off canvas!

**Comment by lmccart** [comment] 2016-02-12 04:11
ah, i don't think the library version has been updated in the editor yet. i'll see if we can't get this merged in asap. thanks!

**Comment by pflannery** [comment] 2016-05-30 15:48
@lmccart I have this problem too when using v0.5.0 on Windows 10

```js
function setup() {
  createCanvas(400, 400);
}

function draw() {
  translate(1, 0);
  background(51);
  stroke(255);
  line(0, 0, 0, 100);
}
```

I see the line gradually goes off the screen. If I Push() and Pop() it works as expected.

**Comment by lmccart** [comment] 2016-05-30 15:51
yes, i don't think the library version has been updated in the editor yet. i'll see if I can merged in asap. thanks!

**Comment by pflannery** [comment] 2016-05-30 17:45
@lmccart when you say editor do you mean the p5 editor? because I'm vscode as my editor, serving with python SimpleHTTPServer and previewing on latest chrome.

**Comment by pflannery** [comment] 2016-05-30 20:22
@lmccart it looks like this [line](https://github.com/lmccart/p5.js-release/blob/master/lib/p5.js#L17145) is where the problem is happening. 
But I think this is fixed in the future 0.5.1 release via the #1390 fix. thanks

**Comment by lmccart** [comment] 2016-05-30 21:24
yes, this is correct.

**Comment by limzykenneth** [comment] 2016-05-31 08:20
@lmccart I think @shiffman came across this problem in his recent live stream as well

**Comment by shiffman** [comment] 2016-06-02 13:53
@limzykenneth thanks for this update!

**Comment by lmccart** [comment] 2016-06-03 11:53
ah sorry, I thought I had published a new version with this fix in there! I will be sure to post it in the next few days, apologies for the delay.

**Comment by barisdemiroz** [comment] 2016-08-04 21:41
This bug still exists in version 0.5.2. I think the issue should be reopened.

**Comment by lmccart** [comment] 2016-08-04 21:56
hi, could you please post a snippet of sample code that illustrates the problem? i'm not able to reproduce.

**Comment by barisdemiroz** [comment] 2016-08-04 22:16
Thank you for fast reply. I gathered the code to post here but I checked for the last time and failed to reproduce it. I swear I saw it :) Maybe it is a heisenbug, if it happens again I will try to catch it.

**Comment by barisdemiroz** [comment] 2016-08-05 09:57
Today the bug appeared again and I was able to reproduce it with the following code:

```
var textarea;

function setup() {
	createCanvas(640, 640);

	noLoop();

	textarea = createElement('textarea', '[[0.1,0.2,100,120], [0.15,0.17,80,180]]'); 
	textarea.input(function () {
		redraw();
	});
}


function draw() {
	var sectors = JSON.parse(textarea.value());

	translate(300, 300);
	ellipse(0,0,20);
  	// translate(-300,-300);
}
```

Everytime I change the textarea the circle being drawn is shifted and redrawn resulting in:

[bugimage](http://i.imgur.com/3laFeLi.png)

**Comment by lmccart** [comment] 2016-08-08 05:08
aha got it, should be fixed in the next release with this patch

**Closed** 2016-08-08 05:08 UTC
