### ISSUE TITLE
`orbitControl()` Compatibility with `imageLight()`

### ISSUE THREAD

**Issue by perminder-17** [processing/p5.js#6688] opened 2024-01-02 17:05 UTC
### Increasing Access

The current implementation of `orbitControl()` does not seamlessly work with the `imageLight()` function, resulting in unexpected behavior. When using a 360-degree image and adding a sphere with `imageLight()`, the use of `orbitControl()` does not provide the expected interaction. It appears as though the sphere is static, while only the image responds to `orbitControl()`.

_**However when we use `texture()` we can achieve the possible result but without other functions such as `shininess()`.**_

https://github.com/processing/p5.js/assets/127239756/e9dd23c1-c77c-4a50-80da-760fd6bfee4e

### Most appropriate sub-area of p5.js?

- [X] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

Expected Behavior:
The `orbitControl()` should seamlessly interact with the `imageLight()` function. When a sphere with an `imageLight()` is present, the `orbitControl` should behave as if the image is fully embedded in the sphere. This enhancement would significantly improve user experience, especially when working with 360-degree images.

### After the implementation it should work similar to this.

https://github.com/processing/p5.js/assets/127239756/0db46392-fab2-490c-b8be-80066970dc48

**Comment by perminder-17** [comment] 2024-01-02 17:19
### When we simply rotate the sphere it still shows inconsistency.
https://github.com/processing/p5.js/assets/127239756/aeadf7b0-4cdf-4eb8-a2df-b7a4ab039144

It would be immensely valuable if either the WEBGL stewards or you, @davepagurek , could assist us in pinpointing the location for fixing it. Seeking for your approach how we could implement it.

**Comment by davepagurek** [comment] 2024-01-02 21:13
There are two things going on in the threejs recording:
1. The reflections on objects take the camera angle into account
2. The background image also rotates with the scene

To accomplish (1), we have to apply the rotation of the camera to the normal vector that we pass in here to look up a coordinate on the light texture: https://github.com/processing/p5.js/blob/fe33439ff3d46d59ca97032ec73de7a308508190/src/webgl/shaders/lighting.glsl#L113

To do that, we have to add a new uniform to the shaders, similar to `uNormalMatrix`, which is the inverse transpose of the model view matrix:
https://github.com/processing/p5.js/blob/fe33439ff3d46d59ca97032ec73de7a308508190/src/webgl/p5.Shader.js#L343-L344

The normal matrix is used to update normals based on the current model's transform, which is a product of the camera transform and all the other transformations applied to the current object. For this, we only want the camera transform, so instead of doing the inverse transpose on `uMVMatrix`, we need to do this on the current camera's matrix. In a shader, multiplying a normal by that will apply the camera rotation.

For (2), the easy but imperfect way is to draw a giant textured sphere around everything, and then call `cleatDepth()` afterwards so it doesn't accidentally clip everything. It's imperfect though because it would still apply any position changes from the camera---ideally, the sphere is so large that position changes make no difference. The best way to do this might be to make a new default shader for sphere mapped backgrounds that dimilarly gets its color from `mapTextureToNormal`, but where the initial normal comes from the angle to the camera (`normalize(worldPosition)`) multiplied by the camera normal matrix.

**Comment by inaridarkfox4231** [comment] 2024-01-04 02:38
Since the specification of orbitControl() is not the cause, shouldn't the title be changed?

**Comment by inaridarkfox4231** [comment] 2024-01-05 01:09
up is fixed to (0,1,0), but this may be the cause. Maybe not. It's just a guess.
[here](https://github.com/processing/p5.js/blob/fe33439ff3d46d59ca97032ec73de7a308508190/src/webgl/shaders/imageLightDiffused.frag#L50C32-L50C32)
```glsl
  vec3 irradiance = vec3(0.0);

  vec3 up = vec3(0.0, 1.0, 0.0);

  vec3 right = normalize(cross(up, normal));
  up = normalize(cross(normal, right));
```
I think it is useless to change the specifications of orbitControl() no matter how much you change it. People who want to use it normally will be in trouble. That's the wrong idea.

What is introduced there is Sphere Environment Mapping, right? In my opinion, the specification of that is completely different from imageLight(), but I can't understand why you had to bring it up.

It's essentially just an application of texture mapping. Since it uses normals to determine the texture function arguments, it is completely different from imageLight(), and extremely lightweight. It works fine on my mobile phone as well.

If you want to implement sphere environment mapping, shouldn't you change the title or create a new issue to explain the path to implementation? imageLight() is no longer relevant.

It seems that the image used for imageLight() can be a general image and does not need to be a spherical map. It's something completely different feature.
[refer this](https://github.com/processing/p5.js/pull/6255#issuecomment-1786854321)

**Comment by davepagurek** [comment] 2024-01-05 03:11
imageLight() is pretty similar to sphere mapped normals---thats what's going on for most of it. The additional thing that imageLight does is it precalculates and caches some blurred versions of the texture the first time you use it, and then uses those in the sphere mapped texture lookup based on the shininess of the material rather than using the texture directly.

I may have misinterpreted the inconsistency @perminder-17 mentioned. I was thinking you meant how in the threejs recording, the reflections change as you change the camera angle. Other lights in p5 do this, but the imageLight reflections currently don't, so that's potentially something we might want to change for the sake of consistency.

But what @inaridarkfox4231 brought up, which is a good point, is that you can use non sphere map images as a light source. This looks ok at a fixed camera angle, but non sphere map images would have a visible seam if the reflections changed with the camera. I'm not sure how distracting that would be, it's potentially a reason to not be consistent with the camera affecting the light positions.

**Comment by inaridarkfox4231** [comment] 2024-01-05 15:56
To me, the Three.js video introduced above looks like just a sphere mapping. I can only see it that way.
It's not lighting, it's just drawing using a sphere map. It's just a variant of texture mapping.

Was imageLight() just a variant of texture mapping? It doesn't really seem that way though. If so, there is no need for complicated calculations. Just give us more options for how to process textures inside the shader and you're done.

There is no need to prepare a process to process the texture material in advance (I can't understand this process, sorry). Just calculate a variable that reads the texture from the transformed normal vector.

However, the current p5.js does not support cubemaps, so we may need to prepare to support it.

That video is cube mapping, right? I have the same one too. It is very similar to what was on the webgpu reference site.
[env mapping test](https://openprocessing.org/sketch/1982658)

https://github.com/processing/p5.js/assets/39549290/dc5c977b-ea06-4b65-816e-d482ec010131

cubemap: [https://github.com/webgpu/webgpu-samples/tree/main/public/assets/img/cubemap](https://github.com/webgpu/webgpu-samples/tree/main/public/assets/img/cubemap)

If this video looks rich, it's not because of the lighting. It's simply because it uses a beautiful cube map. You're probably misunderstanding something.

In the first place, as I wrote above, imageLight() requires too much calculation and my mobile phone crashes. On the other hand, sphere mapping is just a variant of texture drawing, so it is lightweight. It works fine.

Will imageLight() be able to perform cube mapping in the future? If that happens, that would be amazing. Wonderful. I'm rooting for you. that's all.

**Comment by davepagurek** [comment] 2024-01-05 19:21
@perminder-17 it would maybe be helpful to clarify what aspect of the threejs video you were referring to in your issue so that we can continue talking about what addressing it might involve.

The rest of this comment is just adding some context on what `imageLight` is doing and future directions one could take it.

<details>
<summary>
`imageLight()` explanation
</summary>

The preprocessing is to compute a few different sphere map textures at varying levels of roughness so that `shininess()` affects the reflected values:

https://github.com/processing/p5.js/assets/5315059/ee6d03e4-7e81-426e-8e15-bd688d06a126

The other extra bit that happens that is different from pure reflection mapping is that it combined two roughness levels for diffuse and specular light, to parallel the lighting pipeline for things like point lights.

> Will imageLight() be able to perform cube mapping in the future? If that happens, that would be amazing. Wonderful. I'm rooting for you. that's all.

A simplified cube mapping experience would be a good feature, and would be able to use a large chunk of the lighting code that `imageLight` uses! As for supporting cube maps as opposed to equirectangular textures, some support is starting to be added in https://github.com/processing/p5.js/pull/6665.

> imageLight() requires too much calculation and my mobile phone crashes.

https://github.com/processing/p5.js/pull/6613 was also merged recently to make progress on this. I haven't debugged too much further, but we're open to optimizing the process more.
</details>

**Comment by perminder-17** [comment] 2024-01-05 20:34
I apologize for the confusion @davepagurek . While I was exploring its functionality in three.js, I discovered a feature similar to `orbitcontrol`. Essentially, when you rotate the image, the reflections on the sphere dynamically adjust. My objective with this issue is precisely that—I aim to have the reflections on the sphere change in sync with the rotation of the image.

**Basically I need the reflections on objects take the camera angle into account.** 

### Currently it's something like

https://github.com/processing/p5.js/assets/127239756/d787b7ce-d2ad-4c5c-8da0-8ccbf4a1e3e4

### But when the reflections on object take camera angle into account


https://github.com/processing/p5.js/assets/127239756/e563c5af-f300-41de-990e-19d96615e85c


https://github.com/processing/p5.js/assets/127239756/63c95348-de97-4c2c-a4a4-507f13a369a1

**We can take a look and adjust the camera more correctly**

@davepagurek I am unsure if this seems to you a bug or not. If not I will close the issue as you tell. I am not sure about `box()` and `torus()`. `Sphere()` is the one I am working on.

**Comment by davepagurek** [comment] 2024-01-05 21:08
got it! In that case, I believe this section of an earlier comment is the bit that's relevant:



> To accomplish (1), we have to apply the rotation of the camera to the normal vector that we pass in here to look up a coordinate on the light texture:
> 
> https://github.com/processing/p5.js/blob/fe33439ff3d46d59ca97032ec73de7a308508190/src/webgl/shaders/lighting.glsl#L113
> To do that, we have to add a new uniform to the shaders, similar to `uNormalMatrix`, which is the inverse transpose of the model view matrix:
https://github.com/processing/p5.js/blob/fe33439ff3d46d59ca97032ec73de7a308508190/src/webgl/p5.Shader.js#L343-L344
> 
> The normal matrix is used to update normals based on the current model's transform, which is a product of the camera transform and all the other transformations applied to the current object. For this, we only want the camera transform, so instead of doing the inverse transpose on `uMVMatrix`, we need to do this on the current camera's matrix. In a shader, multiplying a normal by that will apply the camera rotation.

**Comment by perminder-17** [comment] 2024-01-05 21:11
> got it! In that case, I believe this section of an earlier comment is the bit that's relevant:
> 
> > To accomplish (1), we have to apply the rotation of the camera to the normal vector that we pass in here to look up a coordinate on the light texture:
> > https://github.com/processing/p5.js/blob/fe33439ff3d46d59ca97032ec73de7a308508190/src/webgl/shaders/lighting.glsl#L113
> > 
> > To do that, we have to add a new uniform to the shaders, similar to `uNormalMatrix`, which is the inverse transpose of the model view matrix:
> > https://github.com/processing/p5.js/blob/fe33439ff3d46d59ca97032ec73de7a308508190/src/webgl/p5.Shader.js#L343-L344
> > 
> > The normal matrix is used to update normals based on the current model's transform, which is a product of the camera transform and all the other transformations applied to the current object. For this, we only want the camera transform, so instead of doing the inverse transpose on `uMVMatrix`, we need to do this on the current camera's matrix. In a shader, multiplying a normal by that will apply the camera rotation.
> 
> Is that similar to the technique you were using to generate the second and third video? And in those videos, is there anything remaining that you think you would need to fix to get the desired behaviour you're after?

Yess... I am going with the same technique. Do you think I should raise a PR? Does the videos looks good to you?

**Comment by davepagurek** [comment] 2024-01-05 21:13
> Yess... I am going with the same technique. Do you think I should raise a PR? Does the videos looks good to you?

I think it's looking close to what I would expect, although it would be helpful to see how it looks with an equirectangular input image so we can make sure the seams and stretching we see is just due to the input image.

**Comment by inaridarkfox4231** [comment] 2024-01-09 01:18
To facilitate discussion, I put a link to the Three.js sample mentioned at the beginning.
[webgl_materials_envmaps](https://threejs.org/examples/#webgl_materials_envmaps)
Isn't it basic etiquette to include a link when quoting a video?

Aside from that...

I created something similar to the sample by modifying the p5.js shader, so please use it as a reference.

[p5_envMapping](https://editor.p5js.org/dark_fox/sketches/TddBB19GO)
```js
// texture source.
// https://noemotionhdrs.net/hdrday.html

let envMap;
let forestMap;

let myShader;

function preload(){
  envMap = loadImage("https://inaridarkfox4231.github.io/assets/sphereMaps/DAY_H_06_07.png");
  forestMap = loadImage("https://inaridarkfox4231.github.io/assets/season/summer_small.png");
}

function setup() {
  createCanvas(640, 640, WEBGL);
  pixelDensity(1);

  // Generate lightingShader
  lights();
  sphere(1);
  clear();

  // get shader.
  const sh = this._renderer._defaultLightShader;
  // Check the contents
  //console.log(sh._vertSrc);
  //console.log(sh._fragSrc);

  // Modify the content using replace()

  let vert = sh._vertSrc;
  vert = vert.replace("uniform mat3 uNormalMatrix;", `
    uniform mat3 uNormalMatrix;
    uniform mat3 uInvCameraMatrix;
  `);
  // LocalNormal is used for sphere mapping.
  // GlobalNormal and GlobalRay are used for environment mapping.
  vert = vert.replace("OUT vec3 vNormal;", `
    OUT vec3 vNormal;
    OUT vec3 vLocalNormal;
    OUT vec3 vGlobalNormal;
    OUT vec3 vGlobalRay; // global eye -> global position
  `);

  vert = vert.replace("void main(void) {", `
    void main(void) {
      vLocalNormal = aNormal;
  `);
  vert = vert.replace("vNormal = uNormalMatrix * aNormal;", `
    vNormal = uNormalMatrix * aNormal;
    vGlobalNormal = uInvCameraMatrix * vNormal;
    vGlobalRay = uInvCameraMatrix * vViewPosition;
  `);

  let frag = sh._fragSrc;
  frag = frag.replace("uniform float uShininess;", `
    uniform float uShininess;
    uniform bool uApplyReflection;
  `);

  frag = frag.replace("IN vec3 vNormal;", `
    IN vec3 vNormal;
    IN vec3 vLocalNormal;
    IN vec3 vGlobalNormal;
    IN vec3 vGlobalRay;
  `);
  // newTexColorにマッピングの結果を格納します
  frag = frag.replace("void main(void) {", `
    void main(void) {
      vec4 newTexColor;
      vec3 n = normalize(vLocalNormal);
      if (uApplyReflection) {
        n = reflect(vGlobalRay, normalize(vGlobalNormal));
      }
      n = normalize(n);
      vec2 suv;
      suv.y = 0.5 + 0.5 * n.y;
      suv.x = atan(-n.z, n.x) / 6.28318 + 0.5;
      newTexColor = texture(uSampler, suv);
  `);
  // change textureColor to newTexColor.
  frag = frag.replace("TEXTURE(uSampler, vTexCoord)", `newTexColor`);

  // create shader
  myShader = createShader(vert, frag);
  shader(myShader);

  noStroke();

  camera(0, 0, 320*sqrt(3), 0, 0, 0, 0, 1, 0);
  perspective(PI/3, 1, 30, 6000);
}

function draw() {
  orbitControl();

  clear();
  lights();
  specularMaterial(128);

  const cameraMat = this._renderer._curCamera.cameraMatrix.copy();
  const invMat = new p5.Matrix().invert(cameraMat);
  const invMat3x3 = invMat.createSubMatrix3x3();
  myShader.setUniform("uInvCameraMatrix", invMat3x3.mat3);

  myShader.setUniform("uApplyReflection", true);
  texture(envMap);
  sphere(60, 48);
  push();
  rotateY(frameCount*TAU/120);
  rotateX(frameCount*TAU/240);
  torus(120, 44, 48);
  pop();
  myShader.setUniform("uApplyReflection", false);

  // background sphere.
  noLights();
  sphere(3000);
}
```

https://github.com/processing/p5.js/assets/39549290/3536e7ad-a4f3-4eeb-a716-35e227481739

We prepared a global normal vector by using the inverse of the camera matrix. By using this and a vector that takes into account the position of the eye, a reflection-like effect is achieved. It's probably similar to Equirectanglar in the video I mentioned earlier.

Of course it's not lighting or anything. It's just a variant of texture drawing.
I'm not asking to implement this or anything like that. This is just a reference. I think the more reference materials, the better.

There are no bugs in orbitControl(). That's all I want to say.

**Comment by inaridarkfox4231** [comment] 2024-01-09 01:22
>Is that similar to the technique you were using to generate the second and third video? And in those videos, is there anything remaining that you think you would need to fix to get the desired behaviour you're after?

>Yess... I am going with the same technique. Do you think I should raise a PR? Does the videos looks good to you?

Even if it's something simple, shouldn't you just post the source code or post a link?
I can't help but wonder why they don't do this, since doing so would make discussions easier and save time.
It looks like you're wasting your time on unnecessary things.

**Comment by inaridarkfox4231** [comment] 2024-01-09 11:59
I haven't read it properly yet, so I don't know the details, but if you're thinking about a function called imageLight(), I think this sample is closer.
[webgl_materials_envmaps_exr](https://threejs.org/examples/#webgl_materials_envmaps_exr)

https://github.com/processing/p5.js/assets/39549290/c5454006-c4b1-4441-bd12-2fc50d2e4faa

Then, I realized that the contents executed in the script called PMREMGenerator used in it were very similar to the contents of imageLight().
[PMREMGenerator.js](https://github.com/mrdoob/three.js/blob/master/src/extras/PMREMGenerator.js)

I'll also include this for reference. By the way, this example also worked without any problems on my mobile phone. I feel like p5 is probably doing unnecessarily heavy calculations. This is also just speculation.

**Closed** 2024-01-19 01:23 UTC
Labels: Enhancement, Area:WebGL, Area:Accessibility
