### ISSUE TITLE
Examples of square() not showing up properly in the references

### ISSUE THREAD

**Issue by mattfan00** [processing/p5.js#4452] opened 2020-04-02 02:27 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ x] Other (specify if possible) Reference not displaying correctly

#### Details about the bug:

- p5.js version: Bug occurring on the website
- Web browser and version: Chrome 80.0.3987.149
- Operating System: macOS 10.13.6
- Steps to reproduce this: 

This is the link that the bug is on: https://p5js.org/reference/#/p5/square 
This is a screenshot of what it looks like on my screen:

![image](https://user-images.githubusercontent.com/30060256/78204439-82046100-7467-11ea-9868-e232037ef22f.png)

For some reason, the squares generated are flattened out whenever you try to add some sort of rounded corner. The correct behavior is shown in this screenshot, which is taken when the same code is running on the p5 web editor: 

![image](https://user-images.githubusercontent.com/30060256/78204559-d3aceb80-7467-11ea-99fb-2c543ca91b7f.png)

So the code works, but for some reason the reference isn't generating the correct image

**Comment by maxdevjs** [comment] 2020-04-02 07:10
Note: 

- seems to me that the cause is the interpretation of the `top-left` (first) argument
- with a corner radius value greater than the side size, the generated squares acquire an oblong (`y` growing) shape

**Comment by limzykenneth** [comment] 2020-04-02 10:47
This is a bug present in `1.0.0`, the editor is using `0.10.2` so it doesn't show up there. This is fixed in #4346 and will be included in the next release.

**Closed by limzykenneth** 2020-04-02 10:47 UTC
Labels: bug
