### ISSUE TITLE
[WEBGL + WEBGL] Uncaught TypeError ... data.setModified is not a function at p5.Texture.update

### ISSUE THREAD

**Issue by diwi** [processing/p5.js#2479] opened 2017-12-31 03:24 UTC
- [x] Bug
- [x] WebGL
- [x] Desktop/Laptop
- [x] 0.5.16

The Following codesnippet contains only the really necessary parts to demonstrate a couple of issues/bugs I come across during experimenting with multiple P2D and WEBGL combinations.
Bug description is in the comment.

The error shown here, usually is not thrown because another error described in this issue https://github.com/processing/p5.js/issues/2478 fires first.

Another confusing result ... when I copied the concerning p5.Texture stuff into the sketch (without changing anything) the error did not show up and the demo (kind of) worked.

```javascript
//
// p5.bug, WEBGL
//
// config:
//   primary WEBGL
//   offscreen WEBGL
//
// throws:
//   1)
//   p5.js:70422 Uncaught TypeError: data.setModified is not a function
//   at p5.Texture.update (p5.js:70422)
//   2)
//   p5.js:67579 Uncaught TypeError: Cannot read property 'apply' of undefined
//   at p5.RendererGL._applyColorBlend (p5.js:67579)
//
// related: 
// 
//


var renderer;
var graphics;


function setup() { 

  // createCanvas(800, 600, P2D);
  createCanvas(800, 600, WEBGL);

  renderer = this._renderer;
  
  if(renderer instanceof p5.RendererGL){
    setAttributes('antialias', true);
  }

  graphics = createGraphics(800, 600, WEBGL)
} 


function draw() {
  
  // offscreen
  {
    graphics.push();
    graphics.resetMatrix();
    graphics.ortho();
    graphics.background(64);
    graphics.noStroke(); // buggy stroke 
    graphics.fill(255,0,0);
    graphics.rectMode(CENTER);
    graphics.rect(0, 0, 300, 300);
    graphics.pop();
  }
  
  
  // onscreen
  {
    push();
    background(32);
    
    if(renderer instanceof p5.Renderer2D){
      image(graphics, 0, 0);
    }
    
    if(renderer instanceof p5.RendererGL){
      resetMatrix();
      ortho();
      texture(graphics);
      plane(width, height);
      // 0/0 ... top left corner
      translate(-width/2,-height/2);
    }
    

    // rect attached to mouse
    translate(mouseX, mouseY);
    
    // tilt to see Aliasing
    if(renderer instanceof p5.Renderer2D) rotate (3 * PI/180);
    if(renderer instanceof p5.RendererGL) rotateZ(3 * PI/180);
    
    rectMode(CENTER);
    noStroke();
    fill(0,255,0);
    rect(0, 0, 50, 300);
    pop();
  }
  
}




p5.RendererGL.prototype._applyColorBlend = function(v1,v2,v3,a){
  var gl = this.GL;
  
  // < fix, ... not really, but at least i got rid of err 2) 
  var inst = this._pInst;
  if(inst instanceof p5.Graphics){
    var inst = inst._pInst;
  }
  // fix >
  

  var color = inst.color.apply(inst, arguments);
  var colors = color._array;
  if(colors[colors.length-1] < 1.0){
    gl.depthMask(false);
    gl.enable(gl.BLEND);
    gl.blendEquation( gl.FUNC_ADD );
    gl.blendFunc( gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA );
  } else {
    gl.depthMask(true);
    gl.disable(gl.BLEND);
  }
  return colors;
};


```

**Comment by kjhollen** [comment] 2018-01-05 08:23
I think this is a duplicate of #2472? The issue is that the texture handling is treating the webgl p5.Graphics like an image, but p5.Graphics is missing the setModified method. closing as duplicate, please reopen if I've misunderstood something here!

**Closed by kjhollen** 2018-01-05 08:23 UTC
Labels: area:webgl
