### ISSUE TITLE
iOS demands createGraphics and image has integer parameters

### ISSUE THREAD

**Issue by ChristerNilsson** [processing/p5.js#5775] opened 2022-08-30 20:38 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.4.2

### Web browser and version

Chrome 104.0.5112.99

### Operating System

iOS

### Steps to reproduce this

createGraphics takes two parameter: width and height. They have to be integers.
All image parameters has to be integers.
If this is not the case, the image will not be copied to the canvas.

**Comment by ChristerNilsson** [comment] 2022-08-30 20:40
I guess the simplest solution would be to transform all parameters to integers inside the createGraphics and image methods.

**Comment by Qianqianye** [comment] 2022-08-30 21:27
Hi @ChristerNilsson. Could you please provide code snippet or a p5 editor link with code that illustrates the issue. Thanks!

**Comment by limzykenneth** [comment] 2022-08-30 22:12
Probably duplicate of #5697

**Comment by ChristerNilsson** [comment] 2022-08-31 16:12
Yes, it is the same bug as #5697.
With the addition, image method parameters has to be integers.
I’m not sure if the transformation to integers has to take place inside or outside the methods.
All I know is that I lost two days looking for the reason for this error.

**Comment by ChristerNilsson** [comment] 2022-08-31 16:16
> Hi @ChristerNilsson. Could you please provide code snippet or a p5 editor link with code that illustrates the issue. Thanks!

It is almost the same bug as #5697. I found that the image method has the same behaviour.

**Comment by Qianqianye** [comment] 2022-08-31 17:30
Since this issue addresses the same problem in #5697, I will close this issue for now for organizational purpose. Let's continue the conversation in #5697. Thanks!

**Closed by Qianqianye** 2022-08-31 17:30 UTC
Labels: Bug, Area:Core, Area:Image
