### ISSUE TITLE
Summary: The four issues in the current implementation for mobile devices

### ISSUE THREAD

**Issue by KouichiMatsuda** [processing/p5.js#909] opened 2015-09-13 02:46 UTC
The current implementation for mobile devices has **four** issues:

1.  #891: The acceleationXYZ does **NOT** report the acceleration values of a device but its amount of rotations.
2.  #885: The deviceShaken() is called **NOT** only when the device is shaken **but also** when it is rotated. This is frequently happen.
3.  #908: The deviceTurned() is **NOT** called when the device rotates by more than 90 degrees. It is called when its rotation axis is changed.
4.  The deviceMoved() is called **NOT** only when the devices orientation changes by more than the threshold value **but also** when it is moved (translated) along with one axis.

The 4th issue is rarely happen in a default because the value of default threshold is 30. It means the deviceMoved() is called when a user moves (translates) the device more than 30 m/s^2 in one direction in one frame. It seems to be hard for the user but it could be happen, if the "threshold" is changed  to a smaller value by setMoveThreshold(). This issue will be fixed simultaneously when the 1st issue is fixed.

These are very confusing for beginners. I hope they should be fixed.

One of the straightforward solutions (which I mentioned in #891) is to provide rotationXYZ and modify the current implementation as I showed in #891. The advantage of this solution is

1. The current reference can be used **as it is**, just adding the new entries about rotationXYZ.
2. p5.js can provide the **similar level of functionality** which the modern mobile APIs (such as, android, iphone, and HTML5) are supporting.

**Comment by limzykenneth** [comment] 2015-09-18 14:14
@lmccart I can try to fix these issues if nobody is working on it at the moment. I'll be using the API as describe [here](http://www.html5rocks.com/en/tutorials/device/orientation/) and add rotationXYZ both in the source and documentation.

deviceShaken() and deviceTurned() might be fixed after the changes made to accelerationXYZ I'm not entirely sure yet.

**Comment by lmccart** [comment] 2015-09-18 16:59
I think that'd be great. I want to check though with @OhJia who worked on these this summer. @OhJia is it ok with you if @limzykenneth looks into the issues further and makes the proposed revisions?

**Comment by lmccart** [comment] 2015-09-20 20:03
@limzykenneth I think you can go ahead with the proposed changes.

**Comment by limzykenneth** [comment] 2015-09-21 12:27
I'm working on it and come across a small problem: the standard device orientation/motion events are working as expected but the `MozOrientation` event is a bit different. The x and y property of MozOrientation is the equivalent of `beta` and `gamma` rotation in device orientation while the z property is the acceleration along the Z axis equivalent of the device motion events z acceleration.

`MozOrientation` has already been deprecated and removed from Firefox since 6.0 as stated [here](https://developer.mozilla.org/en-US/docs/Web/Events/MozOrientation). Should we still keep this event and maybe explain it clearer in the documentation or simply remove support for it since it may cause some confusion among beginners and it's not very common in the wild. Thoughts?

Cheers.

**Comment by KouichiMatsuda** [comment] 2015-09-21 12:48
I think it should be removed. 
I think most people, especially beginners, don't use Firefox on mobile devices. 
http://www.statista.com/statistics/272664/market-share-held-by-mobile-browsers-in-the-us-since-2009/

**Comment by lmccart** [comment] 2015-09-21 15:18
the general policy of p5.js is to support the two most recent versions of major browsers, so I think it's fine to remove this.

**Comment by limzykenneth** [comment] 2015-09-21 17:42
`deviceTurned()` is giving me some problem here as it is hard to account for all three axis at the same time without unintended behaviour. Mainly the problem is when the device is not flat, say in a handheld landscape viewing position, the rotation value for the X axis will jump from 0 - 180 at certain point. My pass experience with deviceOrientation is that it is worst when lying down but that's a can of worms I don't want to open (none of the axis will work as intended). : P

I can try can and see if I can account for that somehow but it might start to look too convoluted. I would suggest separating out the `deviceTurned()` function into `deviceTurnedX()` `deviceTurnedY()` and `deviceTurnedZ()`. I think that way it will be easier to use as well, so you can only lock the device turned event to one axis while being able to bind it to all axis with additional function call.

Any ideas?

Cheers.

**Comment by lmccart** [comment] 2015-09-21 21:46
hm I like that this is clear, but I worry that this is overly explicit for the API when the other event methods are not so specific. what do you think about keeping it `deviceTurned()` and including an example in the reference that demonstrates how to check the `rotationX/Y/Z` inside with an if statement? similar to the way the `keyCode` is checked inside `keyPressed()` in the second example?
http://p5js.org/reference/#p5/keyPressed

**Comment by limzykenneth** [comment] 2015-09-21 22:28
That might not be a bad idea, I'll see what I can do.

**Comment by limzykenneth** [comment] 2015-09-22 12:30
I'm almost done here, just a few decisions that needs to be made:

As a result of the implementation of deviceTurned(), there is a few more variables related to rotations other than `rotationX`, `rotationY` and `rotationZ`:

1. pRotationX, pRotationY, pRotationZ. They act the same as pAccelerationXYZ just for rotations.
1. rotateDirectionX, rotateDirectionY, rotateDirectionZ which give rotation direction in the respective axis.

These variables are not exposed yet and I think they could be useful in some cases (rotateDirection and be used with deviceTurned() to figure out how many times the device have rotated fully). Although exposing them might make the API a bit too bloated.

Let me know what you think and if they are to be exposed, I'll add the respective documentation as well.

Cheers.

**Comment by KouichiMatsuda** [comment] 2015-09-22 13:19
I think pRotationXYZ are good idea to support them. They are useful to figure out how a device is rotated.

> rotateDirectionX, rotateDirectionY, rotateDirectionZ which give rotation direction in the respective axis.

I'm not sure about how these are implemented but if they are implemented as
      rotationDirectionX = rotationX - pRotationX;
then I think they are not necessary. Because we can estimate them easily.

**Comment by KouichiMatsuda** [comment] 2015-09-22 13:30
> I can try can and see if I can account for that somehow but it might start to look too convoluted. I would suggest separating out the deviceTurned() function into deviceTurnedX() deviceTurnedY() and deviceTurnedZ().

I think three APIs are too many. They looks like providing mousePressedLeftButton(), mousePressedMiddleButton(), and mousePressedRightButton() instead of mousePressed().
One solution would pass a rotation axis argument to deviceTurned(axis) or to provide a system variable to describe the current rotation axis, such as rotationAxis. 

Regards,

**Comment by limzykenneth** [comment] 2015-09-22 13:53
For deviceTurned() I managed to provide a system variable for the method so the usage is similar to keyPressed().

For the rotationDirection because my implementation also takes care of wrap around ie. from 175 degree to -175 degree (the angles go from 180 to -180 back to 180). It does a couple more checks than `rotationDirectionX = rotationX - pRotationX;` to account for that. Then again, I'm not sure if a user will really need it.

**Comment by KouichiMatsuda** [comment] 2015-09-23 10:50
Thanks. I see.

For the rotationDirection, I think "rotationX - pRotationX" might be sufficient for most cases (I might be wrong).

So, as a first step, it might be better that rotationDirections should be provided as an example in the reference that demonstrates how to use them based on the rotationX/Y/Z,  pRotationX/Y/X, and a couple more checks you've done in your implementation. After that, you should discuss them again.

**Comment by limzykenneth** [comment] 2015-09-23 11:33
Yeah, that's true. The wrap around issue is really just an edge case that may cause problem in limited fashions. In that case, do you think the example for getting rotationDirection should be included in the documentation of pRotationXYZ or as an entry in the example page along with other mobile examples?

@lmccart What do you think? I can submit a PR today as soon as a decision is made.

**Comment by KouichiMatsuda** [comment] 2015-09-23 12:01
The "edge" case is the best wording.

> In that case, do you think the example for getting rotationDirection should be included in the documentation of pRotationXYZ or as an entry in the example page along with other mobile examples?

I think the latter is better. You should have an entry in the example page along with other mobile examples?

**Comment by lmccart** [comment] 2015-09-23 15:39
@limzykenneth great! if the example is not too long, I think putting it right into the reference makes sense. if it is a bit more involved, we can keep put it on the examples page. how does that sound?

**Comment by limzykenneth** [comment] 2015-09-23 16:15
They are not too long so I think they can fit on the reference. I'll work on it now, expect PR soon. Cheers.

**Comment by lmccart** [comment] 2015-09-28 00:59
hi @KouichiMatsuda, thanks to your thorough reporting and @limzykenneth's [great work](https://github.com/processing/p5.js/pull/937), I believe all issues here are now resolved. the next build (v0.4.13) which will be posted tomorrow should contain these fixes. if you still notice issues with this next build, please feel free to reopen this issue. thanks again!

**Closed by lmccart** 2015-09-28 00:59 UTC
Labels: area:mobile

**Comment by KouichiMatsuda** [comment] 2015-09-28 08:10
Thanks.
I am looking forward to seeing the code!

Regards,

p.s.
4.13 is my birthday :)

2015-09-28 9:59 GMT+09:00 Lauren McCarthy <notifications@github.com>:

> hi @KouichiMatsuda <https://github.com/KouichiMatsuda>, thanks to your
> thorough reporting and @limzykenneth <https://github.com/limzykenneth>'s great
> work <https://github.com/processing/p5.js/pull/937>, I believe all issues
> here are now resolved. the next build (v0.4.13) which will be posted
> tomorrow should contain these fixes. if you still notice issues with this
> next build, please feel free to reopen this issue. thanks again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js/issues/909#issuecomment-143609883>.
>



-- 
松田晃一 MATSUDA, Kouichi, Ph.D.
