### ISSUE TITLE
Using p5.js and three.js together

### ISSUE THREAD

**Issue by outisfun** [processing/p5.js#1771] opened 2017-01-21 07:26 UTC
Hello, 

So I'm trying to overlay a p5 canvas over a three.js canvas. Both are in separate divs positioned absolutely one on top of the other.
I have a p5.js script and a three.js script. Both of them separately work just fine, but when I try to combine them, the three.js script gives error. Here's how my scripts look (they're just before the closing of the <body> tag):

<script src="../build/three.js"></script><br>
<script src="js/renderers/Projector.js"></script><br>
<script src="js/renderers/CanvasRenderer.js"></script><br>
<script src="js/shaders/BokehShader2.js"></script><br>
<script src="js/loaders/OBJLoader.js"></script><br>
<script src="js/cameras/CinematicCamera.js"></script><br>
<br>
<script src="cali/mainthree.js"></script><br>

<script src="js/p5-zip/p5.min.js"></script><br>
<script src="cali/mainp5.js"></script><br><br>

Is there a way to load them correctly so that both work?

Thank you in advance and apologies if it's a silly question!

**Comment by limzykenneth** [comment] 2017-01-21 12:44
@outisfun What does the error says?

**Comment by lmccart** [comment] 2017-01-29 00:35
Here is a codepen that demonstrates an example of using the two libraries together, in two divs absolutely positioned on top of each other.
http://codepen.io/p5js/pen/apVPVx?editors=1111

**Comment by Katy310** [comment] 2017-02-04 12:31
I'd like to work on this issue. Any guidelines or pointers on how to approach it?

**Comment by limzykenneth** [comment] 2017-02-04 13:01
Hi @Katy310 thanks for taking an interest! Currently for this issue we don't have much to go on as @outisfun has not provided enough information for us to determine what the problem is. I would advice you to try tackling other issues in the meantime but if you are keen to tackle this one, you can try and see if you can replicate the situation mentioned above.

**Comment by Katy310** [comment] 2017-02-04 13:05
Oh alright. Thanks a lot @limzykenneth. I am new to P5.js and am looking at beginner friendly issues as I intend to apply to RGSoc'17.

**Comment by limzykenneth** [comment] 2017-02-04 13:08
Cool, stick around and have a look at the various issues, not all of them are categorised so maybe some you may be able to tackle but are not labeled beginner

**Comment by Katy310** [comment] 2017-02-04 13:09
Yes, I'll look at other issues.

**Comment by lmccart** [comment] 2017-02-05 00:05
thanks @limzykenneth! @Katy310 i'll try to look through and tag any others that may be beginner level.

@outisfun I'm going to close this. I think the codepen I attached should hopefully get you started.

**Closed by lmccart** 2017-02-05 00:05 UTC
Labels: level:beginner

**Comment by jagadeeshCoder** [comment] 2022-05-12 10:45
how to add .gltf model in p5.js
