### ISSUE TITLE
createCapture should provide access to getUserMedia constraints

### ISSUE THREAD

**Issue by brysonian** [processing/p5.js#495] opened 2015-01-26 19:25 UTC
getUserMedia allows you to pass constraints to the video resolution and fps. 
More info: https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-MediaTrackConstraints and http://www.html5rocks.com/en/tutorials/getusermedia/intro/#toc-constraints

**Comment by kevinb7** [comment] 2015-01-27 06:49
look like a duplicate of https://github.com/lmccart/p5.js/issues/476

**Comment by lmccart** [comment] 2015-01-27 13:14
closed https://github.com/lmccart/p5.js/issues/476, as this covers it more generally

**Comment by lmccart** [comment] 2015-03-05 14:03
ahh this one keeps coming up with students, will get to it soon!

**Closed** 2015-04-02 17:39 UTC
