### ISSUE TITLE
URGENT: print() command collides with browser/OSX print() command

### ISSUE THREAD

**Issue by golanlevin** [processing/p5.js#1579] opened 2016-09-02 21:07 UTC
With apologies, I have marked this URGENT because fall classes have just started and this bug is about to slay dozens of new programmers everywhere. 

Something has changed between 0.5.2 and 0.5.3, such that the following code, 

var foo = 0; 
print(foo); 

no longer prints diagnostic data to the console. Instead, in version 0.5.3, it pauses the p5 environment and opens up the operating system's Print dialog, for the printer! I have tested this in OSX 10.9.5 and 10.11.5. I consider this problem urgent because printing data to the console is one of the easiest ways to begin debugging. 

Thank you!
Golan

**Comment by dribnet** [comment] 2016-09-02 21:42
Confirmed that in 0.5.2 "print" was a p5.js function, but no longer is in 0.5.3. As a workaround, the following can be added to the top of any 0.5.3 sketch:
```js
p5.prototype.print = p5.prototype.println;
```

**Comment by dribnet** [comment] 2016-09-02 21:52
So `print` was intentionally removed in ecf8ee0e and this was documented in the [0.5.3 release notes](https://github.com/processing/p5.js/releases/tag/0.5.3).

**Comment by lmccart** [comment] 2016-09-03 01:52
thanks @dribnet, this is correct, it was removed as of 0.5.3. the main reason is that having it in there overwrites the native browser command `window.print()` that opens a print dialog, which could be useful functionality. in addition, we already had `println()` which was essential an alias for the same method. as of 0.5.3, `println()` should be used instead. I'll look into adding a warning message per @golanlevin's suggestion if users do try to call this.

for reference, here's the original discussion of this change.
https://github.com/processing/p5.js/issues/1491

**Comment by golanlevin** [comment] 2016-09-03 22:22
Thanks for your replies @dribnet & @lmccart.  I'm embarrassed not to have checked the changelog/releasenotes to see that this change was actually _deliberate_ (though I _had_ checked to see whether an issue had been filed :) It's good to know that `println()` and `console.log` (see [https://developer.mozilla.org/en-US/docs/Web/API/Console/log](https://developer.mozilla.org/en-US/docs/Web/API/Console/log), via @brysonian) are working solutions.

So, a lot of my older pedagogic examples use print(), and so do my typing habits :/ I'd like to advise that a warning for print() should be issued in p5.js (but perhaps not in p5.min.js), which says something to the effect of "Did you mean to use println() or console.log()?" I consider it much more likely that someone is mistakenly trying to use `print()` to do some debugging, than they are the rare individual who actually is trying to kick open the printer. 

It might also be good to put some sort of information in the reference at [http://p5js.org/reference/#/p5/print](http://p5js.org/reference/#/p5/print), indicating that this function may appear in older code (pre 0.5.3) but has been obsolesced.

**Comment by dribnet** [comment] 2016-09-03 22:41
Note that `window.print()` takes no parameters and `p5.print()` would always have parameters, so it should be possible to do a runtime check like:

```javascript
p5._haveGivenPrintWarning = false;
p5.prototype.print = function(args) {
  if (arguments.length === 0) {
    window.print();
    return;
  }
  if(!p5._haveGivenPrintWarning) {
    println("Warning: p5.print() is deprecated, please use p5.println() instead");
    p5._haveGivenPrintWarning = true;
  }
  println.apply(args);
}
```

@lmccart - I can try to put something like this into a merge request for  `environment.js` if you think this it's worthwhile.

**Comment by lmccart** [comment] 2016-09-03 22:46
hm, interesting. great point. I'd be fine with this, but on the other hand I wonder about the usefulness of having two methods that do the exact same thing (`print()` and `println()`). we are well under 1.0, intentionally, to give us space to iterate to find the API that feels right to us. so I think we should preference what makes sense for the future, as long as it's not too big a detriment to current users.

that being said, if people feel that `print()` is just a better name (maybe it is, shorter to write and say and less ambiguous characters), I'd be happy to remove `println()` and use @dribnet's proposed solution of checking args.

**Comment by golanlevin** [comment] 2016-09-03 23:00
My opinion: p5.js is ideal as an environment for introductory learning, new programmers, kids, etc., for whom `print()` is much more obvious and memorable. I like @dribnet's solution to restore the functionality of `print()`. Additionally, however, I'd like to recommend retaining `println()`, both for backwards compatibility and for parity with Processing.

**Comment by brysonian** [comment] 2016-09-04 17:46
@golanlevin I agree that it is a great environment for new programmers. But in that vein i wonder if "print" is the best choice for this functionality at all. I've had many students over the years be confused when first learning about print because it doesn't make a piece of paper come out of the printer. Similarly, an ambitious student googling "how to print in javascript" is going to find a bunch of correct answers that don't work. 

I wonder if using "log" might be a better choice because it is closer to the actual javascript API (which includes node.js) and doesn't have any technical or semantic clashes. That way a student moving to straight JS in the browser or node just has to learn to add "console." 

The advantage to sticking with "print" is really just mapping back to processing and a few other languages like python and java who use print.

**Comment by lmccart** [comment] 2016-09-21 01:40
I agree, I like `log()` a lot, but then there is the issue that it collides with the p5.js existing log function (as in logarithm). 😶 

I think @golan's case for `print()` feels like the next best option, so I will restore functionality of `print()` in the next release. I would also like to remove `println()` to reduce redundancy. Thanks all for your input and sorry for the confusion this causes at the start of the semester.

**Closed** 2016-09-22 02:20 UTC
