### ISSUE TITLE
Add mechanism to stop recordings from createCapture()

### ISSUE THREAD

**Issue by neefrehman** [processing/p5.js#4085] opened 2019-10-15 13:34 UTC
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [x] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Feature enhancement details:

My p5 sketch is contained in a single-page-app. When using `createCapture()` a video stream starts recording as expected, but when I navigate to a different route and remove the sketch with p5's `remove()` function, my webcam indicator light is still on, implying the stream is still running but just not being used.

Obviously my specific case isn't too common as most people would be running their sketch in an individual HTML page that would stop the stream when navigating away. However, It would be great if `remove()` also stopped any active `getUserMedia` streams (video or audio), or if there was another way to stop the capture without exiting the page.

I've done a quick bit of digging but haven't found any other way with JS to stop the stream that I can implement on my end, as I can't see a global variable to run `track.stop()` on.

##### Relevant links:
Processing Discourse: [Possible to stop webcam after using createCapture](https://discourse.processing.org/t/possible-to-stop-webcam-after-using-createcapture/10557)
StackOverflow: [Stop/Close webcam which is opened by navigator.getUserMedia](https://stackoverflow.com/questions/11642926/stop-close-webcam-which-is-opened-by-navigator-getusermedia)
GoogleDevelopers: [MediaStream Deprecations](https://developers.google.com/web/updates/2015/07/mediastream-deprecations?hl=en#stop-ended-and-active)

**Comment by singhvisha** [comment] 2019-11-27 07:26
hi @stalgiag,
It seems that when try to remove the streaming caused by the `createCapture()` method using the `remove()` method(method in p5).It don't stop streaming.the light of the webcam is still open which implies that the microphone and camera is runnning.

I think that this issuse closely resmbles the issuse(#4140).Implenting this feature might be a solution for the the issue(#4140 ) also.

There are two `remove()` method.Can you please tell whether It should go either [here](https://github.com/processing/p5.js/blob/0.10.2/src/core/main.js#L406) or [here](https://github.com/processing/p5.js/blob/0.10.2/src/dom/dom.js#L2056)?

As the discussion where going in issue(#4140 )
`
@limzykenneth
 
Member
limzykenneth commented 15 days ago
remove() is a p5.Element wide method so how to pin point it to p5.MediaElement I'm not exactly sure. The inheritence there is rather messy.

@stalgiag
 
Contributor
stalgiag commented 9 days ago
It would not help with messiness in the inheritance but a quick fix could be to:

if (this instanceof p5.MediaElement) {
  let stream = this.elt.srcObject;
  let tracks = stream.getTracks();

  tracks.forEach(function(track) {
    track.stop();
  });

  this.elt.srcObject = null;
}
`
Could you please tell where to implement this features?

**Comment by limzykenneth** [comment] 2019-11-27 08:35
The problem seems to be the same as #4140 so the solution @stalgia suggested should solve this issue as well. The function that needs changing is this one: https://github.com/processing/p5.js/blob/0.10.2/src/dom/dom.js#L2056, the `remove()` function on `p5.Element`.

I can assign you to this issue if you are going to work on it.

**Comment by singhvisha** [comment] 2019-11-27 08:38
Hi @limzykenneth,
I would definitely like to work on this?

**Comment by limzykenneth** [comment] 2019-11-27 08:57
@singhvisha Great! Just file a PR whenever you are ready. I'll assign you the other issue as well.

**Comment by singhvisha** [comment] 2019-11-27 09:09
@limzykenneth,
I will soon submit PR

**Comment by lmccart** [comment] 2019-11-28 20:44
fixed with https://github.com/processing/p5.js/pull/4166

**Closed by lmccart** 2019-11-28 20:44 UTC
Labels: area:dom, feature request
