### ISSUE TITLE
Clipping Y-Axis Lines

### ISSUE THREAD

**Issue by SpilledMilkCOM** [processing/p5.js#4722] opened 2020-07-30 14:25 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

Only the lines that represent the Y axis are being clipped; all other primitives seem fine.  My sample sketch is at the following link:  https://editor.p5js.org/SpilledMilkCOM/sketches/-fHjsQGQN

*(I'm new to p5 so maybe I'm doing something wrong, but it's pretty basic code. I posted to the Coding Train discord, but didn't see any feedback.)*

- p5.js version:  Not sure of the version.  *I just assume that the p5 editor is running the latest.*
- Web browser and version:  **Chromium / Edge**
- Operating System:  **Windows 10**
- Steps to reproduce this: https://editor.p5js.org/SpilledMilkCOM/sketches/-fHjsQGQN

**Comment by stalgiag** [comment] 2020-07-31 13:55
Hi and welcome! I am a bit confused by what the precise problem is. Can you make a simpler sketch that shows the problem or explain in more detail the difference between expected and actual results. Thanks!

**Comment by SpilledMilkCOM** [comment] 2020-07-31 23:55
When you hit play, the two Y-axes (the short ones) are disappearing when pointing away from the viewport.  I kept the spheres in the model to show that the spheres are NOT being clipped.  I'll adjust it and remove some of the primitives.  I removed the X and Z primitives, and left the 4 Y primitives (the two lines and two spheres).  The lines are being clipped and yet the spheres are not.  Also, when you include the X and Z lines those are NOT being clipped and yet the Y lines are still being clipped.  I hope this helps.  THANKS!

**Comment by stalgiag** [comment] 2020-08-01 12:01
Thanks for the more detailed explanation. I am unable to reproduce (or see) any clipping that appears abnormal on Mac OS X with latest Firefox and Chrome. The only time that the line disappears is when foreshortening is so severe that it appears as a single dot but this is expected behavior when pivoting the line towards the view. It is possible that this is a Windows/Edge specific problem.

**Comment by SpilledMilkCOM** [comment] 2020-08-03 17:20
I attached screen shots of what I see in Edge/Chromium.  I see the same issue in Chrome.  I don't see the issue on my iPhone.  The clipped piece shows up as slightly thinner lines on my phone.

![Annotation 2020-08-03 111248](https://user-images.githubusercontent.com/22199284/89209040-c53c2100-d57a-11ea-9dba-d7880a75cbfc.png)
![Annotation 2020-08-03 111248-2](https://user-images.githubusercontent.com/22199284/89209045-c5d4b780-d57a-11ea-88c7-c836bf231a1d.png)

**Comment by stalgiag** [comment] 2020-08-04 13:23
Okay! Just got a chance to check this out on Chrome/Windows. I am able to reproduce on 0.10.2 but the issue is gone on 1.0.0 and 1.1.9. I am unsure what caused the problem but there was a fairly extensive rewrite of core WebGL code between those versions so something likely fixed it during those changes.

I am going to mark this as resolved since the current codebase and the most recent releases all work. To fix in your sketch you can go to the `index.html` file tab and change the script line for p5 to:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.1.9/p5.js"></script>`

Marking this as resolved and closing for tidiness. Thanks!

**Closed by stalgiag** 2020-08-04 13:23 UTC
Labels: area:webgl, bug

**Comment by SpilledMilkCOM** [comment] 2020-08-10 13:53
When I use the p5.js editor online, how do I choose the version?  I don't even know what version I'm using when I use that editor.  THANK YOU for taking a look at this.

**Comment by stalgiag** [comment] 2020-08-10 13:58
If you click the right-facing arrow underneath the play button it reveals the file explorer. In the file explorer, you can click index.html and change the script line as explained in my prior comment. A new sketch made in the editor should also have 1.1.9 by default at the moment so you can simply copy your code over into the new sketch window.

**Comment by SpilledMilkCOM** [comment] 2020-08-10 20:34
THANK YOU!!  That did the trick!
