### ISSUE TITLE
windowHeight returns 0

### ISSUE THREAD

**Issue by GamefreakSenpai** [processing/p5.js#1584] opened 2016-09-08 16:27 UTC
Every time in the setup() function windowHeight return 0 later on it returns the true value.

**Comment by limzykenneth** [comment] 2016-09-08 23:25
Hi @GamefreakSenpai, what browser (with version) and OS are you using? Also it would be great if you can include a code example as well.

**Comment by lmccart** [comment] 2016-10-01 16:38
I'm going to close this for now since we're having trouble reproducing, please feel free to reopen and update with info about browser, OS, and code sample. Thanks!

**Closed by lmccart** 2016-10-01 16:38 UTC
