### ISSUE TITLE
Improved IOS support, working examples for inline video, audio and touch events

### ISSUE THREAD

**Issue by jacopomazzoni** [processing/p5.js#3729] opened 2019-05-06 20:43 UTC
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [x ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ x] Other (specify if possible)
IOS support
#### Which platform were you using when you encountered this?

- [x ] Mobile/Tablet (touch devices)
- [ ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.8.0
- Web browser and version: safary but really any on IOS 
- Operating System: IOS
- Steps to reproduce this:
see https://discourse.processing.org/t/ios-support-for-inline-video-touch-events-and-audio/10961

#### Feature enhancement details:
add native support for IOS by incorporating the examples I provided here https://discourse.processing.org/t/ios-support-for-inline-video-touch-events-and-audio/10961

#### New feature details:
Support for IOS see here: https://discourse.processing.org/t/ios-support-for-inline-video-touch-events-and-audio/10961

**Comment by limzykenneth** [comment] 2019-05-08 10:19
Hi, can you give more specific examples about what is the current behaviour and what is the expected behaviour?

**Comment by jacopomazzoni** [comment] 2019-05-09 21:44
The beahviour for video currently loads a full screen player instead of loading the video frames in the canvas object.
P5. Sound just flat out did not work for me on ios. (several iPhone models tested) this does.

**Comment by stalgiag** [comment] 2019-05-10 01:17
Hi @jacopomazzoni! I have a bit of confusion about this issue.

> The behaviour for video currently loads a full screen player instead of loading the video frames in the canvas object.

Could you point to a broken example somewhere? Perhaps on the p5 website? The link you provide points to a forum thread which points to a sketch file. This doesn't make it easy to figure out the problem on our end. Once we figure out what the problem is, if the fix that you developed for that sketch is a good solution then you can open a PR that adds that code into the library source. But we can't extract code from a sketch file and add it to the source to fix a problem we don't fully understand. Hopefully that all makes sense.

Thanks!

**Comment by stalgiag** [comment] 2019-07-01 23:41
I am closing this issue for now since it needs some more information to be properly addressable. If you are able to provide the information requested above just @ me and I will happily reopen. Thank you!

**Closed by stalgiag** 2019-07-01 23:41 UTC
