### ISSUE TITLE
p5 had problems creating the global function "log"

### ISSUE THREAD

**Issue by Huc91** [processing/p5.js#2708] opened 2018-03-17 18:40 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

- p5.js version: 0.6 

On Chrome i get this on the console:
p5 had problems creating the global function "log", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.

it occurs at: p5.js:46563 

I have no global variable called "log" in my code

**Comment by limzykenneth** [comment] 2018-03-19 08:39
Can you share your code that is causing this issue? Thanks

**Comment by Huc91** [comment] 2018-03-19 09:32
Here you go, this is the old version that was causing the problem.
I have changed the code to have p5.js in [instance mode](https://github.com/processing/p5.js/wiki/Global-and-instance-mode) and now the problem is gone.
`//wolfram automaton
//array of cells
//edit on Shiffman example
var cells = [0, 0, 0 ,1 ,1 ,1 ,0 ,0 ,0];
var art = 0.2


var ruleset = [1,0,0,1,1,0,1,0];
var generation = 0;
var w = 50;

function generate(cells){
  // First we create an empty array filled with 0s for the new values
  var nextgen = [];
  for (var i = 0; i < cells.length; i++) {
    nextgen[i] = 0;
  }
  // For every spot, determine new state by examing current state, and neighbor states
  // Ignore edges that only have one neighor
  for (var i = 1; i < cells.length-1; i++) {
    var left   = cells[i-1];   // Left neighbor state
    var me     = cells[i];     // Current state
    var right  = cells[i+1];   // Right neighbor state
    nextgen[i] = rules(left, me, right); // Compute next generation state based on ruleset
  }
  // The current generation is the new generation
  this.cells = nextgen;
  this.generation++;

// This is the easy part, just draw the cells
function display() {
  for (var i = 0; i < cells.length; i++) {
    if (cells[i] == 1) {
      fill(255)
    } else if (cells[i] == 0) {
      if (Math.random() <= art){
        fill(125)
        noStroke();
        triangle(i*w, generation*w+50, i*w+25, generation*w, i*w+50, generation*w+50);
      } else {
        fill(0)
        noStroke();
        rect(i*w, generation*w, w, w);
      }
    } else {
      fill (125);
      noStroke();
      rect(i*w, generation*w, w, w);
    }
  }
};

// Implementing the Wolfram rules
// Could be improved and made more concise, but here we can explicitly see what is going on for each case
function rules(a, b, c) {
  if (a == 1 && b == 1 && c == 1) return ruleset[0];
  if (a == 1 && b == 1 && c === 0) return ruleset[1];
  if (a == 1 && b === 0 && c == 1) return ruleset[2];
  if (a == 1 && b === 0 && c === 0) return ruleset[3];
  if (a === 0 && b == 1 && c == 1) return ruleset[4];
  if (a === 0 && b == 1 && c === 0) return ruleset[5];
  if (a === 0 && b === 0 && c == 1) return ruleset[6];
  if (a === 0 && b === 0 && c === 0) return ruleset[7];
  return 0;
};
display();
}

function setup() {
  createCanvas(800, 2000);
  stroke(255);
  noFill();
}

function draw() {
  if(generation <= 8){
    generate(cells);
  }
}`

**Comment by limzykenneth** [comment] 2018-03-19 10:43
Hmm...I can't duplicate the error on my side.

**Comment by Spongman** [comment] 2018-03-19 17:50
maybe an extension, or a another script getting loaded on the page?

**Comment by Spongman** [comment] 2018-03-19 17:51
````
function rules(a, b, c) {
  return ruleset[a + b*2 + c*4];
````


;-)

**Comment by meiamsome** [comment] 2018-03-19 19:14
Perhaps try typing `log` into the JS console whilst on the page to see what that shows up as

**Comment by lmccart** [comment] 2018-03-19 21:06
there is a p5 function called [log](https://p5js.org/reference/#/p5/log) which could be causing a namespace conflict. you could change the name of the function, or use [instance mode](https://github.com/processing/p5.js/wiki/Global-and-instance-mode) to wrap up all the p5 functions under the p5 namespace.

**Comment by lmccart** [comment] 2018-03-19 23:15
ah I'm sorry I misunderstood the issue. i'm also not able to reproduce this, I'm guessing it could be an extension or another script as @Spongman suggests. since you've found a workaround, I'm going to close this issue

**Closed by lmccart** 2018-03-19 23:15 UTC

**Comment by Huc91** [comment] 2018-03-20 14:11
Thanks to everyone who answered this! Yeah I think it was an extension

**Comment by Huc91** [comment] 2018-03-20 14:15
@Spongman Can you explain me what you mean with this?
```
function rules(a, b, c) {
  return ruleset[a + b*2 + c*4];
```
Maybe it was because I read it late at night but I didn't get it, sorry :-D
