### ISSUE TITLE
textWidth not implemented in WebGL mode

### ISSUE THREAD

**Issue by janschill** [processing/p5.js#2278] opened 2017-10-20 16:53 UTC
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [X] Data
- [X] WebGL
- [X] Text

#### Which platform were you using when you encountered this?

- [X] Desktop/Laptop

#### Details about the bug: 

- p5.js version: p5.js v0.5.16 October 11, 2017
- Web browser and version: Chrome - Version 62.0.3202.62 (Official Build) (64-bit)
- Operating System: MacOSX - 10.13
- Steps to reproduce this:

Uncaught TypeError: Cannot read property 'apply' of undefined
    at p5.textWidth
    at TextObject.drawTextWithParsing)
    at TextObject.drawAt
    at fileLoaded
    at XMLHttpRequest.req.onreadystatechange

```
function loadFile() {
    txt = loadStrings("data/mi-module.txt", fileLoaded);
}

function fileLoaded(data) {
    acquireAndParse(txt, objects);
    for (let i = 0; i < objects.length; i++) {
        objects[i].drawAt(width / objects.length * i, 425);
    }
    for (let i = objects.length - 1; i >= 0; i--) {
        if (objects[i].textLength() < 100) {
            objects.splice(i);
        }
    }
}
function setup() {
    let canvas = createCanvas(1100, 450, WEBGL);
}
function acquireAndParse(file, objects) {
    let running = false;
    let line = "";
    let textObject = new TextObject("");
    let i = 0;

    while (i < file.length) {
        try {
            line = file[i];
            // console.log(file[i]);
        } catch (error) {
            line = null;
            i = file.length;
            console.log("error loading");
        }
        if (line.indexOf("----") == 0) {
            objects.push(textObject);
            textObject = new TextObject("");
        } else {
            textObject.appendText(line + " ");
        }
        i++;
    }
}
```

```
class TextObject {
    drawAt(x, y) {
        push();
        translate(x, y);
        rotate(radians(-90));
        this.drawTextWithParsing();
        pop();
    }

    drawTextWithParsing() {
        for (let i = 0; i < this.textLength(); i++) {
            let c = this.text.charAt(i);
            let letterWidth = textWidth(c);
            let lineLength = this.textLength();

            text(c, 0, 0);
            translate(letterWidth, 0);

            if (lineLength % 2 == 1) {
                rotate(radians(0.01 * i));
            } else {
                rotate(radians(-0.01 * i));
            }
            switch (c) {
                case ' ':
                    if (i % 2 == 1) {
                        rotate(radians(25));
                    } else {}
                    rotate(radians(-25));
                    translate(letterWidth, 0);
                    break;
                case '.':
                    rotate(radians(45));
                    translate(letterWidth, 0);
                    break;
                case ',':
                    rotate(radians(-45));
                    translate(letterWidth, 0);
                    break;
                default:
                    text(c, 0, 0);
                    translate(letterWidth, 0);
            }

            if (c >= 'A' && c <= 'Z') {
                let lettercolor = c - 'A';
                fill(map(lettercolor, 1, 26, 100, 240), .8, .8, .8);
            }
        }
    }
}
```
_I removed small portions, which shouldn't have any effect on the error_

I get this error message, when I turn on WEBGL, otherwise it runs fine.

Here is the full code: [Gist](https://gist.github.com/janschill/88a739805481f8bb24fec4daaba8fd6a)

**Comment by meiamsome** [comment] 2017-10-20 16:57
Have you got the data/mi-module.txt file, perchance?

**Comment by janschill** [comment] 2017-10-20 16:59
Of course

[mi-module.txt](https://github.com/processing/p5.js/files/1402717/mi-module.txt)

**Comment by meiamsome** [comment] 2017-10-20 17:09
Ah, ok.

This just comes down to `textWidth` being unimplemented in WEBGL mode - probably to be implemented as part of #2183 when text functionality is added to WEBGL. Minimum reproduction is:
```javascript
function setup() {
    let canvas = createCanvas(1100, 450, WEBGL);
    textWidth("test");
}
```

Sorry that this isn't in WEBGL mode yet - hopefully you can get the feature you need in another way

**Comment by kjhollen** [comment] 2017-12-30 20:17
@meiamsome is right, the method is not available yet because we're still working on text implementation for GL mode. updated the title to reflect this!

**Comment by lmccart** [comment] 2018-01-04 02:16
closing this, we can follow up over here with the implementation of text() https://github.com/processing/p5.js/issues/2183

**Closed by lmccart** 2018-01-04 02:16 UTC
Labels: area:webgl
