### ISSUE TITLE
strokeWeight(); is modifying the drawings made before it being called

### ISSUE THREAD

**Issue by Edely** [processing/p5.js#1636] opened 2016-10-15 09:15 UTC
I am new to P5, so I don't know if I am right, but I think there is a bug with strokeWeight(). It changes the stroke weight of the draws made before it being called. For instance, when I follow the example 3-12 of Getting Started With P5.js book I have this code:

```
function setup() {
	createCanvas(480, 120);
} 
function draw() {
	background(204);
	ellipse(75, 60, 90, 90);
	strokeWeight(8); // Stroke weight to 8 pixels
	ellipse(175, 60, 90, 90);
	ellipse(279, 60, 90, 90);
	strokeWeight(20); // Stroke weight to 20 pixels
	ellipse(389, 60, 90, 90);
}
```

The first ellipse is supposed to have a 1 pixel stroke, but is getting a stroke of 20 pixels.

I tested this in Chrome 53.0.2785 and Firefox 47.0.1.

**Comment by Edely** [comment] 2016-10-15 10:31
Actually, I am following the other examples of the book and is not just strokeWeight(). Every time I set a property like fill, noStroke, etc, the previous draws that don't have these properties explicitily defined are changing too.

**Comment by limzykenneth** [comment] 2016-10-16 13:32
Hi @Edely, you are probably using an older version of p5.js. The above problem should be fixed in I think either 0.5.3 or 0.5.4. Just update the p5.js file in you sketch folder with a new copy of p5.js from the website and you should be good to go.

**Comment by joecridge** [comment] 2016-10-16 14:02
I may be wrong, but I thought that this was the expected behaviour?

When `draw()` is first entered, `strokeWeight` is 1 by default, and so the first ellipse has a stroke weight of 1 in the first frame. By the end of the first frame, the global `strokeWeight` has been set to 20. This persists so that at the start of the second frame (and all subsequent frames), `strokeWeight` is still 20, and so the first ellipse is drawn with a stroke weight of 20.

You can see this happening by adding `frameRate(1);` into `setup()`.

**Comment by limzykenneth** [comment] 2016-10-16 14:09
@joecridge the transform matrix is supposed to reset at the end of each draw call, more intuitive and also parity with Processing, see discussions #1193 and #1390. Arguably `strokeWeight` and `fill` are styles instead of matrix transform but I think they are wrapped together in Processing/p5.js as opposed to separate as in the case with openframeworks.

**Comment by joecridge** [comment] 2016-10-16 14:23
I’m seeing the behaviour described above in p5.js 0.5.4, p5.js master, and Processing 3.2.1. Are they all in the wrong then?

**Comment by limzykenneth** [comment] 2016-10-16 14:26
Really? This is what I get woth 0.5.4 with Safari 10.0, which looks right to be though:
![screen shot 2016-10-16 at 10 25 05 pm](https://cloud.githubusercontent.com/assets/7543950/19418095/7dbd82cc-93ef-11e6-8341-e872afe230e8.png)

Been awhile since I used Processing so you might be right.

**Comment by joecridge** [comment] 2016-10-16 14:34
That’s odd, I just copied and pasted @Edely’s code into the `empty_example` in p5.zip 0.5.4, also in Safari 10.10:

## Frame 1

<img width="1440" alt="screen shot 2016-10-16 at 15 31 16" src="https://cloud.githubusercontent.com/assets/11491479/19418129/aca549b0-93b5-11e6-9fb0-11b196f1b737.png">

## Frame 2

<img width="1439" alt="screen shot 2016-10-16 at 15 31 26" src="https://cloud.githubusercontent.com/assets/11491479/19418130/aca925bc-93b5-11e6-904f-452affd63767.png">

**Comment by limzykenneth** [comment] 2016-10-16 14:40
wait, hold on, I've made a terrible mistake, you are right, it doesn't reset by default...ignore what I said..... 😭 

About the tutorials from the book though, presumably it assumed that `strokeWeight` and `fill` alike would reset after each draw call. What kind behaviour would you think is better?

**Comment by joecridge** [comment] 2016-10-16 14:54
Okay, I don’t have a copy of the book so I’m not sure what it’s assuming. Personally I find persistent styles more intuitive, but that’s just because it’s what I’m used to from Processing.

**Comment by lmccart** [comment] 2016-10-16 15:29
The transform matrix resets at the end of draw, but the styles persist. So on the first frame you would see the default strokeWeight of 1, but all frames after that will hold the last set strokeWeight (20 in this case) unless it is reset to 1 again before drawing the first circle. This behavior is consistent with Processing. This behavior is also documented in the reference entry for [draw()](http://p5js.org/reference/#/p5/draw).

**Closed by lmccart** 2016-10-16 15:29 UTC
