### ISSUE TITLE
webgl: lighting state lost between draw calls

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js#3398] opened 2018-12-13 07:12 UTC
0.7.2:

EDIT: @sanketsingh24's example below doesn't require the `resizeCanvas()` call.

calling `resizeCanvas()` breaks lighting:

```javascript
function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  resizeCanvas(windowWidth, windowHeight);
  directionalLight(255, 255, 255, 0, 0, -1);
}

function draw() {
  background(0);
  sphere(width/3);
}
```

![image](https://user-images.githubusercontent.com/1088194/49921698-4228fd00-fe63-11e8-949a-2a2783930b01.png)

https://codepen.io/Spongman/pen/yGYQyX?editors=1010

**Comment by sanketsingh24** [comment] 2018-12-22 17:37
@Spongman  This also renders the same output, so I don't think there's any problem with ```resizeCanvas()```.

```js

function setup() {
	createCanvas(windowWidth, windowHeight, WEBGL);
	//resizeCanvas(windowWidth, windowHeight);
}

function draw() {
	background(0);
	sphere(width / 3);
	directionalLight(255, 255, 255, 0, 0, -1);
}
```

But I am not sure what is the desired output. :( 

https://codepen.io/sanketsingh24/pen/romBgZ

**Comment by Spongman** [comment] 2018-12-23 11:34
Hmmm what browser are you running where you see your example give that result? It looks fine on mine.

**Comment by sanketsingh24** [comment] 2018-12-23 11:57
I'm running firefox and getting the same output from both codes.

**Comment by Spongman** [comment] 2018-12-24 08:31
ah, i see it now. it doesn't repro in iOS safari for some reason. i think your example is closer to the issue. it's probably related to some shader state getting corrupted between frames.

**Comment by vedhant** [comment] 2019-01-10 11:20
> @Spongman This also renders the same output, so I don't think there's any problem with `resizeCanvas()`.
> 
> ```js
> function setup() {
> 	createCanvas(windowWidth, windowHeight, WEBGL);
> 	//resizeCanvas(windowWidth, windowHeight);
> }
> 
> function draw() {
> 	background(0);
> 	sphere(width / 3);
> 	directionalLight(255, 255, 255, 0, 0, -1);
> }
> ```
> 
> But I am not sure what is the desired output. :(
> 
> https://codepen.io/sanketsingh24/pen/romBgZ

I get the problem mentioned by @Spongman if I use p5 editor in chrome.
However i get it when i place the line ```directionalLight(255, 255, 255, 0, 0, -1); ``` in the setup function as in the example given by @Spongman.
So ```resizeCanvas()``` is breaking the lighting.

Anyways lighting still breaks when ```directionalLight()``` is used in the draw loop.

**Comment by Ajayneethikannan** [comment] 2019-03-02 22:31
Hello ! I noticed that the bug disappears , when you call directionalLight is called before calling sphere(),
as shown here https://codepen.io/AjayTDM/pen/jJqvga?editors=1010
Hopefully its of help !

**Comment by stalgiag** [comment] 2019-03-09 01:10
I am no longer able to reproduce this in Chrome 72.0.3626.121 on Windows 10. 

`directionalLight` calls do not have an effect on previously drawn geometry or when placed in setup but that is expected behavior. Calls to `resizeCanvas` do not affect these results. All examples posted in this thread work as expected for me.

**Comment by stalgiag** [comment] 2019-06-17 18:07
Hello all just pinging on this again because I am going to close this soon if we don't confirm that it can still be reproduced under some conditions. I have tried both @Spongman and @sanketsingh24's examples, with every variation I can think of with:
- `resizeCanvas`
-  no `resizeCanvas`
- `directionalLight` inside draw loop
- `directionalLight` inside setup
- `directionalLight` before and after `sphere`

I have tried the above in both the editor (0.8.0 release) and with a build of the current master branch with:

Android 8.0 Galaxy S7 
- Chrome 74.0.3729
- Firefox 67.0.2

Windows 10 Build 1803
- Chrome 75.0.3770.90
- Firefox 67.02
- Edge 42.17134

Rendering is as expected with all of the above tests. Let me know if anyone can recreate this currently.

**Comment by stalgiag** [comment] 2019-06-20 21:08
Closing for now! Ping me if anyone is able to recreate.

**Closed by stalgiag** 2019-06-20 21:08 UTC
Labels: area:webgl
