### ISSUE TITLE
textWidth doesn't work: ReferenceError: can't access lexical declaration `textWidth' before initialization

### ISSUE THREAD

**Issue by ProgrammingLife** [processing/p5.js#4448] opened 2020-04-01 22:49 UTC
This sample https://p5js.org/reference/#/p5/textWidth doesn't work for me:
"ReferenceError: can't access lexical declaration `textWidth' before initialization"

**Comment by akshay-99** [comment] 2020-04-01 22:59
Hi @ProgrammingLife! Does it not show an output on the example link itself?  Or does the error happen in your own sketch? If so, can you provide more details, such as the code you wrote, the p5 version you are using, and the browser you are using?

**Comment by lmccart** [comment] 2020-05-23 04:00
I'm going to close this because we're not able to reproduce. If you can provide more details including a code snippet, we can reopen this. Thanks!

**Closed by lmccart** 2020-05-23 04:00 UTC
Labels: bug
