### ISSUE TITLE
`npm test` command not working in Windows OS

### ISSUE THREAD

**Issue by AryanKoundal** [processing/p5.js#6207] opened 2023-06-13 17:52 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

v1.6.0

### Web browser and version

Any

### Operating System

Windows 10

### Steps to reproduce this

The command `npm test` is failing while doing the project setup.

### Steps:
1. Create a fork of the p5js repository
2. Clone the fork in the local machine
3. Execute `npm ci` 
4. Execute `npm test`

### Error after executing the last command
![image](https://github.com/processing/p5.js/assets/77334487/dc8272c5-5694-4032-afa2-9f889099da09)

```

**Comment by limzykenneth** [comment] 2023-06-14 12:27
The new line characters in the codebase (which should be LF) are being replaced by CRLF (ie. Windows style new line), possibly by your code editor. You can change that default in your settings or use the editorconfig plugin that will read the included config for p5.js.

**Comment by davepagurek** [comment] 2023-06-14 15:34
If you `git reset --hard`, if there were any line ending changes, those should be reverted right? When debugging we tried doing that then rebuilding but ran into the same issue unfortunately.

**Comment by limzykenneth** [comment] 2023-06-15 09:18
In that case it might be that the build step is generating files with that line ending and linting them. It would be helpful to know which files the linter is failing on.

**Comment by AryanKoundal** [comment] 2023-06-16 05:51
> 

If I consider the file path of the error generated, `utils/sample-linter,js` could be the file then.

**Comment by limzykenneth** [comment] 2023-06-16 23:00
I think that is where the error is thrown from instead of where the lint error is. Judging that it is thrown form the sample linter it is likely the reference example build is the one generating the Windows style line break instead of the Unix style line break.

If you can post a more complete terminal output we can have a closer look as well.

**Comment by AryanKoundal** [comment] 2023-06-20 06:20
> 

Sure, I'll recreate this scenario again. But the number of these, _"Expected linebreaks to be LF..."_ was more than the buffer of the terminal, and when I scrolled back to the top, the same _"Expected linebreaks to be LF..."_ was found for the same `utils/sample-linter.js` file but for different line in the same file.

**Comment by davepagurek** [comment] 2023-07-25 14:33
Btw, someone else on the p5 discord just ran into this same issue on Windows on a fresh install. Still not sure what the cause is though, unfortunately without a Windows machine myself I can't do too much to help debug

**Comment by SilasVM** [comment] 2023-07-31 18:33
One thing I did that fixed this on windows was run `git config --global core.autocrlf false`. 
You can check the value of this variable with `git config core.autocrlf`
From what I know this pretty much prevents windows from messing with the line endings and imports them as intended

This should be run before cloning your repo locally. I've had some others in my cohort run the same command and it fixed their issues. Let me know if this helps.

**Comment by SilasVM** [comment] 2023-08-07 20:07
I've opened PR  #6317 which is an option to fix this indefinitely and user limzykenneth is looking for other Windows users to test it out. 

If you're on windows and open to testing it out here are some instructions on what to run from the CL:
1.  Run the following  : `git config --global core.autocrlf true`, in your terminal to ensure default settings are in place. 
2. Run `git clone https://github.com/SilasVM/p5.js.git`
3. Enter your new clone with `cd p5.js`
4. In your new clone run `npm ci`
5. Next run `npm test` and let us know the results [here](https://github.com/processing/p5.js/pull/6317)

Thank you in advance to any testers. ❤️

**Comment by davepagurek** [comment] 2023-08-17 12:16
I just tested on a PR currently failing the linter test from line ending issues by:
1. merging `main`
2. Running `npm run lint` to confirm it fails
3. Running `git rm --cached -r .; git reset --hard` to update the working tree with new line endings
4. Running `npm run lint` again
It seems like it hasn't updated the files. I'm going to make a follow-up PR to get that process working

**Comment by davepagurek** [comment] 2023-08-17 12:43
Actually, never mind, going to close this again. Pasting my comment from that PR:

> Just realizing now that this issue was caused by `autocrlf` being turned on initially for Windows: if it was on already (not through the git config) then this change is unnecessary; if it was off on Windows, then it wouldn't be converting files. So I think this change is actually unnecessary for future changes, and the issue with that branch is that the changes were made before the .gitattributes file was added.

Anyway, all good, going to close this, sorry for the noise!

**Closed by davepagurek** 2023-08-17 12:43 UTC
Labels: Bug, Build Process
