### ISSUE TITLE
ReadMe links redirecting to 404 page

### ISSUE THREAD

**Issue by umangutkarsh** [processing/p5.js#6614] opened 2023-12-09 17:01 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### Web browser and version

Chrome Version 119.0.6045.200 (Official Build) (64-bit)

### Operating System

Windows 10

### Steps:
1. Go to the documentation -> ReadMe
2. The following links not working.

### Screenshot
<img width="686" alt="p51" src="https://github.com/processing/p5.js/assets/95426993/4df121b5-6571-4b0d-96ca-14cae99da340">
<img width="698" alt="p52" src="https://github.com/processing/p5.js/assets/95426993/cf2a5be1-36ee-43de-bbe4-0f2dd205869a">

Getting this 404 page when clicking the link.
![404](https://github.com/processing/p5.js/assets/95426993/6192137b-b551-49db-8b36-c6f3ce3cf2d1)

**Comment by umangutkarsh** [comment] 2023-12-09 17:26
@all-contributors please add @umangutkarsh  for documentation

**Comment by limzykenneth** [comment] 2023-12-09 23:50
Duplicate of https://github.com/processing/p5.js-website/issues/1345

**Closed by limzykenneth** 2023-12-09 23:50 UTC
Labels: Bug
