### ISSUE TITLE
Local Fonts not Loading on MacOSX 

### ISSUE THREAD

**Issue by dkgrieshammer** [processing/p5.js#5850] opened 2022-11-04 10:24 UTC
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [X] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.1.9 - 1.5

### Web browser and version

Chrome 107.0.5304.87, Firefox 105.0.3

### Operating System

MacOSX 12.6 (21G115)

### Steps to reproduce this

Local fonts are not loading on MacOSX; website keeps showing `...loading` so preload function never finishes
Any help highly appreciated 🙏

### Steps:
1. download example from p5js editor [https://editor.p5js.org/sojamo/sketches/mvEZEFfB6](https://editor.p5js.org/sojamo/sketches/mvEZEFfB6)
2. open Local Server in downloaded folder tried local dev server with certificates as well as `python -m SimpleHTTPServer`
3. open browser at https://localhost:8000/ 
4. Tried different versions of p5js 1.1.9 to 1.5, no difference
5. changed access rights of dir to 777 just to see if it's an access problem, doesn't help 

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/2266596/199949558-dac1520b-aeae-4bd9-9ed0-ee011f209d1f.png">

### :

```js

// Load fonts in WEBGL mode by uploading the font-file
// eg. ttf to your Sketch Files
// 
// check the Sketch Files and the additional file
// KronaOne-Regular.ttf
//
// You must load and set a font before drawing text. 
// See `loadFont` and `textFont` for more details. 
//
// if you are using the default renderer, you can use
// the link tag inside the index.html file, see example:
//
// https://editor.p5js.org/sojamo/sketches/yvc00Kv1x


let font;

function preload() {
  font = loadFont("KronaOne-Regular.ttf");
}

function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  textFont(font);
  textSize(windowWidth*0.1);
}

function draw() {
  background(240);
  fill(40);
  textAlign(CENTER);
  push();
  translate(0,tan(frameCount*0.01)*20);
  rotateX(frameCount*0.01);
  rotateY(frameCount*0.01);
  text("Remix me", 0,0);
  pop();
}

```

**Comment by dkgrieshammer** [comment] 2022-11-04 10:45
After further investigation it seems the fonts are being corrupted when downloading the folder from  p5js web editor. Seems there is something wrong there

<img width="409" alt="image" src="https://user-images.githubusercontent.com/2266596/199954193-1b66d256-5ccb-4952-a57d-4821113a4d60.png">
### Reproduce (on MacOSX)
1. download example from p5js web editor: https://editor.p5js.org/sojamo/sketches/mvEZEFfB6
2. unzip folder
3. quick preview of font file in assets folder is not showing preview
4. double click will not open in font manager

**Comment by davepagurek** [comment] 2022-11-04 11:52
Thanks for filing this and for your follow-up information! I think you're right about the font file corruption, it looks like your fonts are being corrupted from this bug: https://github.com/processing/p5.js-web-editor/issues/2075

Since it seems that, like you said, the issue isn't p5.js but the zipped download from the p5 web editor, for organizational purposes, I'm going to close this issue. We can continue the conversation in the web editor issue I linked, or we can reopen this issue here if we discover that it might still be related to p5.js itself.

**Closed by davepagurek** 2022-11-04 11:52 UTC
Labels: Bug, Area:Core, Area:Typography
