### ISSUE TITLE
position of the element always stays absolute in dom lib

### ISSUE THREAD

**Issue by Dheeeraj** [processing/p5.js#2630] opened 2018-02-03 21:12 UTC
- [x] Found a bug
- [x] Other ( In dom lib )
- [x] Desktop/Laptop
- p5.js version: 0.6.0 (dom version:0.6.0)
- Web browser and version: chrome Version 63.0.3239.108
- Operating System: Windows 10

in the following code as you can see i am trying to change position style to relative but it stays always absolute 

````javascript
var scoreHtml
function setup() {
 createCanvas(400,400);
 scoreHtml=createP('score:').style('position','relative');
}
function draw() {
   background(70);
}
`````

**Comment by lmccart** [comment] 2018-02-04 01:40
I'm not able to reproduce this. Note that if you are setting position:relative, you will need to specify two offsets (top + left for example) to move it to a position.

```javascript
scoreHtml=createP('score:').style('position:relative;top:10px;left:100px;');
```
https://developer.mozilla.org/en-US/docs/Web/CSS/position

**Comment by Dheeeraj** [comment] 2018-02-04 11:04
ho i was tying to do this below way it didn't worked position was staying at absolute .thank you
 now it worked for me in the way you said
```javascript
 scoreHtml=createP('score:').style('position','relative');
scoreHtml.style('top','50px');
```

**Comment by lmccart** [comment] 2018-02-04 15:09
you need to set a left or right property as well i think. but yes, you can break it into two lines.
for further help, you can post programming questions in the [forum](http://forum.processing.org)

**Comment by aparrish** [comment] 2018-11-28 13:16
I ran into this same behavior with 0.7.2. Here's a sketch to reproduce:

https://editor.p5js.org/allison.parrish/sketches/rJbDQMnR7

Using `elem.style('position', 'relative')` doesn't work (the position remains absolute), while `elem.style('position: relative')` works as expected. While [the documentation indicates](https://p5js.org/reference/#/p5.Element/style) that `"position"` as a parameter triggers special behavior in this method (i.e., letting you set pixel offsets for absolute position), it's not clear from the documentation that attempting to use the method with a valid value for the CSS 'position' attribute will fail. (The problem appears to be on [this line](https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L1668), which calls the `position()` method regardless of the value of the second parameter of `.style()`).

**Comment by lmccart** [comment] 2019-03-06 06:59
I'm going to close this one as it's discussed more thoroughly and tracked over here now: https://github.com/processing/p5.js/issues/3447

**Closed by lmccart** 2019-03-06 06:59 UTC
