### ISSUE TITLE
p5 image() friendly error message needs clarification

### ISSUE THREAD

**Issue by ryanachten** [processing/p5.js#2706] opened 2018-03-15 03:04 UTC
- [x] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

- [x] Image

- [x] Desktop/Laptop

- p5.js version: 0.6.0

- Steps to reproduce this:

Am getting the following friendly error message from p5 concerning arguments passed to the p.image() (with p5 in instance mode).

`p5.js says: image() was expecting p5.Image|p5.Element for parameter #0 (zero-based index), received p5.Element instead at webpack-internal:///239:103:9. [http://p5js.org/reference/#p5/image]`

Message results from calls such as this: `p.image(video, p.mouseX-vWidth/2, p.mouseY-vHeight/2, vWidth, vHeight);`.
_Video_ in this case is a `p5.MediaElement` returned from `p.createCapture( p.VIDEO )`.

It is unclear as to what is required to resolve the issue since the friendly error message says it was _'expecting a p5.Image or p5.Element'_ and has _'received p5.Element instead'_ (p5.MediaElement apparently being a subclass of p5.Element). 

(NB: Was referred here from the Processing forum)

**Comment by Spongman** [comment] 2018-03-15 21:19
i believe this is a dupe of #2576, which was fixed with #2582, but has not yet been released.

can you verify that this is fixed in this build: https://github.com/Spongman/p5.js/releases/tag/untagged-516916da5822156a6263/ ?

**Comment by ryanachten** [comment] 2018-03-15 22:24
@Spongman can verify the friendly error message isn't present when using the unreleased build

**Closed** 2018-03-16 15:05 UTC
