### ISSUE TITLE
more transparency issues webgl

### ISSUE THREAD

**Issue by saitogroup** [processing/p5.js#2677] opened 2018-03-01 23:00 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: p5.js v0.5.16 December 28, 2017
- Web browser and version: Version 64.0.3282.140 (Official Build) (64-bit)
- Operating System: 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"

- Steps to reproduce this:
https://saitogroup.github.io/basic/ <-- it's hosted on github and you can see the issue

- - - - - - - - - - - - -

(1.) Those red lines should show through the box that is covered in pgraphics; they don't.
(2.) One of the sides of the box that is covered in Pgraphics isn't transparent; all the rest are.
(3.) I tried putting a sphere in the sphere with a specular material and a transparency, but that didn't work.
(4.) I tried using the most recent version of p5.js and that made the problem worse; it eliminated the transparency of the pgraphics and you couldn't see the sphere inside

Very keen to know how to better manipulate transparencies...

**Comment by Spongman** [comment] 2018-03-01 23:09
i think this is related to #2616. the visibility of semi-transparent faces depends entirely on the order in which they were drawn. in order to get this kind of effect right you need to disable the z-buffer and sort your render order back-to-front (which is hard with primities like `box` & `sphere`)

**Comment by saitogroup** [comment] 2018-03-01 23:46
@Spongman ; hiya, thanks for getting back so fast; I am a web-graphics novice; does that basically mean that for the moment, this is beyond my capability? (at some point, I will learn three.js); are there no p5-y ways to handle this problem?

**Comment by saitogroup** [comment] 2018-03-01 23:56
@Spongman I appear to have fixed the issue with the intersecting lines (as per your suggestion) by changing the draw order; I drew the lines before anything else and it worked. Now trying to put a sphere in the sphere; standby.

**Comment by saitogroup** [comment] 2018-03-02 00:00
@Spongman OK, so, yes the intersecting lines cut through the pgraphics box, but no can't put a sphere within the sphere even if I change the order (partial fix is awesome though!).

**Comment by kjhollen** [comment] 2018-06-07 00:54
closing as a duplicate of #2616

**Closed by kjhollen** 2018-06-07 00:54 UTC
Labels: area:webgl
