### ISSUE TITLE
noSmooth behaviour inconsistent

### ISSUE THREAD

**Issue by TheCell** [processing/p5.js#2659] opened 2018-02-21 11:37 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [x] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.6.0 January 19, 2018
- Web browser and version: Firefox 58.0.2 (64-Bit) / Google Chrome 64.0.3282.167 (Offizieller Build) (64-Bit)
- Operating System: Windows 10 Home and Android 8.1
- Steps to reproduce this:
1. Programmed the Floyd Steinberg Dithering and the output is inconsistent. I am using noSmooth and I read in this issue https://github.com/processing/p5.js/issues/1381 that the noSmooth only works on canvas rescaling. The output therefore is unsatisfying, wanted to ask for the current state of the issue. Any response from Mozilla or planned workaround?
2. The inconsistency occurs when generating the image
    - Zoom in to 300% on Firefox or 500% on Chrome: noSmooth does work
    - having it set random zoomlevels: sometimes it works.
    - Having it at normal: 100% the smoothing occures all the time.
The Code is accessible [Github](https://github.com/TheCell/devSpace/tree/master/FloydSteinbergDithering) and a working example can be found here [Example](http://dev.thecell.eu/floydSteinbergDithering/) and here are example images:

wrong output at 100%
![examplewrongoutput](https://user-images.githubusercontent.com/3481579/36478076-c2994c1c-1703-11e8-960f-e0bd970c47d2.PNG)
right output at zoom level 300%
![exampleoutput](https://user-images.githubusercontent.com/3481579/36478075-c2813348-1703-11e8-8cc9-d7e704cd7167.PNG)

**Comment by limzykenneth** [comment] 2018-02-21 15:53
`noSmooth` and in turn `imageSmoothingEnabled` is designed to work when you resize images, ie. say you have a 200px by 200px image and you draw it 400px by 400px on the canvas, It does not affect browser zooming. The dithering algorithm you are using probably need to be tweaked to work on the right resolution in this case.

**Comment by TheCell** [comment] 2018-02-21 23:19
Thanks for your answer. I do see that `noSmooth` is not designed for this as it stands right now. I wanted to get feedback on the status of the Mozilla Request from the linked issue, maybe Mozilla will update this in the future or a workaround function is beeing made for p5js.

The Dithering Algorithm was written by me using the Wikipedia and the Coding Challenge 90 from Shiffman. As you said it does not affect browser zooming but this issue is in fact saying that it is _sometimes_. That the algorithm is the problem could only be the case when the image density is changed while zoomed in with the browser I did not check that. But the two images above were made after each other only by pressing refresh in the browser and having different zoom levels. The first image clearly shows that smoothing is occuring. This asumption is based on the observation that the pixels in the first image are not all equal in size. The algorithm loads the pixels and goes through pixel by pixel.

**Comment by limzykenneth** [comment] 2018-02-22 14:35
I'm not aware of any request or bug report being sent to Mozilla or any other vendors regarding this issue, the link in the issue simply links to MDN's documentation of `imageSmoothingEnabled`.

I'm also not entirely sure why and how the issue is occuring in this case, maybe it is about pixel density, maybe it is something else, I don't have a clear idea and so couldn't say for sure if a workaround is even possible. 

> As you said it does not affect browser zooming but this issue is in fact saying that it is sometimes.

Do you mean that if `noSmooth` was not called, this issue doesn't present itself?

**Comment by TheCell** [comment] 2018-02-22 15:49
Hey thanks for the answer and sorry for bothering you. I made a big mistake and was so occupied in finding out if the smoothing occurs all the time that I forgot to check without noSmooth. It does occur even if I comment out noSmooth in the setup. So this issue basically is wortthless :/ I am not sure where to push further with this issue.

**Comment by limzykenneth** [comment] 2018-02-22 15:53
No worries! I would still be suspicious of the implementation of the dithering algorithm especially since I don't think it take into account browser zooming (however that works and how it affects the canvas/algorithm). I'm not sure what is the best next step to solve this, but if there isn't an obvious bug in p5.js I suggest closing this and maybe asking this question on the [forum](https://forum.processing.org) or stackoverflow, hopefully someone there would have experience with this kind of problem.

**Comment by Spongman** [comment] 2018-02-22 16:15
Does it make any difference if your put 'pixelDensity(1);' at the start of your 'setup()' function?

**Comment by TheCell** [comment] 2018-02-22 16:44
ok, thanks again @limzykenneth 
Yes @Spongman after putting in the `pixelDensity(1)` it always smoothed. Therefore I conclude that the zoom of the browser does mess with the p5 density. I will have a look at my algorithm and incorporate the density into it.

**Closed** 2018-02-26 02:29 UTC
