### ISSUE TITLE
loadJSON() doesn't return an array

### ISSUE THREAD

**Issue by benswift** [processing/p5.js#2207] opened 2017-09-26 02:59 UTC
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

- p5.js version: 0.5.14

#### Feature enhancement details:

I'm not sure if this is the desired behaviour, but `loadJSON()` doesn't return an array (even if the top-level object in the `.json` file is an array). Instead, it returns an object with array-like integer properties, but it doesn't have the Array prototype and therefore doesn't have `.map()`, etc.

Is this the expected behaviour? If so, is there any reason for it?

**Comment by lmccart** [comment] 2017-09-26 03:00
thanks! this is a duplicate of https://github.com/processing/p5.js/issues/2154, so we'll follow up over there

**Closed by lmccart** 2017-09-26 03:00 UTC

**Comment by benswift** [comment] 2017-09-26 03:13
Thanks. Sorry about the duplicate.
