### ISSUE TITLE
Trying to create graphics with WebGL throws TypeError

### ISSUE THREAD

**Issue by TheChilliPL** [processing/p5.js#2496] opened 2018-01-05 19:35 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 
Trying to create graphics with WEBGL throws TypeError:
```
p5.min.js:36 Uncaught TypeError: Cannot read property 'apply' of undefined
    at d.RendererGL._applyColorBlend (p5.min.js:36)
    at d.RendererGL.fill (p5.min.js:37)
    at new d.RendererGL (p5.min.js:37)
    at new d.Graphics (p5.min.js:33)
    at e.d.createGraphics (p5.min.js:33)
    at draw (script.js:38)
    at e.d.redraw (p5.min.js:33)
    at e.<anonymous> (p5.min.js:32)
    at e.<anonymous> (p5.min.js:32)
    at new e (p5.min.js:32)
```

- p5.js version: 0.5.16
- Web browser and version: Google Chrome 63.0.3239.108
- Operating System: Windows 10 Version 10.0.16299 Compilation 16299
- Steps to reproduce this:
```javascript
var gpx = createGraphics(width, height, WEBGL);
```

**Comment by TheChilliPL** [comment] 2018-01-05 19:38
Using createCanvas(width, height, WEBGL) works though

**Comment by Spongman** [comment] 2018-01-05 22:45
i think this is a dupe of #2478

**Comment by mlarghydracept** [comment] 2018-01-05 23:27
Closing as per @Spongman's point that this is a dupe. Follow that issue to get updates.

**Closed by mlarghydracept** 2018-01-05 23:27 UTC
