### ISSUE TITLE
loadTable() parses an extra row of one undefined value

### ISSUE THREAD

**Issue by iaindillingham** [processing/p5.js#623] opened 2015-05-21 21:12 UTC
I've encountered the following issue when calling ``loadTable()`` in Firefox both on the Mac and on Ubuntu. In each case, I was using the most recent version of Firefox (38.0.1) and of P5.js (0.4.4).

Given the following CSV:
```
column_1,column_2,column_3
r1_c1,r1_c2,r1_c3
r2_c1,r2_c2,r2_c3
r3_c1,r3_c2,r3_c3
```
The following sketch should print 3 to the console, but instead prints 4:
```
var table;

function preload() {
  table = loadTable("data.csv", "header");
}

function setup() {
  print(table.getRowCount());
}
```
On closer inspection, the final row consists of one ``undefined`` value. This occurs when the CSV terminates with and without a single trailing newline; and when the ``"header"`` parameter is and isn't passed to ``loadTable()``. The console also reports a syntax error within the CSV, although gives no further information.

The workaround is simple:
```
var table;

function preload() {
  table = loadTable("data.csv", "header");
}

function setup() {
  table.removeRow(table.getRowCount() - 1);
  print(table.getRowCount());
}
```
However, it would be nice not to have to remember to remove the final row! Would anyone have any suggestions as to the cause of this issue?

**Comment by sarahgp** [comment] 2015-05-26 21:18
I ran the following code — with the same csv example file — on the latest versions of Firefox, Safari, and Chrome on Mac, and in all cases `3` printed in the console. 

```js
var table;

function preload() {
  table = loadTable("data.csv", "header");
}

function setup() {
  // put setup code here
  // createCanvas(600, 400);
  print(table.getRowCount());
}

function draw() {
  // put drawing code here
}
```

**Comment by workergnome** [comment] 2015-05-27 12:18
@iaindillingham, we're having a hard time reproducing this bug.  It's possible that there's something going on with the `preload()`, and that it's an async problem; it could also be that there's something strange with your specific CSV file.

Could you upload your CSV file somewhere so we can test against the exact file?  Thanks!

**Comment by sarahgp** [comment] 2015-05-27 14:07
I realized looking at this that my version made a call to the draw function not included in the original report, so I tested without. No change, still can't reproduce, but wanted to let you guys know that's not it.

**Comment by lmccart** [comment] 2015-05-27 14:08
ok, I'm closing this for now, please reopen if anyone can reproduce

**Comment by iaindillingham** [comment] 2015-05-27 18:59
Hello everyone,
Thanks for your efforts with this. I've tested with the code given by @sarahgp and 4 -- rather than the expected 3 -- printed to the console (Firefox 38.0.1 on OSX 10.10.3). For reference, you can find my code here:
https://github.com/iaindillingham/p5-sketches/tree/master/table_test
As I mentioned, I tried with and without the trailing newline in data.csv. In both cases, the error persisted. I also tried with and without the call to ``draw()`` (as noted by @sarahgp) and again, the error persisted.
That said, if you can't reproduce the error, then you can't do much about it! I'll continue to investigate.
Iain

**Comment by workergnome** [comment] 2015-05-27 19:52
So, @sarahgp and I are playing with this.  We can duplicate it with your repo—it has *something* to do with the trailing line return.  If we remove the trailing return, it reports `3` as expected; if the extra line exists, we get `4`.

Would you mind double-checking?  Also, what text-editor are you using?  It could have something to do with CR/LF line endings vs OSX just LF.

**Comment by sarahgp** [comment] 2015-05-27 19:55
We've definitely narrowed it down to the data file — if I point your repo at my version of the file, it returns `3`.

**Comment by iaindillingham** [comment] 2015-05-28 18:03
Interesting. I created the file using [Atom](https://atom.io/), which gives it as UTF-8. The line-end character is just LF. The error persists when I convert to CR/LF line endings, though.

Okay, I think I've got it: the file -- either CR/LF or just LF -- ends with an EOL marker. When it doesn't, then the results are as expected. It's fairly common to have a text editor add an EOL marker on save (I use this feature in Komodo, TextWrangler, and Atom). Would it be possible to check the final line in whatever code parses the CSV? If it's an empty line, then the file probably ends with an EOL marker.

**Comment by workergnome** [comment] 2015-05-28 19:38
Reading over the CSV quasi-standard, it looks like a trailing CR/LF is a valid end-of file, and shouldn't create a new row.  (see <https://tools.ietf.org/html/rfc4180>).

That means that we're not in accordance with the spec, and you are.  We found a valid bug! High fives all around!

I'll try and get this resolved in the next day or two.

**Comment by iaindillingham** [comment] 2015-05-28 21:02
Great digging, @workergnome! And thank you to everyone for very constructive comments.

**Comment by workergnome** [comment] 2015-05-29 00:55
Thanks to @mxchelle, this issue should be resolved and merged!  

@iaindillingham, when you get a chance, can you check if the changes in the master branch of the repo work for you?

**Closed by workergnome** 2015-05-29 00:55 UTC
Labels: area:input, firefox, osx, severity:minor, ubuntu
