### ISSUE TITLE
RECT Function BUG - v.0.6.0 jan 19 2018

### ISSUE THREAD

**Issue by millerarocha** [processing/p5.js#2685] opened 2018-03-06 13:38 UTC
#### Nature of issue?

- [X ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [X ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [X ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: V.0.6.0 January 19 2018
- Web browser and version: Chrome, not tested in others
- Operating System: Windows
- Steps to reproduce this:

I've updated a simple program to the new version 0.6.0 and something happens, the rect function has a bug. I draw a rectangle with rounded corners and the first round parameter was applied  to all corners, so my image crashed. With the version 0.5.16 Nov 17 2018 works perfect. I attached a zip with two folders, the same program but different p5.js version.

Thanks!

Miller

[P5js version comparisson.zip](https://github.com/processing/p5.js/files/1785180/P5js.version.comparisson.zip)

**Comment by lmccart** [comment] 2018-03-06 14:54
thanks @millerarocha could you please post a snippet of the rect code line you are using in your sketch?

**Comment by millerarocha** [comment] 2018-03-06 15:00
Thanks for your response. 

rect(250,100,200,250,100,100,0,0);

That's how i'm using in my sketch rect code, the same code but different results from each version.

**Comment by jeonghopark** [comment] 2018-03-07 20:54
hey, maybe ?
> https://p5js.org/reference/#/p5/rect

`rect(250,100,200,250,100,100);`
or
`rect(250,100,200,250,100);`

**Comment by justinsulik** [comment] 2018-03-09 13:14
Had same issue as millerarocha with same versions. I've played around with the rect() function a bit. In version 0.5.16 rect(a, b, c, d, e, f, g, h) reads e,f,g,h as rounding parameters for the 4 corners. In 0.6.0 it reads e as the rounding parameter for top left, f as rounding parameter for the other 3 corners, and ignores g and h.

**Comment by Spongman** [comment] 2018-03-09 19:49
maye a dupe of #2640 (fixed in #2642) ?

**Comment by lmccart** [comment] 2018-04-28 01:07
should be fixed in 0.6.1

**Closed by lmccart** 2018-04-28 01:07 UTC
