### ISSUE TITLE
Offline documentation?

### ISSUE THREAD

**Issue by JobLeonard** [processing/p5.js#610] opened 2015-05-02 00:37 UTC
What I really like about the original Processing is that it comes with offline documentation, so I can easily program in it while (say) travelling without internet access. Could we have the same for p5.js?

I can understand if the default download doesn't include it, to keep the download small (especially once the framework stabilizes enough for the documentation to not really change between updates to the library). But a separate zip file with the full reference could be nice.

**Comment by lmccart** [comment] 2015-05-03 03:38
great, yes definitely, thanks! closing this issue as it's a duplicate of https://github.com/processing/p5.js-website/issues/81.

**Closed by lmccart** 2015-05-03 03:38 UTC

**Comment by JobLeonard** [comment] 2015-05-03 10:21
Oh right, sorry for the noise :). I searched for "offline" so I missed it.
