### ISSUE TITLE
line() function not working in WEBGL.

### ISSUE THREAD

**Issue by punitsoni** [processing/p5.js#1740] opened 2017-01-03 08:47 UTC
```
function setup() {
    createCanvas(windowWidth, windowHeight, WEBGL);
}

function draw(){
    line(0, 0, 0, 100, 0, 0);
}
```

Running this is causing following error message.

```
Uncaught TypeError: this._renderer.line is not a function
    at p5.line (p5.js:7935)
    at draw (sketch.js:13)
    at p5.redraw (p5.js:14100)
    at p5.<anonymous> (p5.js:9144)
    at p5.<anonymous> (p5.js:9050)
    at new p5 (p5.js:9320)
    at _globalInit (p5.js:5602)
```

From the documentation it looks like drawing 3D lines is supported. Please help.

**Comment by hkirat** [comment] 2017-01-05 13:20
Hi
The problem is that you are in the WEBGL mode.
Try removing WEBGL, should work fine. (Even for 3-D)

**Comment by lmccart** [comment] 2017-01-09 04:51
thanks. this is covered here: https://github.com/processing/p5.js/issues/1638, closing this one for organizational purposes

**Closed by lmccart** 2017-01-09 04:51 UTC
