### ISSUE TITLE
1.0.0 broke syntax for square with rounded corners

### ISSUE THREAD

**Issue by McGittyHub** [processing/p5.js#4343] opened 2020-03-03 10:44 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 1.0.0
- Steps to reproduce this:

```
// with 0.10.2: 
  square(x, y, size, corner_radius);

// with 1.0.0:
  square(x, y, size, size, corner_radius);
```

**Comment by AnuragGupta93** [comment] 2020-03-03 13:42
@McGittyHub @stalgiag Working on this issue. It may have been arisen due to some typo during parsing arguments in `square` method. Fixing in a while.

**Comment by AnuragGupta93** [comment] 2020-03-03 13:46
@McGittyHub I don't think this is a bug. You must have created the canvas in WEBGL mode in version 1.0.0. That's why it is showing irrelevant behavior. 
You can reproduce the code given below to get the desired output.
```
    function setup() {
        createCanvas(200, 200);
        square(70, 70, 60, 10);
      }
```

In WebGL mode, the addition argument represents:
```
detailX Integer: number of segments in the x-direction (for WebGL mode) (Optional)
detailY Integer: number of segments in the y-direction (for WebGL mode) (Optional)

```

That's why you are not getting the desired output.
@stalgiag You can close this issue.

**Comment by McGittyHub** [comment] 2020-03-03 13:51
using your code produces:

![image](https://user-images.githubusercontent.com/2076567/75781877-48ecaa00-5d5e-11ea-99fc-58f08c63cd19.png)

I have to add a second 60 to get the desired (rounded square) result:
![image](https://user-images.githubusercontent.com/2076567/75781976-746f9480-5d5e-11ea-98bf-1b9d36226420.png)

**Comment by AnuragGupta93** [comment] 2020-03-03 14:07
@McGittyHub That's strange. On the Web Editor, I get:
![image](https://user-images.githubusercontent.com/35900375/75783147-13f44d80-5d86-11ea-846e-fd40d3da611d.png)
And for double 60, I got: 
![image](https://user-images.githubusercontent.com/35900375/75783194-279fb400-5d86-11ea-8c12-db79b4809e40.png)

**Comment by McGittyHub** [comment] 2020-03-03 14:09
Please make sure that you're in fact running the 1.0.0 version and not 0.10.2 as is default on the web editor:
![image](https://user-images.githubusercontent.com/2076567/75783465-e8ab3780-5d60-11ea-8339-876524d83222.png)

**Comment by AnuragGupta93** [comment] 2020-03-03 14:17
Oh my bad. I assumed the web editor to use v 1.0.0 but don't think that's the case. It's still using 0.10.2 somehow. Correcting in a while.

**Comment by stalgiag** [comment] 2020-03-03 16:17
Thank you for the issue @McGittyHub !

Could it be the handling of arguments in [this function](https://github.com/processing/p5.js/blob/master/src/core/shape/2d_primitives.js#L641)? I can't parse this quickly enough right now but it seems plausible.

@outofambit would you be willing to take a look?

**Comment by outofambit** [comment] 2020-03-03 16:18
@stalgiag that’s my best guess too, and it’s likely that i broke this since i touched it last 😂

will have a look later today!

thanks for reporting this @mcgittyhub!

**Comment by AnuragGupta93** [comment] 2020-03-04 07:10
@McGittyHub @stalgiag @outofambit Please take a look into the mentioned PR.

**Closed** 2020-03-04 20:26 UTC
Labels: area:core, bug
